<%
RenewalLetter = ""
RenewalLetter = RenewalLetter & "<BR><table border=""1"" width=""750""><tbody><tr VALIGN=TOP>" & vbCrLf
RenewalLetter = RenewalLetter & "<td ALIGN=""LEFT""><FONT FACE=Calibri,Charcoal,Arial><B>CHANGE REQUESTS</B><BR><FONT SIZE=1><I>&nbsp;&nbsp;If we aren't able to honor your request, we will keep you in your current seats.<BR><BR></I></FONT><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR VALIGN=TOP><TD><INPUT TYPE=CHECKBOX style=background:#0000;></TD><TD>PLEASE MOVE MY SEATS ACCORDING TO THE FOLLOWING<BR>_________________________________________________<BR>_________________________________________________<BR>_________________________________________________<BR><BR></TD></TR><TR VALIGN=TOP><TD><INPUT TYPE=CHECKBOX style=background:#0000;></TD><TD>PLEASE CHANGE MY NUMBER OF SEATS<BR>Add _____ seats to my current order<BR><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><TD><INPUT TYPE=CHECKBOX style=background:#0000;></TD><TD>Willing to move in order to be seated together.</TD></TR><TR><TD><INPUT TYPE=CHECKBOX style=background:#0000;></TD><TD>Not willing to move; please keep seats as close as possible.</TD></TR></TABLE>Reduce by: ___ seats. Please keep seat numbers: __________</FONT></TD></TR></TABLE></td>" & vbCrLf
RenewalLetter = RenewalLetter & "<td ALIGN=""LEFT""><FONT FACE=Calibri,Charcoal,Arial><B>PAYMENT</B><BR><TABLE CELLPADDING=0 CELLSPACING=0><TR VALIGN=TOP><TD ALIGN=RIGHT><FONT SIZE=2>Subtotal</FONT></TD><TD ALIGN=RIGHT> " & FormatCurrency(LastTotal,2) & "</TD></TR><TR VALIGN=TOP><TD ALIGN=RIGHT><FONT SIZE=2>Optional Tax Deductible Contribution</FONT></TD><TD ALIGN=RIGHT>$100.00</TD></TR><TR VALIGN=TOP><TD ALIGN=RIGHT><B><FONT SIZE=2>TOTAL PAYMENT</FONT></B></TD><TD ALIGN=RIGHT><B>$________</B></TD></TR></TABLE><INPUT TYPE=CHECKBOX style=background:#0000;> Mastercard    <INPUT TYPE=CHECKBOX style=background:#0000;> Visa    <INPUT TYPE=CHECKBOX style=background:#0000;> Discover<BR><INPUT TYPE=CHECKBOX style=background:#0000;> American Express   <INPUT TYPE=CHECKBOX style=background:#0000;> Check #___________<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE=1><I>Please make check payable to Cityfolk</I></FONT><BR>Card #_____________________________<BR>Expiration Date______________________<BR>Name on Card (please print)<BR>__________________________________<BR>Signature___________________________</FONT></td>" & vbCrLf
RenewalLetter = RenewalLetter & "</tr></TBODY></TABLE>" & vbCrLf
RenewalLetter = RenewalLetter & "<TABLE border=""1"" width=""750""><TR><TD><FONT FACE=Calibri,Charcoal,Arial><B>CityFolk Box Office Use Only</B>&nbsp;&nbsp;&nbsp;Date Received:  ________________&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Date Entered:  ________________</TD></TR></TBODY></TABLE><FONT FACE=Calibri,Charcoal,Arial><I>If you sit with friends, please send renewal forms together.</I></FONT>" & vbCrLf
RenewalLetter = RenewalLetter & "<DIV>&nbsp;</DIV>" & vbCrLf
RenewalLetter = RenewalLetter & "<table border=""1""><tbody><tr><td ALIGN=""LEFT""><FONT FACE=Calibri,Charcoal,Arial><FONT SIZE=6><B>GENERAL SUBSCRIPTION INFORMATION</B></FONT></FONT></td></tr></TBODY></TABLE>" & vbCrLf
RenewalLetter = RenewalLetter & "<BR><table border=""0"" width=""750""><tbody><tr><td ALIGN=""LEFT""><FONT FACE=Calibri,Charcoal,Arial><B><FONT SIZE=4>2011–2012 CELTIC SERIES</FONT></B><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<B>bohola with dancers from the Richens-Timm Academy of Irish Dance</B> – <FONT SIZE=2><I>Irish piano accordion virtuoso Jimmy Keane and singer Pat Broaders will be joined by talented local Irish dancers.</I></FONT> <B>CH • Saturday, October 22, 2011</B><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<B>Natalie MacMaster: Christmas in Cape Breton</B> – <FONT SIZE=2><I>The award-winning fiddler and step-dancer shares holiday traditions from her beloved Cape Breton in this tuneful new program for the whole family.</I></FONT> <B>DMC • Sunday, December 4, 2011</B><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<B>Genticorum</B> – <FONT SIZE=2><I>This fast-rising Québécois band is an acoustic power trio with a distinctive sound combining gorgeous vocal harmonies with fiddle, flute, and foot percussion.</I></FONT> <B>CH • Saturday, February 25, 2012</B><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<BR><HR SIZE=4><B><FONT SIZE=4>HELPFUL HINTS</FONT></B><BR><FONT SIZE=2><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR VALIGN=TOP><TD>" & vbCrLf
RenewalLetter = RenewalLetter & "• <B>Renew by June 24 to keep your current seats.</B> All subscriptions which are not paid by June 30 will be released for sale. Single tickets go on sale on July 1.<BR>" & vbCrLf
RenewalLetter = RenewalLetter & "• <B>The Cityfolk Box Office is the outlet for tickets to all Cityfolk concerts.</B> Visit www.cityfolk.org, call (937) 496–3863, or purchase your tickets by mail. If you have any questions, contact the Box Office at (937) 496–3863 or tickets@cityfolk.org. The Box Office is staffed from Monday – Friday from 10 am to 3 pm.<BR>" & vbCrLf
RenewalLetter = RenewalLetter & "• Please remember that our ability to fulfill your seat change request may be dependent on previously received subscription requests. Every effort will be made to accommodate you; however, we cannot guarantee our ability to grant your request.<BR>" & vbCrLf
RenewalLetter = RenewalLetter & "• <B>Subscription requests are filled in the order in which they are received.</B> The earlier you renew, the better your chance of receiving your change request.<BR>" & vbCrLf
RenewalLetter = RenewalLetter & "• <B>Please be as specific as possible in your request.</B> It is much easier for us to meet your needs if we clearly understand what is (or is not) acceptable to you. Here are some questions you may want to consider:<BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<UL><LI><I>When requesting seats in the center: Are you willing to move back (farther from the stage) in order to do so? If so, how far?</I>" & vbCrLf
RenewalLetter = RenewalLetter & "<LI><I>When requesting an aisle seat: Are you willing to take an outside aisle? Are you willing to move back (farther from the stage)? If so, how far?</I>" & vbCrLf
RenewalLetter = RenewalLetter & "<LI><I>When requesting to move closer to the stage: Are you willing to move to the sides in order to do so?</I></UL>" & vbCrLf
RenewalLetter = RenewalLetter & "• <B>If more than one account is involved</B> – your request involves not only your seats, but also those of friends – we MUST receive all of your orders in the same envelope. We cannot ensure that orders received separately will be seated together.</FONT></TD>" & vbCrLf
RenewalLetter = RenewalLetter & "<TD><IMG SRC=""/PrivateLabel/CityFolk/Renewal/Images/Centennial Hall seat map.jpg"" WIDTH=200><BR><BR><IMG SRC=""/PrivateLabel/CityFolk/Renewal/Images/Masonic Seat Map.jpg"" WIDTH=200></TD></TR></TABLE>" & vbCrLf
RenewalLetter = RenewalLetter & "<BR><CENTER><FONT SIZE=5><B>2011–2012 SUBSCRIPTION PRICES</B></FONT><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<FONT SIZE=4><I>Save 12% over single ticket prices!</I></FONT><BR><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<FONT SIZE=5>A $70.40 • B $64.24 • C $57.20</FONT><BR><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<FONT SIZE=4><B>Questions? Call the Cityfolk Box Office at (937) 496–3863</B></FONT><BR>" & vbCrLf
RenewalLetter = RenewalLetter & "<FONT SIZE=4>126 N. Main St. Suite 220 • Dayton, OH 45402-1766 • tickets@cityfolk.org</FONT><BR></CENTER>" & vbCrLf
RenewalLetter = RenewalLetter & "</FONT></td></tr></TBODY></TABLE></CENTER>" & vbCrLf
Response.Write RenewalLetter & vbCrLf
%>