(function(){var f=true,g=null,h=false,aa=encodeURIComponent,i=navigator,ba=undefined,k=parseInt,l=document,ca=decodeURIComponent,n=Math;function da(a,b){return a.width=b}function ea(a,b){return a.toString=b}function fa(a,b){return a.height=b}
var ga="appendChild",o="push",p="valueOf",q="width",ha="round",s="slice",t="replace",ia="floor",ja="cookie",ka="charAt",la="_height_",u="indexOf",ma="domain",w="write",na="opera",x="_html_",oa="createElement",y="getParameter",pa="referrer",qa="name",ra="contentWindow",sa="getTime",ta="getElementsByTagName",z="toString",A="length",ua="plugins",B="prototype",C="document",D="split",E="userAgent",F="screen",va="body",wa="_width_",xa="call",ya="random",H="substring",za="navigator",I="height",J="join",
Ba="toLowerCase",K=this,Ca=function(a,b,c){a=a[D](".");c=c||K;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[A]&&(d=a.shift());)if(!a[A]&&b!==ba)c[d]=b;else c=c[d]?c[d]:(c[d]={})};n[ia](n[ya]()*2147483648)[z](36);
var Da=function(a,b){var c=b||K;if(arguments[A]>2){var d=Array[B][s][xa](arguments,2);return function(){var e=Array[B][s][xa](arguments);Array[B].unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},Ea=Date.now||function(){return+new Date},L=function(a,b,c){Ca(a,b,c)},Fa=function(a,b){function c(){}c.prototype=b[B];a.ra=b[B];a.prototype=new c};var M=function(a,b){da(this,a);fa(this,b)};ea(M[B],function(){return"("+this[q]+" x "+this[I]+")"});M[B].floor=function(){da(this,n[ia](this[q]));fa(this,n[ia](this[I]));return this};M[B].round=function(){da(this,n[ha](this[q]));fa(this,n[ha](this[I]));return this};var Ia=function(a){if(a[u]("&")!=-1)return"document"in K&&a[u]("<")==-1?Ga(a):Ha(a);return a},Ga=function(a){var b=K[C][oa]("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Ha=function(a){return a[t](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c[ka](0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return b}})},Ka=function(a,b){var c=0;a=
String(a)[t](/^[\s\xa0]+|[\s\xa0]+$/g,"")[D](".");b=String(b)[t](/^[\s\xa0]+|[\s\xa0]+$/g,"")[D](".");for(var d=n.max(a[A],b[A]),e=0;c==0&&e<d;e++){var m=a[e]||"",j=b[e]||"",r=new RegExp("(\\d*)(\\D*)","g"),v=new RegExp("(\\d*)(\\D*)","g");do{var N=r.exec(m)||["","",""],G=v.exec(j)||["","",""];if(N[0][A]==0&&G[0][A]==0)break;c=N[1][A]==0?0:k(N[1],10);var Aa=G[1][A]==0?0:k(G[1],10);c=Ja(c,Aa)||Ja(N[2][A]==0,G[2][A]==0)||Ja(N[2],G[2])}while(c==0)}return c},Ja=function(a,b){if(a<b)return-1;else if(a>
b)return 1;return 0};Ea();var La,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua=function(){return K[za]?K[za][E]:g},Va=function(){return K[za]},Wa=function(){Pa=Oa=Na=Ma=La=h;var a;if(a=Ua()){var b=Va();La=a[u]("Opera")==0;Ma=!La&&a[u]("MSIE")!=-1;Oa=(Na=!La&&a[u]("WebKit")!=-1)&&a[u]("Mobile")!=-1;Pa=!La&&!Na&&b.product=="Gecko"}};Wa();
var Xa=La,Ya=Ma,Za=Pa,$a=Na,ab=Oa,bb=function(){var a=Va();return a&&a.platform||""},cb=bb(),db=function(){Qa=cb[u]("Mac")!=-1;Ra=cb[u]("Win")!=-1;Sa=cb[u]("Linux")!=-1;Ta=!!Va()&&(Va().appVersion||"")[u]("X11")!=-1};db();var eb=function(){var a="",b;if(Xa&&K[na]){a=K[na].version;a=typeof a=="function"?a():a}else{if(Za)b=/rv\:([^\);]+)(\)|;)/;else if(Ya)b=/MSIE\s+([^\);]+)(\)|;)/;else if($a)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(Ua()))?a[1]:""}return a},fb=eb(),gb={};var hb=function(a){var b=a[C];if($a&&!(gb["500"]||(gb["500"]=Ka(fb,"500")>=0))&&!ab){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a[C].documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new M(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!Xa||Xa&&(gb["9.50"]||(gb["9.50"]=Ka(fb,"9.50")>=0)))?b.documentElement:b[va];return new M(a.clientWidth,a.clientHeight)};function ib(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a}function jb(a,b){if(a=="true")return f;if(a=="false")return h;return b}function O(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var kb=jb("false",h),lb=window;var mb="pagead2.googlesyndication.com",nb="googleads.g.doubleclick.net",ob="googleads2.g.doubleclick.net",qb="pubads.g.doubleclick.net",rb="securepubads.g.doubleclick.net",sb="partner.googleadservices.com",tb=O("pagead2.googlesyndication.com",mb);O("googleads.g.doubleclick.net",nb);O("",ob);O("pagead2.googlesyndication.com",mb);var ub=O("pubads.g.doubleclick.net",qb),vb=O("partner.googleadservices.com",sb),wb=O("securepubads.g.doubleclick.net",rb);function P(a){return typeof aa=="function"?aa(a):escape(a)}function xb(a,b,c){var d=l[oa]("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=l[ta]("head")[0];if(!e)return h;window.setTimeout(function(){e[ga](d)},0);return f}function yb(a){if(a in zb)return zb[a];return zb[a]=i[E][Ba]()[u](a)!=-1}var zb={};function Ab(){return yb("msie")&&!window[na]}
function Bb(){if(i[ua]&&i.mimeTypes[A]){var a=i[ua]["Shockwave Flash"];if(a&&a.description)return a.description[t](/([a-zA-Z]|\s)+/,"")[t](/(\s)+r/,".")}else if(i[E]&&i[E][u]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[z]()}else if(Ab()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==
6)return a[z]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(m){}}if(b){a=b.GetVariable("$version")[D](" ")[1];return a[t](/,/g,".")}}return"0"}function Cb(a,b){var c=n[ya]();if(c<b){b=n[ia](c/b*a[A]);return a[b]}return""}
var Db=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history[A];a.u_java=i.javaEnabled();if(window[F]){a.u_h=window[F][I];a.u_w=window[F][q];a.u_ah=window[F].availHeight;a.u_aw=window[F].availWidth;a.u_cd=window[F].colorDepth}if(i[ua])a.u_nplug=i[ua][A];if(i.mimeTypes)a.u_nmime=i.mimeTypes[A]},Eb=function(a){var b=lb;if(a&&b.top!=b)b=b.top;try{return b[C]&&!b[C][va]?new M(-1,-1):hb(b||window)}catch(c){return new M(-12245933,-12245933)}},Fb=function(a,b){var c=a[A];if(c==0)return 0;
b=b||305419896;for(var d=0;d<c;d++){var e=a.charCodeAt(d);b^=(b<<5)+(b>>2)+e&4294967295}return b},Gb=function(a){if(a==a.top)return 0;var b=[];b[o](l.URL);a[qa]&&b[o](a[qa]);a=f;a=Eb(!a);b[o](a[q][z]());b[o](a[I][z]());b=Fb(b[J](""));return b>0?b:4294967296+b};var Hb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ib={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Kb={google_only_pyv_ads:"pyv",
google_with_pyv_ads:"withpyv"};var Lb=l,Q=i,R=window;
function Mb(){var a=Lb[ja],b=n[ha]((new Date)[sa]()/1E3),c=R.google_analytics_domain_name;c=typeof c=="undefined"?Nb("auto"):Nb(c);var d=a[u]("__utma="+c+".")>-1,e=a[u]("__utmb="+c)>-1,m=a[u]("__utmc="+c)>-1,j={},r=!!R&&!!R.gaGlobal;if(d){a=a[D]("__utma="+c+".")[1][D](";")[0][D](".");j.sid=e&&m?a[3]+"":r&&R.gaGlobal.sid?R.gaGlobal.sid:b+"";j.vid=a[0]+"."+a[1];j.from_cookie=f}else{j.sid=r&&R.gaGlobal.sid?R.gaGlobal.sid:b+"";j.vid=r&&R.gaGlobal.vid?R.gaGlobal.vid:(n[ha](n[ya]()*2147483647)^Ob()&2147483647)+
"."+b;j.from_cookie=h}j.dh=c;j.hid=r&&R.gaGlobal.hid?R.gaGlobal.hid:n[ha](n[ya]()*2147483647);return R.gaGlobal=j}function Ob(){var a=Lb[ja]?Lb[ja]:"",b=R.history[A],c,d=[Q.appName,Q.version,Q.language?Q.language:Q.browserLanguage,Q.platform,Q[E],Q.javaEnabled()?1:0][J]("");if(R[F])d+=R[F][q]+"x"+R[F][I]+R[F].colorDepth;else if(R.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[F][q]+"x"+c[F][I]}d+=a;d+=Lb[pa]?Lb[pa]:"";for(a=d[A];b>0;)d+=b--^a++;return Pb(d)}
function Pb(a){var b=1,c=0,d;if(!(a==ba||a=="")){b=0;for(d=a[A]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Nb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Lb[ma];if("www."==a[H](0,4))a=a[H](4,a[A])}return Pb(a[Ba]())};function Qb(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=l[ma]}ea(Qb[B],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Rb(){this.v=Sb(this);this.N=h;if(!this.v)this.N=Tb(this)}Rb[B].M="__gads=";Rb[B].B="GoogleAdServingTest=";
var Vb=function(a,b){a.q=b._cookies_[0];if(a.q!=g){a.v=a.q._value_;Ub(a)}},Wb=function(a,b){a=(new Date)[p]();var c=new Date;c.setTime(a+b);return c},Xb=function(a){var b=15552E6;a=Wb(a,b);b="ID=12345:T="+b;var c="/",d=l[ma];return new Qb(b,a[p](),c,d)},Yb="http://"+vb+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Zb=function(a,b){if(!(a.v||!a.N)){a="script";var c=l[ma];b=Yb+"&client="+P(b)+"&domain="+P(c);l[w]("<"+a+' src="'+b+'"></'+a+">")}},Tb=function(a){l.cookie=a.B+"Good";
var b=$b(a,a.B);if(b=b=="Good"){var c=Wb(a,-1);l.cookie=a.B+"; expires="+c.toGMTString()}return b},Sb=function(a){return a=$b(a,a.M)},$b=function(a,b){a=l[ja];var c=a[u](b),d="";if(c!=-1){b=c+b[A];c=a[u](";",b);if(c==-1)c=a[A];d=a[H](b,c)}return d},Ub=function(a){if(a.q!=g)if(a.v){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.M+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;l.cookie=a}};var S=function(a){this.ga=a;this.T=[];this.S=0;this.G=[];this.aa=0;this.L=[];this.$=h;this.f=this.X="";this.Z=h},ac=function(a,b,c){var d=a.ga[c],e=a.T;a.ga[c]=function(m){if(m&&m[A]>0){var j=m[A]>1?m[1].url:g;e[o]([b,Ia(m[0].url),j])}d(m)}},bc=function(a){a.S++},cc=function(a,b){a.G[o](b)},dc=function(a){if(!a.$){xb("http://"+tb+"/pagead/osd.js");a.$=f}},ec=function(a,b){if(a.S>0){var c=l[ta]("iframe");a=a.Z?"google_ads_iframe_":"google_ads_frame";for(var d=0;d<c[A];d++){var e=c.item(d);e.src&&e[qa]&&
e[qa][u](a)==0&&b(e,e.src)}}},fc=function(a,b){a=a.T;if(a[A]>0)for(var c=l[ta]("a"),d=0;d<c[A];d++)for(var e=0;e<a[A];e++)if(c.item(d).href==a[e][1]){var m=c.item(d).parentNode;if(a[e][2])for(var j=m,r=0;r<4;r++){if(j.innerHTML[u](a[e][2])>0){m=j;break}j=j.parentNode}b(m,a[e][0]);a.splice(e,1);break}},hc=function(a,b){for(var c=0;c<a.G[A];c++){var d=a.G[c],e=gc(d);if(e)(e=l.getElementById("google_ads_div_"+e))&&b(e,d)}};S[B].Q=function(a){fc(this,a);hc(this,a);ec(this,a)};
S[B].setupOsd=function(a,b,c){this.aa=a;this.X=b;this.f=c};S[B].getOsdMode=function(){return this.aa};S[B].getEid=function(){return this.X};S[B].getCorrelator=function(){return this.f};S[B].R=function(){return this.T[A]+this.S+this.G[A]};S[B].setValidAdBlockTypes=function(a){this.L=a};
S[B].registerAdBlockByType=function(a,b,c){if(this.L[A]>0){for(var d=0;d<this.L[A];d++)if(this.L[d]==a){this.Z=c;if(a=="js")ac(this,b,"google_ad_request_done");else if(a=="html")bc(this);else a=="json_html"&&cc(this,b)}dc(this)}};var gc=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a[A]==2)return a[1];return""},ic=function(){window.__google_ad_urls||(window.__google_ad_urls=new S(window));return window.__google_ad_urls};L("Goog_AdSense_getAdAdapterInstance",ic);
L("Goog_AdSense_OsdAdapter",S);L("Goog_AdSense_OsdAdapter.prototype.numBlocks",S[B].R);L("Goog_AdSense_OsdAdapter.prototype.findBlocks",S[B].Q);L("Goog_AdSense_OsdAdapter.prototype.getOsdMode",S[B].getOsdMode);L("Goog_AdSense_OsdAdapter.prototype.getEid",S[B].getEid);L("Goog_AdSense_OsdAdapter.prototype.getCorrelator",S[B].getCorrelator);L("Goog_AdSense_OsdAdapter.prototype.setValidAdBlockTypes",S[B].setValidAdBlockTypes);L("Goog_AdSense_OsdAdapter.prototype.setupOsd",S[B].setupOsd);
L("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",S[B].registerAdBlockByType);function jc(a,b){try{return a.top[C].URL==b.URL}catch(c){}return h};var kc=/^(?:([^:\/?#]+):)?(?:\/\/(?:([^\/?#]*)@)?([^\/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,lc=function(a){return a&&ca(a)};var mc=function(a){this.fa=(this.O=a&&a.GA_jstiming)&&this.O.load};mc[B].tick=function(a,b){this.fa.tick(a,b)};mc[B].report=function(a){var b={};b.e=a;this.O.report(this.fa,b)};var nc=function(){};Fa(nc,mc);nc[B].tick=function(){};nc[B].report=function(){};var oc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var T=lb&&n[ya]()<ib("0.005",0.0010)&&lb.GA_jstiming&&lb.GA_jstiming.load&&lb.location.protocol=="http:"?new mc(lb):new nc(lb);T.tick("js_load");function U(a){return typeof a=="function"}function pc(a,b){if(typeof a!="string"||a[A]==0)return g;else if(typeof b!="string"||b[A]==0)return g;return qc(V(),a,b)}L("GA_googleAddSlot",pc);function _GA_googleInitializeAdEngine(a){if(!W()){rc(sc(a));tc(W())}}L("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function uc(){V().ha=f;_GA_googleInitializeAdEngine(g);var a=W().g;a=="sync"||a=="sync_sra"?W().j():vc(V())}L("GA_googleFetchAds",uc);function wc(){_GA_googleInitializeAdEngine("iframe");Zb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}L("GA_googleUseIframeRendering",wc);function xc(){var a=window.GA_googleEnv[y]("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}L("GA_googleUseSyncSRARendering",xc);
function yc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}L("GA_googleDomainResetUrl",yc);function zc(a){if(W()!=g)if(W().g!="iframe"){if(Ac(W()))if(W().K){var b=Bc(V(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(Cc(W(),a)!=g&&!W().l)return;W().n(a)}}L("GA_googleFillSlot",zc);function Dc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(W()!=g)if(W().g=="iframe"){qc(V(),a,b);a=new Ec(c,d,h,f);Fc(V(),b,a);W().n(b)}}L("GA_googleFillSlotWithSize",Dc);
function Gc(){Hc(new Ic(Hb));rc(g)}L("GA_googleResetAll",Gc);window.google_noFetch=h;function Jc(){window.google_noFetch=f}L("GA_googleNoFetch",Jc);function Kc(){window.google_delayFetch=f}L("GA_googleDelayFetch",Kc);function Ec(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ea(Ec[B],function(){return"[GA_GoogleAdSlotAttr: width="+this[wa]+", height="+this[la]+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Lc(a){var b={};a=a[D]("?");a=a[a[A]-1][D]("&");for(var c=0;c<a[A];c++){var d=a[c][D]("=");if(d[0])try{b[d[0][Ba]()]=d[A]>1?window.decodeURIComponent?ca(d[1][t](Mc," ")):unescape(d[1]):""}catch(e){}}return b}function Nc(a){a=a||l.URL;this.da=Lc(a)}Nc[B].getParameter=function(a){return a==g?g:this.da[a]};Nc[B].setParameter=function(a,b){this.da[a]=b};var Oc=function(){if(!kb)return"http://"+ub;return"https://"+wb};
function Pc(a){return a[t](/&/g,"&amp;")[t](/</g,"&lt;")[t](/>/g,"&gt;")[t](/\"/g,"&quot;")}function Qc(){this.D=g;this.ea=h;this.qa=(new Date)[p]()}
var Sc=function(a,b){if(a.D==g)if(!a.ea){a.D=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.D){var c=a.D[C],d=[];d[o]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[o]("<p>Google Ad Capture Window</p>");
for(var e in b)U(b[e])||d[o](Rc(a,e,b[e]));d[o]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[o]("<script>displayTime('blocked', pageStartTime);<\/script>");d[o]("<p>Total Page Load Time (ms): <label id='total'></label>");d[o]("</body>\n</html>");a=d[J]("\n");(b=window.GA_googleEnv[y]("google_capture_norender")!=g)?c[w](Pc(a)):c[w](a);c.close()}else a.ea=f}},Rc=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";var d="<p>Slot "+b+"</p>";c=c==g||c[x]==
g?"No ad":c[x];var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Tc(a){this.d={};this.C=a}var Uc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.C)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Vc=function(a,b){for(var c in b.d)U(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Tc[B].getAttribute=function(a){return this.d[a]};
Tc[B].h=function(){var a=[];for(var b in this.d)if(!U(this.d[b])){var c=Hb[b]||Ib[b]||Kb[b]||g,d=this.d[b];c&&d&&a[o](c+"="+P(d))}return a[J]("&")};
var Xc=function(a,b,c,d){a=Wc(a,b,c,d);b=[];a[0]&&a[0][A]>0&&b[o](a[0][J]("&"));a[1]&&a[1][A]>0&&b[o]("sps="+a[1][J]("|"));return b[J]("&")},Wc=function(a,b,c,d){var e=[],m=[];b=b.d;for(var j in d)if(!U(j)){var r=d[j];if(r){var v="";if(b[j]!=g)v=P(b[j]);var N=[],G=-1,Aa=-1;for(var pb in a)if(!U(a[pb])){++G;if(c[pb]==g)N[o]("");else{var Jb=c[pb].d;if(Jb[j]!=g){N[o](P(P(Jb[j])));Aa=G}else N[o]("")}}if(Aa>=0){G=P(v);v=[];v[o](G);for(G=0;G<=Aa;++G)v[o](N[G]);m[o](r+","+v[J](","))}else v&&e[o](r+"="+v)}}a=
[];a[o](e);a[o](m);return a};function Yc(a,b){this.J=a;this.s=b;this.V=0;this.na=this.P=this.U=h;this.la=this.ma=this.Y=this.ia=g}var Zc=function(a){a.P=f;a.ia=(new Date)[p]()},$c=function(a){a.Y=(new Date)[p]()},ad=function(a){a.na=f;a.ma=(new Date)[p]()},bd=function(a){a.la=(new Date)[p]()};ea(Yc[B],function(){return"[GA_GoogleAdSlot: pubid="+this.J+", name="+this.s+", loaded="+this.U+", tries="+this.V+"]"});
function Ic(a){this.a={};this.c=[];this.r={};this.C=a;this.ca=new Tc(this.C);this.A={};this.ha=h;this.o=g}
var qc=function(a,b,c){b=new Yc(b,c);return a.a[b.s]=b},cd=function(a,b){var c=[];for(var d in a.a)if(!U(a.a[d])){if(b){var e=Bc(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.P||c[o](e)}return c},dd=function(a,b){return cd(a,b)[A]},ed=function(a){var b=[];for(var c in a.a){var d=a.a[c];U(d)||d.P&&d.Y==g&&b[o](c)}return b},fd=function(a){var b=0;for(var c in a.a)if(!U(a.a[c])){var d=Bc(a,c);d!=g&&d._enabled_&&b++}return b},gd=function(a){for(var b in a.a)if(!U(a.a[b])){var c=a.a[b];Zc(c)}},hd=function(a,
b){a=a.a[b];Zc(a)},id=function(a,b){a=a.a[b];$c(a)},jd=function(a,b){a=a.a[b];ad(a)},kd=function(a,b){b=a.a[b];bd(b);oc(T,"ga_render",a.c[A],"ga_srt")},ld=function(a){var b=0;for(var c in a.a)U(a.a[c])||b++;return b};ea(Ic[B],function(){var a="[AdData:",b=[];for(var c in this.a)U(this.a[c])||b[o](this.a[c][z]());for(var d in this.r)U(this.r[d])||b[o]("["+d+","+this.r[d]+"]");a+=b[J]();a+="]";return a});
var md=function(a,b){return a.a[b]},nd=function(a,b,c){if(!(b==g||b[A]==0)){if(c==g||c[A]==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function od(a,b){nd(V(),a,b)}L("GA_googleAddAttr",od);var pd=function(a,b,c){Uc(a.ca,b,c)};function qd(a,b){pd(V(),a,b)}L("GA_googleAddAdSensePageAttr",qd);var rd=function(a){return a.ca},sd=function(a,b,c,d){if(!(b==g||b[A]==0)){if(W()==g||W().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.A[b];if(e==g)a.A[b]=new Tc(a.C);Uc(a.A[b],c,d)}};
function td(a,b,c){sd(V(),a,b,c)}L("GA_googleAddAdSenseSlotAttr",td);var ud=function(a,b){return a.A[b]},vd=function(){var a=Oc();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},vc=function(a){if(a.o!=g)W().j();else{var b=[];for(var c in a.a)U(a.a[c])||b[o](c);a=window.GS_googleGetIdsForAdSenseService();b=vd(window)+"&client="+escape(a)+"&page_slots="+escape(b[J]());l[w]("<script src = '"+b+"'><\/script>")}},wd=function(a,b){a.o=b;W().K=f;W().j()};function xd(a){wd(V(),a)}
L("GA_googleSetAdSlotAttributes",xd);var Fc=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;W().K=f},Bc=function(a,b){return a.o!=g?a.o[b]:g};function yd(a,b,c){if(!c||c<0||c>1)c=0;this.oa=n[ya]()<c;this.ja=a;this.W=b+"/pagead/gen_204?id="+P(a);this.ka=[]}
var X=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.W+="&"+b+"="+P(c)},zd=function(a){var b=V();for(var c in b.a){var d=b.a[c];if(!U(d)&&d.J!=g){X(a,"pub_id",d.J);break}}X(a,"nslots",ld(b)[z]());X(a,"pub_url",l.URL);X(a,"pub_ref",l[pa])},Ad=function(a){if(!a.oa||!a.ja||!a.W)return h;var b=new Image;b.src=a.W;a.ka[o](b);return f};function Y(a){this.i=g;this.o={};this.p=this.b="";this.l=a;this.m=this.I=this.t=h;this.g="sync";this.pa=Hb;this.u=f;this.K=h}
var tc=function(a){a.t=window.GA_googleEnv[y]("google_nofetch")!=g||window.google_noFetch;a.I=window.GA_googleEnv[y]("google_norender")!=g;a.m=window.GA_googleEnv[y]("google_capture")!=g||window.GA_googleEnv[y]("google_capture_norender")!=g;if(a.m)a.I=f;Bd(a,window);a.b=a.p;var b=Da(a.ba,a);Cd(a,window,b)},Cd=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,h);return f}return h};
Y[B].F=function(){this.m&&Sc(window.GA_googleAdCapture,this.i)};
var Dd=function(a){if(a.g=="sync_sra"){var b=V(),c=ld(b);b=b.c[A];if(c!=b){a.H=new yd("sra_mismatch",Oc(),ib("0.001",0.0010));X(a.H,"correlator",a.f);X(a.H,"fslots",b[z]());zd(a.H);Ad(a.H)}}},Ed=function(a){T.tick("ga_onload");T.report(a.g)},Fd=function(a){var b=ed(V());if(b[A]>0){a.z=new yd("missing_cb",Oc(),ib("0.01",0.0010));X(a.z,"pending",b[J]());X(a.z,"correlator",a.f);X(a.z,"impl",a.g);zd(a.z);Ad(a.z)}};
Y[B].ba=function(){Ed(this);this.F();Dd(this);Fd(this)};var Bd=function(a){var b=window.GA_googleEnv[y]("google_ad_url");if(b==g||b[A]==0)a.p=Oc()+"/gampad/ads?";else{if(b[ka](b[A]-1)!="?")b+="?";a.p=b}};Y[B].k=function(){};
var Cc=function(a,b){return a.i!=g?a.i[b]:g},Gd=function(){var a=i[E],b=a[u]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[u](";",b)))},Mc=/\+/g,Hd=function(a,b){b=b[Ba]();if(b[H](0,3)!="ca-")b="ca-"+b;return b},$=function(a,b,c){c!=g&&Z(a,b,P(c[z]()))},Z=function(a,b,c){if(c!=g&&c!="")a.b+=a.b[ka](a.b[A]-1)!="?"?"&"+b+"="+c:b+"="+c},Id=function(a,b){for(var c=cd(V(),a.u),d=[],e=[],m=[],j=c[A],r=0;r<j;r++){var v=c[r];m[o](v.s);if(!(b!=g&&b!=v.s)){d[o](v.s);e[o](Hd(a,v.J))}}$(a,"client",e[0]);if(a.l)m[A]>
0&&$(a,"page_slots",m[J]());else{$(a,"slotname",d[J]());V().c[A]>0&&$(a,"page_slots",V().c[J]())}},Jd=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[u]("google_preview=",a);c=b[u]("&",a);if(c==-1){c=b[A]-1;a-=1}return b[H](0,a)+b[H](c+1,b[A])}return b},Kd=function(a,b,c){if(jc(b,c))return c.URL;return c[pa]},Md=function(a,b,c){if(Ld(a,b,c)!=c.URL)return c[ma];return""},Ld=function(a,b,c){var d=rd(V()).getAttribute("google_page_url");if(d)return d;return Kd(a,b,c)},Od=function(a,b,c,d){$(a,"url",
Jd(a,Ld(a,window,l),window.GA_googleEnv[y]("google_preview")));$(a,"ref",l[pa]);$(a,"lmt",(Date.parse(l.lastModified)/1E3)[z]());Z(a,"dt",b[sa]());if(l[va]){b=l[va].scrollHeight;var e=l[va].clientHeight;e&&b&&$(a,"cc",n[ha](e*100/b)[z]())}b=f;if(b=Eb(b)){$(a,"biw",b[q]);$(a,"bih",b[I])}b=Nd(window);$(a,"ifi",b);b=Gb(window);b!=0&&$(a,"ifk",b[z]());b=window.GA_googleEnv[y]("deb");b!=g&&$(a,"deb",b);b=window.GA_googleEnv[y]("haonly");b!=g&&$(a,"haonly",b);b=rd(V());i[E][u]("MSIE ")>0&&Uc(b,"google_encoding",
l.charset,h);e="";if(d)e=Xc(V().a,b,V().A,a.pa);else{c=ud(V(),c);if(c==g)c=b;else Vc(c,b);e=c.h()}if(e)a.b+="&"+e},Pd=function(a,b,c){var d=V().r,e=[];for(var m in d)U(d[m])||e[o](P(m)+"="+P(d[m]));$(a,"cust_params",e[J]("&"));if(b._GA_googleCookieHelper){$(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.N&&$(a,"cookie_enabled","1")}(b=Md(a,b,c))&&$(a,"cdm",b)},Qd=function(a){Mb();var b=window;Z(a,"ga_vid",b.gaGlobal.vid);Z(a,"ga_sid",b.gaGlobal.sid);Z(a,"ga_hid",b.gaGlobal.hid);Z(a,
"ga_fc",b.gaGlobal.from_cookie);$(a,"ga_wpids",b.google_analytics_uacct)},Rd=function(a,b){for(var c in b){var d=b[c];U(d)||Z(a,c,d)}};
Y[B].h=function(a){this.k();var b=Sd(this.f[z]());Z(this,"eid",b);b=new Date;Id(this,a);Pd(this,window,l);window.GA_googleEnv[y]("google_preview")!=g&&Z(this,"gct",window.GA_googleEnv[y]("google_preview"));Qd(this);Od(this,b,a,this.l);a={};Db(a);Rd(this,a);Z(this,"flash",Bb());this.b=this.b[H](0,2E3);this.b=this.b[t](/%\w?$/,"");a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";ic().registerAdBlockByType(a,this.b,f);return this.b};
var Ac=function(a){return a.u},Td=function(a,b){a=b.getAttribute("id");return a=a.substr(18,a[A]-18)},Ud=function(a,b,c,d,e,m,j){var r="google_ads_iframe_"+b,v=[];if(j){b="google_ads_div_"+b;v[o]("<div id=",b,">")}v[o]("<iframe id=",r," name=",r,' width="',e,'" height="',m,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',Pc(c),'"');d!=g&&v[o](' onload="',d,'"');v[o]("></iframe>");j&&
v[o]("</div>");a=v[J]("");l[w](a)},Vd=function(a,b,c){var d=Cc(a,c),e=d[wa],m=d[la];d=d[x];var j=l[oa]("iframe");j.id="google_ads_iframe_"+c;j.name="google_ads_iframe_"+c;da(j,e);fa(j,m);j.vspace=0;j.hspace=0;j.allowTransparency="true";j.scrolling="no";j.marginWidth=0;j.marginHeight=0;j.frameBorder=0;j.style.border=0;b=l.getElementById(b);b[ga](j);if(a.m){j[ra][C][w](Pc(d));j.scrolling="auto"}else j[ra][C][w](d);j[ra][C].close();kd(V(),c)};function Wd(a,b){Vd(W(),a,b)}
L("GA_googleCreateDomIframe",Wd);
var Xd=function(){var a=[],b=l[ta]("base");if(b)for(var c=0,d=b[A];c<d;++c){var e=b[c],m=e.getAttribute("target");if(m){a[o]({baseElement:e,originalTagValue:m});e.removeAttribute("target")}}return a},Yd=function(a){if(a)for(var b=0,c=a[A];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Zd=function(a){var b="http://"+tb+"/pagead/inject_object_div.js";if(k(Gd(),10)>6)return h;if(a[u](b)<0)return h;return f},$d=function(a,b,c){if(a.m)c=Pc(c);a=Xd();window.frames[b[qa]].contents=
c;b.src=Zd(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Yd(a)},ae=function(a,b,c){var d=Td(a,b);try{var e=b[ra]?b[ra][C]:b.contentDocument;if(e==g)if(l.implementation&&l.implementation.createDocument)e=l.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return h;e.open("text/html","replace");a.m?e[w](Pc(c)):e[w](c);e.close()}catch(m){return h}return f},be=function(a,
b){var c=Td(a,b),d=md(V(),c);if(!d.U){d.U=f;d=Cc(a,c);var e=b.parentNode;if(d==g||d[x]==g)e.removeChild(b);else if(d._expandable_)e.innerHTML=d[x];else d._is_3pas_?$d(a,b,d[x]):ae(a,b,d[x]);kd(V(),c)}},ce=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";a=Cc(a,b);if(a!=g){c+=a[x];c+="\n</div>\n";l[w](c);kd(V(),b)}},de=function(a,b){a="google_ads_div_"+b;b="<div id="+a+">";b+="\n</div>\n";l[w](b);return a},ee=function(a){if(!a.u)return f;if(dd(V(),a.u)>0)return f;else if(fd(V())==0)return h},
fe=function(a,b){oc(T,"ga_srt",V().c[A],"_ga_start");if(a.i==g){a.i=b;for(var c in b)U(b[c])||id(V(),c)}else for(c in b)if(!U(b[c])){a.i[c]=b[c];id(V(),c)}a=h;for(c in b)if(!U(b[c])){var d=b[c];if(a){d._cookies_=[Xb(window._GA_googleCookieHelper)];a=h}d!=g&&d._cookies_!=g&&Vb(window._GA_googleCookieHelper,d)}};function ge(a){fe(W(),a)}L("GA_googleSetAdContentsBySlot",ge);function he(a){Y[xa](this,a);this.u=h;this.f=(new Date)[sa]();this.g=a?"sync_sra":"sync"}Fa(he,Y);
he[B].k=function(){this.b=this.p;$(this,"correlator",this.f[z]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?Z(this,"impl","ss"):Z(this,"impl","s");ie(this,V().c);this.l||je(this,V().c,this.i)};
var ie=function(a,b){for(var c=0,d=f,e=0;e<b[A];++e){var m=a.i&&a.i[b[e]];if(m)if(m._is_afc_==ba){d=h;break}else c=2*c+(m._is_afc_?1:0)}d&&Z(a,"prev_afc",c)},je=function(a,b,c){if(b&&c){for(var d=[],e=[],m=b[A]-1,j=0;j<m;j++){var r=b[j];if((r=c[r])&&r._cids_&&r._a2ids_){d[o](r._cids_[0]);e[o](r._a2ids_[0])}else{d[o]("");e[o]("")}}if(d[A]>0){b=d[J](",");e=e[J](",");$(a,"a2ids",e);$(a,"cids",b)}}},ke=function(a,b){var c=V().a;c=c[b];if(c!=g)if(!a.t){a.h(c.s);hd(V(),b);l[w]("<script src = '"+a.b+"'><\/script>")}},
me=function(a,b){fe(a,b);if(a.l)if(V().c[A]==1){b=V().c[0];le(a,b);return}for(var c in b)U(b[c])||le(a,c)};function ne(a){me(W(),a)}L("GA_googleSetAdContentsBySlotForSync",ne);he[B].j=function(){ee(this)};var oe=function(a){a.h(g);l[w]("<script src = '"+a.b+"'><\/script>");gd(V())};he[B].n=function(a){V().c[o](a);oc(T,"_ga_start",V().c[A]);if(this.l)V().c[A]==1?oe(this):le(this,a);else ke(this,a)};
var pe=function(a,b,c){if(b.google_js_backfill){a="script";c[w]("<"+a+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+a+">")}},le=function(a,b){qe(a,window,l,b)},qe=function(a,b,c,d){var e=md(V(),d);if(e!=g){e=Cc(a,d);jd(V(),d);if(e==g||e._empty_){pe(a,b,c,d);kd(V(),d)}else if(a.I&&!a.m)kd(V(),d);else if(e._snippet_&&!e._is_afc_&&!a.m)ce(a,d);else if(b[za][E][u]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var m="about:blank";if(b=b.GA_googleEnv[y]("google_domain_reset_url")){var j=
lc(b.match(kc)[3]||g);if(j===g||j[u](l[ma])>=0)m=b}Ud(a,d,m,c,e[wa],e[la],f)}else{a=de(a,d);c[w]("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},re=function(a,b){var c=Td(a,b);md(V(),c);be(a,b)};function se(a){re(W(),a)}L("GA_googleSyncAdSlotLoaded",se);function te(a){Y[xa](this,a);this.f=(new Date)[sa]();this.g="async"}Fa(te,Y);
te[B].k=function(){this.b=this.p;ue(this);$(this,"correlator",this.f[z]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlot");Z(this,"impl","a")};var ue=function(a){a.delay=500;var b=window.GA_googleEnv[y]("google_async_delay");if(b!=g)a.delay=1E3*b};te[B].j=function(){if(ee(this))this.t||window.setTimeout("GA_googleReallyFetchAds();",20)};
var ve=function(a){if(dd(V(),a.u)!=0){var b=l[ta]("head")[0];if(a.l){var c=l[oa]("script");c.src=a.h(g);b[ga](c);gd(V())}else{var d=V().a;for(var e in d)if(!U(d[e])){c=l[oa]("script");c.src=a.h(e);b[ga](c);hd(V(),e)}}}};function we(){ve(W())}L("GA_googleReallyFetchAds",we);te[B].n=function(a){var b=md(V(),a);if(b!=g){V().c[o](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=Bc(V(),a);Ud(this,a,"about:blank",b,c[wa],c[la],f)}};var ye=function(a,b){var c=Td(a,b);md(V(),c);!a.t&&!a.I&&xe(a,b)};
function ze(a){ye(W(),a)}L("GA_googleAsyncAdSlotLoaded",ze);var xe=function(a,b){var c=Td(a,b),d=md(V(),c);if(a.i==g||a.i[c]==g){if(!(d.V>30)){window.setTimeout(function(){xe(W(),b)},a.delay);d.V++}}else be(a,b)};te[B].F=function(){};function Ae(a){Y[xa](this,a);this.f=(new Date)[sa]();this.g="fallback"}Fa(Ae,Y);Ae[B].k=function(){this.b=this.p;$(this,"correlator",this.f[z]());Z(this,"output","html");Z(this,"impl","fb")};Ae[B].j=function(){ee(this)};
Ae[B].w=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+P(a)}else a=this.h(a);return a};Ae[B].n=function(a){var b=Bc(V(),a);if(b!=g){V().c[o](a);if(!this.t){var c=this.w(a);Ud(this,a,c,g,b[wa],b[la],f)}}};function Be(a){Y[xa](this,a);this.f=(new Date)[sa]();this.K=f;this.g="iframe"}Fa(Be,Y);Be[B].k=function(){this.b=this.p;$(this,"correlator",this.f[z]());Z(this,"output","html");Z(this,"impl","ifr")};Be[B].j=function(){ee(this)};
Be[B].w=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+P(a)}else a=this.h(a);return a};Be[B].n=function(a){var b=Bc(V(),a);if(b!=g){V().c[o](a);if(!this.t){var c=this.w(a);Ud(this,a,c,g,b[wa],b[la],f)}}};
var Ce=function(){if(Ab()){var a=Gd();return a<=5}else if(yb("firefox")){var b=i[E][u]("Firefox")+8;a=k(i[E][ka](b),10);b=i[E][s](b);return a<1}else if(yb("safari")){b=i[E][u]("Safari")+7;b=i[E][s](b);a=k(b,10);return a<412}else if(window[na]!=g){b=i[E][u]("Opera")+6;b=i[E][s](b);a=k(b,10);return a<9}else if(!Ab()&&!yb("safari")&&yb("mozilla")){b=i[E][u]("Netscape")+9;b=i[E][s](b);a=k(b,10);return a<7}else return f},De=function(){if(Ab()){var a=Gd();return a>5}else if(yb("firefox")){a=i[E][u]("Firefox")+
8;var b=k(i[E][ka](a),10);i[E][s](a);return b>1}return h},Ee=function(){if(Ce())return"fallback";else if(window.google_delayFetch&&De())return"async";return"sync"},sc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv[y]("google_ad_impl");if(b==g)b=Ee()}switch(b){case "async":return new te(h);case "sync":return new he(h);case "sync_sra":return new he(f);case "fallback":return new Ae(h);case "iframe":return new Be(h);default:return new Ae(h)}},Fe;
function V(){Fe||(Fe=new Ic(Hb));return Fe}function Hc(a){delete Fe;Fe=a}var Ge;function W(){Ge||(Ge=g);return Ge}function rc(a){delete Ge;Ge=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new Nc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new Qc;if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new Rb(g);function Nd(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Sd(a){var b=ic(),c=He(window);if(c!=""){var d=b.getOsdMode();if(c=="36815006"){b.setValidAdBlockTypes(["html","json_html"]);d=1}b.setupOsd(d,c,a)}else c=b.getEid();return c}function He(a){if((a.google_unique_id||0)!=0)return"";return Cb(["36815005","36815006"],ib("0.006",0))}T.tick("js_parse","js_load");T.tick("jl");})()
