//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
var ver='3.0.1'
var m1=new Object
m1.name='m1'
m1.fnm='2008brule_nav_m1'
if(!window.lastm||window.lastm<1)lastm=1
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.v55=50
m1.scrollStep=10
m1.fadingSteps=8
m1.itemOverDelay=0
m1.transTLO=0
m1.fixSB=0
m1.v21="."
m1.maxlev=1
m1.v22=0
m1.sepH=10
m1.bHlNL=1
m1.showA=1
m1.bVarWidth=0
m1.bShowDel=0
m1.scrDel=0
m1.v23=150
m1.levelOffset=20
m1.bord=1
m1.vertSpace=5
m1.sep=1
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg=""
m1.tlmOrigCol="white"
m1.boh=1
m1.v25=false
m1.v52=false
m1.v60=75
m1.v11=false
m1.v10=0
m1.ppLeftPad=5
m1.v54=0
m1.v01=2
m1.tlmHlBg=""
m1.tlmHlCol="orange"
m1.borderCol="white"
m1.menuHorizontal=true
m1.scrollHeight=6
m1.attr=new Array("11px",false,false,"000166","orange","000166","verdana","orange","white","")
m1mn1=new Array
(
"Interactive ","digipromopak.html",0,"",""
,"PDF Download","http://www.brulerecords.com/promopak/2008BruleandAiroDigitalPromoPak.pdf",0,"",""
)
m1mn2=new Array
(
"Our Journey","journey.cfm",0,"",""
,"Digital Promotional Kit","digipromopak.html",0,"",""
)
m1mn3=new Array
(
"Paul","paul.cfm",0,"",""
,"Kathy","kathy.cfm",0,"",""
,"Nicole","nicole.cfm",0,"",""
,"Shane","shane.cfm",0,"",""
,"Moses","moses.cfm",0,"",""
)
m1mn4=new Array
(
"CDs","cd.cfm",0,"",""
,"DVDs","dvd.cfm",0,"",""
,"Hidden Heritage","bookorder.html",0,"",""
,"Mail Orders Only","http://www.brulerecords.com/brule_orderform.pdf",0,"_blank",""
)
m1mn5=new Array
(
"Photo Gallery","brule_gallery.html",0,"",""
,"Video Gallery","brule_videoclips.html",0,"",""
,"Sound Clips","brule_soundclips.html",0,"",""
)
m1mn6=new Array
(
"Fan Club Registration","brule_register.cfm",0,"",""
,"Chat Room","brule_chatroom.html",0,"",""
,"Message Board","http://members5.boardhost.com/BruleRecords/",0,"",""
,"Links","links.html",0,"",""
)
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.v61=0
m1.v02=m1.v23
document.write("<style type='text/css'>\n.m1CL0,.m1CL0:link{text-decoration:none;width:100%;color:white; }\n.m1CL0:visited{color:white}\n.m1mit{padding-left:15px;padding-right:15px;color:white; font-family:verdana; font-size:11px; }\n"+"</"+"style>")
document.write("<script language='JavaScript1.2' src='./menu_dom.js'></"+"script>")
