stm_bm(["menu7046",900,"/clients/CCCOnline/Images","blank.gif",0,"","",0,0,250,0,1000,1,0,0,"","",67108897,0,1,2,"default","hand","file:///S|/Clients/Capital%20Christian/web",1,25],this);
stm_bp("p0",[0,4,0,0,0,0,0,0,100,"",-2,"",-2,50,0,0,"#999999","","",3,0,0,"#000000"]);
stm_ai("p0i0",[2,"","btn_getinvolved.jpg","btn_getinvolved_over.jpg",152,40,0,"/ministries.php","_self","","","","",0,0,0,"","",0,0,0,0,1,"#E6EFF9",0,"#FFD602",0,"","",3,3,0,0,"#E6EFF9","#000000","#000000","#000000","8pt Verdana","8pt Verdana",0,0,"","","","",0,0,0]);
stm_bpx("p1","p0",[1,4,0,0,0,10]);
stm_aix("p1i0","p0i0",[0,"Adults","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*adults*","_self","","Adult Ministries and Programs","","",0,0,0,"","",0,0,0,0,1,"#133e44",0,"#23717b",0,"","",3,3,1,1,"#999999","#eeeeee","#FFFFFF","#ccff99","bold 8pt Verdana","bold 8pt Verdana"],223,0);
stm_aix("p1i1","p1i0",[0,"Men","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*mens*","_self","","Activities and Programs for Men"],223,28);
stm_aix("p1i2","p1i0",[0,"Women","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*women*","_self","","Activities and Programs for Women"],223,28);
stm_aix("p1i3","p1i0",[0,"Married Life","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*married*","_self","","Activities and Programs for Married Couples"],223,28);
stm_aix("p1i4","p1i0",[0,"College / Career","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*career*","_self","","Activities and Programs for Young Adults"],223,0);
stm_aix("p1i5","p1i0",[0,"High School","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*high_school*","_self","","Activities and Programs for High School Students"],223,28);
stm_aix("p1i6","p1i0",[0,"Middle School","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*middle_school*","_self","","Activities and Programs for Middle School Students"],223,28);
stm_aix("p1i7","p1i0",[0,"Kids","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*kids*","_self","","Activities and Programs for Kids"],223,28);
stm_aix("p1i8","p1i0",[0,"Small Groups","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*small_groups*","_self","","Church Small Groups and Activities"],223,28);
stm_aix("p1i9","p1i0",[0,"Sports","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*sports*","_self","","Activities and Programs for Sports"],223,28);
stm_bpx("p2","p1",[1,2]);
stm_aix("p2i0","p1i0",[0,"Sports Leagues & Outings","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*sport_leagues*","_self","","Sports Leagues Clubs and Events"],250,28);
stm_aix("p2i1","p1i0",[0,"Adventure Quest","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*adventure_quest*","_self","","Adventure Activities"],250,28);
stm_aix("p2i2","p1i0",[0,"Core, Nutrition and Fitness","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*core_nutrition*","_self","","Programs for Health, Nutrition and Fitness"],250,28);
stm_aix("p2i3","p1i0",[0,"Be Change Competition Racers","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*bechange*","_self","","Be Change Competions and Events"],250,0);
stm_ep();
stm_aix("p1i10","p1i0",[0,"Outreach","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*outreach*","_self","","Outreach Programs and Activities"],223,0);
stm_aix("p1i11","p1i0",[0,"Missions","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*missions*","_self","","Missions Trips and International Programs"],223,28);
stm_aix("p1i12","p1i0",[0,"Music & Creative Arts","","",-1,-1,0,"http://www.ccconline.cc/ministries.php?category=*creative_arts*","_self","","Music and Creative Arts Programs and Activities"],223,28);
stm_aix("p1i13","p1i0",[0,"Volunteer Opportunities","","",-1,-1,0,"http://www.ccconline.cc/volunteer_opportunities.php","_self","","Volunteer Opportunities"],223,28);
stm_ep();
stm_aix("p0i1","p0i0",[2,"","btn_calendar.jpg","btn_calendar_over.jpg",120,40,0,"http://www.ccconline.cc/calendar.php"]);
stm_bpx("p3","p1",[]);
stm_aix("p3i0","p1i0",[0,"Featured Events","","",-1,-1,0,"http://www.ccconline.cc/calendar.php?f1=yes","_self","","Featured Events and Calendar Dates For Capital Christian"],223,0);
stm_aix("p3i1","p1i0",[0,"All Upcoming Events","","",-1,-1,0,"http://www.ccconline.cc/calendar.php","_self","","Capital Christian Center Calendar"],223,28);
stm_ep();
stm_aix("p0i2","p0i0",[2,"","btn_messages.jpg","btn_messages_over.jpg",122,40,0,""]);
stm_bpx("p4","p1",[]);
stm_aix("p4i0","p1i0",[0,"Audio Messages","","",-1,-1,0,"http://www.ccconline.cc/messages.php","_self","","Online Sermon Messages In Audio"],223,0);
stm_aix("p4i1","p1i0",[0,"Video Messages","","",-1,-1,0,"http://www.ccconline.cc/videos.php","_self","","Online Video Sermons"],223,28);
stm_aix("p4i2","p1i0",[0,"iTunes Podcast","","",-1,-1,0,"http://www.ccconline.cc/podcast.php","_self","","Capital Christian Center Podcast"],223,28);
stm_ep();
stm_aix("p0i3","p0i0",[2,"","btn_resources.jpg","btn_resources_over.jpg",130,40,0,"http://www.ccconline.cc/resources.php"]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p1i0",[0,"Mentioned On Sunday","","",-1,-1,0,"http://www.ccconline.cc/resources.php?category=Mentioned%20on%20Sunday","_self","","Mentioned On Sunday Downloads"],223,0);
stm_aix("p5i1","p1i0",[0,"Celebrate Recovery","","",-1,-1,0,"http://www.ccconline.cc/ministries/celebrate_recovery","_self","","Celebrate Recovery Resources"],223,28);
stm_aix("p5i2","p1i0",[0,"Website Links","","",-1,-1,0,"http://www.ccconline.cc/resources.php?category=Website%20Links","_self","","Website Links and Helpful Resources"],223,28);
stm_aix("p5i3","p1i0",[0,"Counseling Center","","",-1,-1,0,"http://www.capitalcounselingcenter.com","_self","","Capital Counseling Center"],223,0);
stm_ep();
stm_aix("p0i4","p0i2",[2,"","btn_schools.jpg","btn_schools_over.jpg",108]);
stm_bpx("p6","p1",[]);
stm_aix("p6i0","p1i0",[0,"Capital Bible College","","",-1,-1,0,"http://www.capchrist.edu","_blank","","Capital Christian Bible School"],265,0);
stm_aix("p6i1","p1i0",[0,"Capital Christian School (PK-12)","","",-1,-1,0,"http://ccs.ccconline.cc","_blank","","Capital Christian Preschool Through 12 School"],265,28);
stm_aix("p6i2","p1i0",[0,"Masters Commission","","",-1,-1,0,"http://www.mcsacramento.com","_blank","","Masters Commission Sacramento"],265,28);
stm_ep();
stm_aix("p0i5","p0i2",[2,"","btn_about.jpg","btn_about_over.jpg",92]);
stm_bpx("p7","p1",[]);
stm_aix("p7i0","p1i0",[0,"New to Capital","","",-1,-1,0,"http://www.ccconline.cc/new.php","_self","","New To Capital Christian Center"],223,0);
stm_aix("p7i1","p1i0",[0,"Our 5 Purposes","","",-1,-1,0,"http://www.ccconline.cc/purposes.php","_self","","Our 5 Purposes At Capital Christian Center"],223,28);
stm_aix("p7i2","p1i0",[0,"What We Believe","","",-1,-1,0,"http://www.ccconline.cc/believe.php","_self","","Our Statement of Faith and What We Believe"],223,28);
stm_aix("p7i3","p1i0",[0,"Photogallery","","",-1,-1,0,"http://www.ccconline.cc/gallery.php","_self","","Photo Gallery"],223,28);
stm_aix("p7i4","p1i0",[0,"Our Team","","",-1,-1,0,"http://www.ccconline.cc/team.php","_self","","Our Team"],223,0);
stm_aix("p7i5","p1i0",[0,"Contact Information","","",-1,-1,0,"http://www.ccconline.cc/contact.php","_self","","Contact Capital Christian Center"],223,28);
stm_ep();
stm_aix("p0i6","p0i2",[2,"","btn_connected.jpg","btn_connected_over.jpg",176]);
stm_bpx("p8","p1",[]);
stm_aix("p8i0","p1i0",[0,"Pastor\'s Blog","","",-1,-1,0,"http://cccpastorrick.blogspot.com","_blank","","Pastor Rick\'s Blog"],223,0);
stm_aix("p8i1","p1i0",[0,"Email Newsletter","","",-1,-1,0,"http://www.ccconline.cc/newsletter.php","_self","","Capital Christian Email Newsletter"],223,28);
stm_aix("p8i2","p1i0",[0,"C5 Magazine","","",-1,-1,0,"http://www.ccconline.cc/c5mag/index.htm","_self","","C5 Magazine at Capital Christian"],223,28);
stm_aix("p8i3","p1i13",[],223,28);
stm_ep();
stm_ep();
stm_em();
