document.writeln('<SCRIPT>');
document.writeln('				function fixHref(elem, page, href) {');
document.writeln('					if (page) {');
document.writeln('						if (window.__is_internal__ || window.top._edit) {');
document.writeln('							elem.href = "javascript:changePage(\'" + page + "\');";');
document.writeln('						} else if (typeof(theSitetree) != "undefined") {');
document.writeln('							elem.href = __path_prefix__ + theSitetree.getHREF(page);');
document.writeln('						}');
document.writeln('					} else {');
document.writeln('						if (window.__is_internal__ || window.top._edit) {');
document.writeln('							elem.href = "javascript:;";');
document.writeln('							elem.title = href;');
document.writeln('						}');
document.writeln('					}');
document.writeln('					elem.onmouseover = null;');
document.writeln('				}');
document.writeln('				function footerSMT() {');
document.writeln('					if (typeof(footer_setModifiedTimestamp) == "function") {');
document.writeln('						footer_setModifiedTimestamp();');
document.writeln('					}');
document.writeln('				}');
document.writeln('			</SCRIPT><center><div class="footerBox" id="footer_box"><p class="footer_timestamp_normal"><span value="20091007-130026" format="f1" id="footer_lastModified">20091007-130026</span></p></div></center><SCRIPT>footerSMT();</SCRIPT>');