document.writeln('<center>');
document.writeln('<div class="footerBox" id="footer_box">');
document.writeln('<p class="p_footer">Dance Central performing arts - 46 E Central Avenue - Pearl River, NY  - (845) 627-0595</p>');
document.writeln('<script>');
document.writeln('						if (typeof(footer_setModifiedTimestamp) == "function") {');
document.writeln('							footer_setModifiedTimestamp();');
document.writeln('						}');
document.writeln('					</script>');
document.writeln('</div>');
document.writeln('</center>');
