//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
var ver='3.0.2'
var m1=new Object
m1.name='m1'
m1.fnm='menu_ps_m1'
if(!window.lastm||window.lastm<1)lastm=1
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.v55=50
m1.scrollStep=10
m1.fadingSteps=8
m1.itemOverDelay=0
m1.transTLO=0
m1.fixSB=0
m1.v21="."
m1.maxlev=0
m1.v22=0
m1.sepH=10
m1.bHlNL=1
m1.showA=1
m1.bVarWidth=0
m1.bShowDel=0
m1.scrDel=0
m1.v23=150
m1.levelOffset=20
m1.bord=0
m1.vertSpace=5
m1.sep=1
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=-1
m1.shc='#000000'
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg="#134F9A"
m1.tlmOrigCol="White"
m1.v25=false
m1.v52=false
m1.v60=0
m1.v11=false
m1.v10=0
m1.ppLeftPad=5
m1.v54=0
m1.v01=2
m1.tlmHlBg="#134F9A"
m1.tlmHlCol="Yellow"
m1.borderCol="#FFFFFF"
m1.menuHorizontal=false
m1.scrollHeight=6
m1.attr=new Array("14px",false,false,"White","#134F9A","#ffff00","Arial,Helvetica","#843F04","White","#134F9A")
window.m1templFold="<tr align=\"right\"><td onmouseover=\"chgBg(m1,'m1tlm(menuind)',3);exM(m1,'m1mn(foldind)','m1tlm(menuind)',event)\" onmouseout=\"chgBg(m1,'m1tlm(menuind)',0);coM(m1,'m1mn(foldind)')\" id=\"m1tlm(menuind)\" style=\"color:(textcol);\" class=\"m1mit\" bgcolor=\"(bgcol)\"><a id=\"m1tlm(menuind)a\" (status)style=\"color:(textcol);\" class=\"m1CL0\" href=\"(menuurl)\" target=\"(trgframe)\" >(menutxt)</a></td>\n</tr>"
window.m1templFile="<tr align=\"right\"><td onmouseover=\"chgBg(m1,'m1tlm(menuind)',3);exM(m1,'none','',event)\" onmouseout=\"chgBg(m1,'m1tlm(menuind)',0,1)\" id=\"m1tlm(menuind)\" style=\"color:(textcol);\" class=\"m1mit\" bgcolor=\"(bgcol)\"><a id=\"m1tlm(menuind)a\" (status)style=\"color:(textcol);\" class=\"m1CL0\" href=\"(menuurl)\" target=\"(trgframe)\">(menutxt)</a></td>\n</tr>"
window.m1templSep=""
window.m1tbl1="<table  id=\"m1mainSXMenu2\" cellspacing=\"1\" cellpadding=\"5\" border=\"0\" width=\"150\">\n"
window.m1tbl2="\n</table>"
m1mn=new Array()
function gpc(ar){
var i
var cnt=0
for(i=0;i<ar.length/5;i++){
if(ar [i*5+2]==1){
cnt++}}
return cnt}
function insertItemToMenu(itemText,itemUrl,parentMenu,bPopup,targetFrame,itemIcon,nMenu){
var parentMenuId=parentMenu ? parentMenu :((nMenu ? nMenu : 'm1')+'mn')
var arr=eval('window.'+parentMenuId)
if(!arr){
eval('window.'+parentMenuId+'= new Array ();')
arr=eval('window.'+parentMenuId)}
var item=parentMenu ?(arr.length/5+1):(gpc(arr)+1)
if(arr.push)arr.push(itemText,itemUrl,bPopup ? 1 : 0,targetFrame,itemIcon)
else{
arr [arr.length]=itemText
arr [arr.length]=itemUrl
arr [arr.length]=bPopup?1:0
arr [arr.length]=targetFrame
arr [arr.length]=itemIcon}
var newId=(parentMenuId+(parentMenu ? '_' : '')+item.toString())
if(bPopup){
eval("document."+newId+"prop = \'"+itemIcon+"\';")}
return newId}
function addSubMenu(itemText,itemUrl,targetFrame,parentMenu,itemIcon,nMenu){
return insertItemToMenu(itemText,itemUrl,parentMenu,1,targetFrame,itemIcon,nMenu)}
function addMenuItem(itemText,itemUrl,targetFrame,parentMenu,itemIcon,nMenu){
return insertItemToMenu(itemText,itemUrl,parentMenu,0,targetFrame,itemIcon,nMenu)}
function addTopLevelMenu(itemText,itemUrl,targetFrame,itemIcon,nMenu){
var url
if(!itemUrl || itemUrl==''){
url='javascript:void(0);'}
else{
url=itemUrl}
return addSubMenu(itemText,url,null,targetFrame,itemIcon,nMenu)}
function getTopLevelMenu(nSubMenu,nMenu){
return((nMenu ? nMenu : 'm1')+'mn'+nSubMenu)}
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.v61=0
m1.v02=m1.v23
document.write("<style type='text/css'>\n.m1CL0,.m1CL0:link{text-decoration:none;width:100%;color:White; }\n.m1CL0:visited{color:White}\n.m1mit{padding-left:25px;padding-right:5px;color:White; font-family:Arial,Helvetica; font-size:14px; }\n"+"</"+"style>")
document.write("<script language='JavaScript1.2' src='./menu_dom.js'></"+"script>")
