(function() {
var _UDS_CONST_LOCALE = 'en';
var _UDS_CONST_SHORT_DATE_PATTERN = 'MDY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Image'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('Video'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Local'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('save'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('keep'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('include'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copy'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('close'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Sponsored Links'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('see more...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('clipped from Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Search location'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Disable address lookup'); 
var _UDS_MSG_SEARCHER_NEWS = ('News'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minutes ago');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 hour ago'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' hours ago');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('all ' + NUMBER + ' related');} 
var _UDS_MSG_NEWS_RELATED = ('Related Articles'); 
var _UDS_MSG_BRANDING_STRING = ('powered by Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Sort by date'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Jan'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Feb'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Mar'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Apr'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('May'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Jun'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Jul'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Aug'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Sep'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Oct'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Nov'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Dec'); 
var _UDS_MSG_DIRECTIONS = ('directions'); 
var _UDS_MSG_CLEAR_RESULTS = ('clear results'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('show one result'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('show more results'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('show all results'); 
var _UDS_MSG_SETTINGS = ('settings'); 
var _UDS_MSG_SEARCH = ('search'); 
var _UDS_MSG_SEARCH_UC = ('Search'); 
var _UDS_MSG_POWERED_BY = ('powered by'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Business listings provided by ' + LOCAL_RESULTS_PROVIDER + '');} 
var _UDS_MSG_SEARCHER_BOOK = ('Book'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('Page ' + FOUND_ON_PAGE + '');} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' pages');} 
var _UDS_MSG_SEARCHER_BY = ('by'); 
var _UDS_MSG_SEARCHER_CODE = ('Code'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Unknown License'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('More results'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Previous'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Next'); 
var _UDS_MSG_GET_DIRECTIONS = ('Get directions'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('To here'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('From here'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Clear results'); 
var _UDS_MSG_SEARCH_THE_MAP = ('search the map'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('scroll through results'); 
var _UDS_MSG_EDIT_TAGS = ('edit tags'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('tag this search'); 
var _UDS_MSG_SEARCH_STRING = ('search string'); 
var _UDS_MSG_OPTIONAL_LABEL = ('optional label'); 
var _UDS_MSG_DELETE = ('delete'); 
var _UDS_MSG_DELETED = ('deleted'); 
var _UDS_MSG_CANCEL = ('cancel'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('upload your own video'); 
var _UDS_MSG_IM_DONE_WATCHING = ('i\047m done watching this'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('close video player'); 
var _UDS_MSG_NO_RESULTS = ('No Results'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('This Custom Search Engine is loading. Try again in a few seconds.'); 
var _UDS_MSG_COUPONS = ('Coupons'); 
var _UDS_MSG_BACK = ('back'); 
var _UDS_MSG_SUBSCRIBE = ('Subscribe'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patent'); 
var _UDS_MSG_USPAT = ('US Pat.'); 
var _UDS_MSG_USPAT_APP = ('US Pat. App'); 
var _UDS_MSG_PATENT_FILED = ('Filed'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Ads by Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('Set default location'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Top Stories'); 
var _UDS_MSG_NEWSCAT_WORLD = ('World'); 
var _UDS_MSG_NEWSCAT_NATION = ('Nation'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Business'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Sci/Tech'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Entertainment'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('Health'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Sports'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Politics');
var b=true,c=null,g=false,h=encodeURIComponent,j=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,k=window,m=google,ba=navigator,o=undefined,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,p=document,fa=decodeURIComponent,q=Math;function ga(a,d){return a.onload=d}function ha(a,d){return a.onreadystatechange=d}function r(a,d){return a.title=d}function s(a,d){return a.className=d}function ia(a,d){return a.input=d}function ja(a,d){return a.width=d}function ka(a,d){return a.checked=d}
function t(a,d){return a.innerHTML=d}function la(a,d){return a.value=d}function ma(a,d){return a.type=d}function na(a,d){return a.onclick=d}function oa(a,d){return a.display=d}function pa(a,d){return a.execute=d}function u(a,d){return a.height=d}function qa(a,d){return a.visibility=d}
var v="appendChild",ra="push",w="length",sa="title",x="prototype",y="cursor",ta="className",ua="clearTimeout",A="input",C="width",va="Version",wa="round",ya="checked",za="setTimeout",D="replace",Aa="split",Ba="floor",Ca="content",Da="userAgent",Ea="value",Fa="location",Ga="indexOf",Ha="getComputedStyle",E="style",Ia="close",F="search",G="call",Ja="match",Ka="readyState",La="focus",H="createElement",I="setAttribute",J="loader",Ma="currentStyle",Na="cloneNode",Oa="type",Pa="apply",Qa="recordStat",Ra=
"ServiceBase",K="CurrentLocale",L="execute",Sa="height",Ta="getTime",Ua="toLowerCase",M;if(!m[F].NoOldNames){j("UDS_ServiceBase",m[J][Ra]);j("UDS_OriginalAppPath",m[J].OriginalAppPath);j("UDS_ApiKey",m[J].ApiKey);j("UDS_KeyVerified",m[J].KeyVerified);j("UDS_LoadFailure",m[J].LoadFailure);j("UDS_CurrentLocale",ea);j("UDS_ShortDatePattern",aa);j("UDS_Version",m[F][va]);j("UDS_JSHash",m[F].JSHash)}if(!N)var N=j;if(!O)var O=google_exportProperty;var P={};P.blank="&nbsp;";P.image=_UDS_MSG_SEARCHER_IMAGE;P.web=_UDS_MSG_SEARCHER_WEB;P.blog=_UDS_MSG_SEARCHER_BLOG;P.video=_UDS_MSG_SEARCHER_VIDEO;P.local=_UDS_MSG_SEARCHER_LOCAL;P.news=_UDS_MSG_SEARCHER_NEWS;P.book=_UDS_MSG_SEARCHER_BOOK;P.patent="Patent";P["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;P.cse="Custom Search Control";P.save=_UDS_MSG_SEARCHCONTROL_SAVE;P.keep=_UDS_MSG_SEARCHCONTROL_KEEP;P.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;P.copy=_UDS_MSG_SEARCHCONTROL_COPY;P.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
P["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;P["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;P.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;P["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;P["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;P["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;P.pbg=_UDS_MSG_BRANDING_STRING;P["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;P["n-hours-ago"]=_UDS_MSG_HOURS_AGO;P["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;P["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
P["related-articles"]=_UDS_MSG_NEWS_RELATED;P["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var Q=[];Q[0]=_UDS_MSG_MONTH_ABBR_JAN;Q[1]=_UDS_MSG_MONTH_ABBR_FEB;Q[2]=_UDS_MSG_MONTH_ABBR_MAR;Q[3]=_UDS_MSG_MONTH_ABBR_APR;Q[4]=_UDS_MSG_MONTH_ABBR_MAY;Q[5]=_UDS_MSG_MONTH_ABBR_JUN;Q[6]=_UDS_MSG_MONTH_ABBR_JUL;Q[7]=_UDS_MSG_MONTH_ABBR_AUG;Q[8]=_UDS_MSG_MONTH_ABBR_SEP;Q[9]=_UDS_MSG_MONTH_ABBR_OCT;Q[10]=_UDS_MSG_MONTH_ABBR_NOV;Q[11]=_UDS_MSG_MONTH_ABBR_DEC;P["month-abbr"]=Q;P.directions=_UDS_MSG_DIRECTIONS;
P["clear-results"]=_UDS_MSG_CLEAR_RESULTS;P["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;P["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;P["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;P.settings=_UDS_MSG_SETTINGS;P.search=_UDS_MSG_SEARCH;P["search-uc"]=_UDS_MSG_SEARCH_UC;P["powered-by"]=_UDS_MSG_POWERED_BY;P.sa=_UDS_MSG_SEARCHER_GSA;P.by=_UDS_MSG_SEARCHER_BY;P.code=_UDS_MSG_SEARCHER_CODE;P["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;P["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
P.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;P.next=_UDS_MSG_SEARCHCONTROL_NEXT;P["get-directions"]=_UDS_MSG_GET_DIRECTIONS;P["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;P["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;P["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;P["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;P["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;P["edit-tags"]=_UDS_MSG_EDIT_TAGS;P["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;P["search-string"]=_UDS_MSG_SEARCH_STRING;P["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
P["delete"]=_UDS_MSG_DELETE;P.deleted=_UDS_MSG_DELETED;P.cancel=_UDS_MSG_CANCEL;P["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;P["im-done"]=_UDS_MSG_IM_DONE_WATCHING;P["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;P["no-results"]=_UDS_MSG_NO_RESULTS;P["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;P.back=_UDS_MSG_BACK;P.subscribe=_UDS_MSG_SUBSCRIBE;P["us-pat"]="US Pat.";P["us-pat-app"]="US Pat. App";P["us-pat-filed"]="Filed";function Va(a,d){var e=function(){};e.prototype=d[x];a.prototype=new e;a[x].mg=function(f){var i=Array[x].splice[Pa](arguments,[1,arguments[w]]);return f[Pa](a,i)}}var _json_cache_defeater_=(new Date)[Ta](),_json_request_require_prep=b;function Wa(a,d){if(Xa("msie")&&Ya("msie 6.0")){a=R(this,Za,[a,d]);k[za](a,0)}else Za(a,d)}function $a(a){_json_request_require_prep=g;Wa(a,c);_json_request_require_prep=b}
function Za(a,d){var e=p.getElementsByTagName("head")[0];e||(e=p.body.parentNode[v](p[H]("head")));var f=p[H]("script");ma(f,"text/javascript");f.charset="utf-8";a=_json_request_require_prep?a+"&key="+m[J].ApiKey+"&v="+d:a;if(ab()||bb())a=a+"&nocache="+_json_cache_defeater_++;f.src=a;var i=function(){ga(f,c);f.parentNode.removeChild(f);delete f};a=function(l){l=l?l:k.event;l=l.target?l.target:l.srcElement;if(l[Ka]=="loaded"||l[Ka]=="complete"){ha(l,c);i()}};if(ba.product=="Gecko")ga(f,i);else ha(f,
a);e[v](f)}function cb(a,d){return function(){return d[Pa](a,arguments)}}function R(a,d,e){return function(){return d[Pa](a,e)}}function db(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function T(a,d){try{a[v](d)}catch(e){}return d}function V(a,d){var e=p[H]("div");if(a)t(e,a);if(d)s(e,d);return e}function W(a){var d=p[H]("div");if(a)s(d,a);return d}function eb(a,d){var e=p[H]("span");a&&T(e,p.createTextNode(a?a:""));if(d)s(e,d);return e}
function fb(a,d,e){var f=p[H]("table");f[I]("cellSpacing",a?a:0);f[I]("cellPadding",d?d:0);if(e)s(f,e);return f}function gb(a,d,e){(a=a.insertRow(-1))||alert(a);for(var f=0;f<d;f++)X(a,e);return a}function X(a,d){a=a.insertCell(-1);if(d)s(a,d);return a}function hb(a){var d=p[H]("td");if(a)s(d,a);return d}function ib(a,d,e,f){var i=p[H]("img");i.src=a;if(d)ja(i,d);if(e)u(i,e);if(f)s(i,f);return i}
function jb(a,d,e,f,i){var l=p[H]("a");l.href=a;if(d)f?T(l,eb(d,f)):T(l,p.createTextNode(d?d:""));if(e)l.target=e;if(i)r(l,i);return l}function Y(a,d,e,f,i){var l=V(c,f),n=p[H]("a");n.href=a;t(n,d);if(f)s(n,f);if(e)n.target=e;if(i)r(n,i);l[v](n);return l}function kb(a){var d=p[H]("form");if(a)s(d,a);return d}function lb(a,d){var e=p[H]("input");ma(e,"submit");la(e,a);if(d)s(e,d);return e}
function mb(a,d,e){var f=p[H]("input");f[I]("autoComplete","off");ma(f,"text");if(a==-1)Z(f,"util-css-expand");else f.size=a>0?a:10;d&&nb(f,d);if(e)la(f,e);return f}function ob(a,d,e,f){var i=p[H]("input");ma(i,"checkbox");i.name=a;la(i,d);if(f)s(i,f);if(e)ka(i,e);return i}function pb(a,d){s(a,d)}function nb(a,d){Z(a,d)}function qb(a,d){$(a,d)}function Z(a,d){var e;a:if(a==c||a[ta]==c)e=g;else{e=a[ta][Aa](" ");for(var f=0;f<e[w];f++)if(e[f]==d){e=b;break a}e=g}e||(a.className+=" "+d)}
function $(a,d){if(!(a[ta]==c)){for(var e=a[ta][Aa](" "),f=[],i=g,l=0;l<e[w];l++)if(e[l]!=d)e[l]&&f[ra](e[l]);else i=b;if(i)s(a,f.join(" "))}}function rb(a){if(sb!="")return sb;var d=a[Ua]()[Aa](".");if(d[w]<2)sb=".com";a=d.pop();d=d.pop();return sb=a[w]==2?tb[d]&&tb[d][a]==1?"."+d+"."+a:"."+a:".com"}
var sb="",tb={$e:{wg:1,Ag:1,Ig:1,id:1,Jg:1,"in":1,Lg:1,Ng:1,Og:1,Pg:1,Sg:1,ah:1,ph:1,th:1,uh:1,yh:1,zh:1,Ch:1},xg:{ng:1,qg:1,sg:1,tg:1,ug:1,vg:1,$e:1,Bg:1,"do":1,Cg:1,Dg:1,Eg:1,Fg:1,Gg:1,Hg:1,Mg:1,Tg:1,Ug:1,Vg:1,Wg:1,Xg:1,Yg:1,Zg:1,$g:1,dh:1,eh:1,fh:1,gh:1,hh:1,ih:1,kh:1,mh:1,oh:1,qh:1,rh:1,sh:1,wh:1,xh:1,Bh:1},bh:{og:1}};function Xa(a){if(a in ub)return ub[a];return ub[a]=ba[Da][Ua]()[Ga](a)!=-1}function Ya(a){if(a in vb)return vb[a];return vb[a]=ba.appVersion[Ua]()[Ga](a)!=-1}var ub={},vb={};
function ab(){return Xa("msie")}function bb(){return Xa("safari")||Xa("konqueror")}var wb,xb,yb,zb,Ab,Bb,Cb;if(k.lg){wb=b;if(k.XMLHttpRequest)xb=b;else yb=b}else if(k.opera)zb=b;else if(p.childNodes&&!p.all&&!ba.taintEnabled){Ab=b;if(ba[Da][Ga]("iPhone")>0)Bb=b}else if(p.getBoxObjectFor!=c)Cb=b;
function Db(a){this.bc=a+"branding";this.Qb=a+"branding-vertical";this.Kg=a+"branding-img";this.vh=a+"branding-user-defined";this.ge=a+"branding-img-noclear";this.Ze=a+"branding-clickable";this.text=a+"branding-text"};m[F].a=function(){this.da=this.yg=c;this.Dc=this.ig=0;this.ce=b;this.M={width:100,height:75};this.Fa=m[F].a.ab;this.ke=1;this.pa(m[F].a.ba);this.Td();this.gwsUrl=this.v=this.G=this.lh=this.z=this.Ib=this.yb=this.Za=this.sc=this.Nb=this.hc=this.fc=c;this.oa=[];this.ee=typeof k==="object"&&k[Fa]&&k[Fa].hostname&&k[Fa].hostname!=""?rb(k[Fa].hostname):".com";this.nb=this.gb=c};N("google.search.Search",m[F].a);m[F].a.Hc=m[J][Ra];O(m[F].a,"BASE",m[F].a.Hc);m[F].a.ta="large";O(m[F].a,"LARGE_RESULTSET",m[F].a.ta);
m[F].a.ba="small";O(m[F].a,"SMALL_RESULTSET",m[F].a.ba);m[F].a.Ge=8;O(m[F].a,"LARGE_RESULTS",m[F].a.Ge);m[F].a.Pe=4;O(m[F].a,"SMALL_RESULTS",m[F].a.Pe);m[F].a.md=5000;O(m[F].a,"KEEP_SWEEPER_DELAY",m[F].a.md);m[F].a.Je="_top";O(m[F].a,"LINK_TARGET_TOP",m[F].a.Je);m[F].a.Ie="_self";O(m[F].a,"LINK_TARGET_SELF",m[F].a.Ie);m[F].a.He="_parent";O(m[F].a,"LINK_TARGET_PARENT",m[F].a.He);m[F].a.ab="_blank";O(m[F].a,"LINK_TARGET_BLANK",m[F].a.ab);m[F].a.la="order-by-relevance";
O(m[F].a,"ORDER_BY_RELEVANCE",m[F].a.la);m[F].a.ka="order-by-date";O(m[F].a,"ORDER_BY_DATE",m[F].a.ka);m[F].a.pd="order-by-ascending-date";O(m[F].a,"ORDER_BY_ASCENDING_DATE",m[F].a.pd);m[F].a.zb="restrict-type";O(m[F].a,"RESTRICT_TYPE",m[F].a.zb);m[F].a.Tb="restrict-safesearch";O(m[F].a,"RESTRICT_SAFESEARCH",m[F].a.Tb);m[F].a.Wb="active";O(m[F].a,"SAFESEARCH_STRICT",m[F].a.Wb);m[F].a.Vb="off";O(m[F].a,"SAFESEARCH_OFF",m[F].a.Vb);m[F].a.Ub="moderate";O(m[F].a,"SAFESEARCH_MODERATE",m[F].a.Ub);
m[F].a.Sb="restrict-extended";O(m[F].a,"RESTRICT_EXTENDED_ARGS",m[F].a.Sb);m[F].a.cg=P;O(m[F].a,"strings",m[F].a.cg);m[F].a[x].If=function(){var a=this.ma+"?hl="+m[F][K]+"&source=uds";a=this.v?a+this.v:a+"&q=";return this.xa&&this.xa!=""?this.xa:a};m[F].a[x].Vf=function(a){this.G=a==c||a==""?c:a};O(m[F].a[x],"setQueryAddition",m[F].a[x].Vf);
m[F].a[x].za=function(a,d,e){a=m[F].a.Hc+this.Ba+"?callback="+a+"&context="+d+"&lstkp="+this.Ye()+"&rsz="+this.Wa+"&hl="+m[F][K];if(this.sb)a+="&source="+h(this.sb);if(this.ee)a+="&gss="+this.ee;if(m[F].JSHash)a+="&sig="+m[F].JSHash;if(e)a+="&start="+e;return a};m[F].a[x].Zf=function(a){this.sb=a};O(m[F].a[x],"setSearcherSrc",m[F].a[x].Zf);m[F].a[x].tb=function(a){this.Fa=a};O(m[F].a[x],"setLinkTarget",m[F].a[x].tb);M=m[F].a[x];M.t=function(){return this.Fa&&this.Fa!=""?this.Fa:c};
M.tf=function(){this.ig++;this.Dc++;this.Ib&&k[ua](this.Ib);this.Ib=k[za](R(this,this[L],[c]),m[F].a.md)};M.Ye=function(){k[ua](this.Ib);var a=this.Dc;this.Dc=0;return a};M.mc=function(){if(this.fc==c)this.fc="gsc-"+this.z+"Result";return this.fc};M.ha=function(){if(this.hc==c)this.hc="gs-"+this.z+"Result";return this.hc};M.qf=function(){if(this.Nb==c)this.Nb=P[this.z];return this.Za?this.Za:this.Nb};M.of=function(){if(this.sc==c)this.sc=P[this.z];return this.Za?this.Za:this.sc};M.pf=function(){return this.Wa};
O(m[F].a[x],"getResultSetSize",m[F].a[x].pf);m[F].a[x].pa=function(a){switch(a){case m[F].a.ta:this.Wa=m[F].a.ta;break;default:case m[F].a.ba:this.Wa=m[F].a.ba;break}};O(m[F].a[x],"setResultSetSize",m[F].a[x].pa);pa(m[F].a[x],function(a){var d=(new Date)[Ta]();this.Cc=d%100==1?d:-1;d=this.ga(a,c,c);d+="&"+this.ib;if(k._googleudsextrastuff)d=d+k._googleudsextrastuff;this.cursor=c;this.xf=a;Wa(d,m[F][va]);if(this.oa&&this.oa[w]>0)for(d=0;d<this.oa[w];d++)this.oa[d][L](a)});O(m[F].a[x],"execute",m[F].a[x][L]);
m[F].a[x].fe=function(a){if(this[y]&&a<this[y].pages[w]){a=this.ga(this.xf,c,c,this[y].pages[a].start);this.cursor=c;Wa(a,m[F][va])}};O(m[F].a[x],"gotoPage",m[F].a[x].fe);m[F].a[x].Re=function(a){this.oa&&this.oa[ra](a)};O(m[F].a[x],"addRelatedSearcher",m[F].a[x].Re);m[F].a[x].nf=function(a,d,e){return this.ga(a,d,e)+"&key="+m[J].ApiKey+"&v="+m[F][va]};O(m[F].a[x],"getExecuteUrl",m[F].a[x].nf);
m[F].a[x].ua=function(a){var d=P.watermark+" - "+this.af();d=Y("http://code.google.com/apis/ajaxsearch/faq.html",d,"_blank","gs-watermark");T(a,d)};m[F].a[x].af=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};
m[F].a[x].Ta=function(a){var d;d=a.getFullYear();var e=a.getMonth(),f=P["month-abbr"][e];a=a.getDate();if(a<10)a="0"+a;switch(m[F].ShortDatePattern){case "MDY":d=f+" "+a+", "+d;break;case "YMD":if(m[F][K]=="zh-CN"||m[F][K]=="zh-TW"||m[F][K]=="ja"||m[F][K]=="ko"){f=Eb[m[F][K]];d=d+f.year+(e+1)+f.month+a+f.day}else d=d+" "+f+" "+a;break;default:case "DMY":d=a+" "+f+" "+d;break}return d};O(m[F].a[x],"formatToShortDate",m[F].a[x].Ta);
var Eb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};m[F].a.nd=3600000;m[F].a.Oe=60000;m[F].a.Ne=86400000;
m[F].a[x].lc=function(a){var d=(new Date)[Ta](),e=a[Ta]();if(d<e)return P["n-minutes-ago"](2);d=d-e;if(d<m[F].a.nd){a=q[Ba](d/m[F].a.Oe);a=a<=1?2:a;return P["n-minutes-ago"](a)}if(d<m[F].a.Ne){a=q[Ba](d/m[F].a.nd);if(a<=1)return P["one-hour-ago"];else{a=a;return P["n-hours-ago"](a)}}return this.Ta(a)};O(m[F].a[x],"formatToRelativeDate",m[F].a[x].lc);m[F].a[x].Td=function(){this.jh=this.gwsUrl=c;this.results=[]};O(m[F].a[x],"clearResults",m[F].a[x].Td);
m[F].a[x].hf=function(){this.Ud&&this.Ud();if(this.Cc!=-1){m[J][Qa]("asa_"+this.z,"req."+((new Date)[Ta]()-this.Cc),b);this.Cc=-1}};
m[F].a[x].U=function(a,d,e,f){if(!(a==c&&d==204)){this.gwsUrl=c;if(this.results&&this.results[w]>0)for(var i=0;i<this.results[w];i++)this.results[i].html&&Fb(this.results[i].html);if(a&&a.results&&a.results[w]>0){this.results=a.results;if(a[y]&&a[y].moreResultsUrl)this.gwsUrl=this.xa&&this.xa!=""?this.xa:a[y].moreResultsUrl;else if(this.v&&this.ma)this.gwsUrl=this.If()}else this.results=[];this.completionStatus=d;this.hashStatus=f;this.zg=e;this.ne=a&&a.resultAttribution&&a.resultAttribution!=c&&
a.resultAttribution!=""?a.resultAttribution:c;if(a&&a[y]&&a[y].pages&&a[y].pages[w]>0)this.cursor=a[y];else typeof this[y]!="undefined"&&delete this[y];if(a&&a.context)this.context=a.context;else typeof this.context!="undefined"&&delete this.context;if(a&&a.promotions)this.promotions=a.promotions;else typeof this.promotions!="undefined"&&delete this.promotions;if(a&&a.omittedResults)this.omittedResults=a.omittedResults;else typeof this.omittedResults!="undefined"&&delete this.omittedResults;this.ce&&
this.Ue();this.hf()}};O(m[F].a[x],"onSearchComplete",m[F].a[x].U);m[F].a[x].de=function(){var a=c;if(this.ne)a=V(this.ne,"gs-results-attribution");return a};O(m[F].a[x],"getAttribution",m[F].a[x].de);m[F].a[x].Ue=function(){var a,d;for(a=0;a<this.results[w];a++){d=this.results[a];this.D(d)}};m[F].a[x].vb=function(a,d,e){e||(e=[c]);this.Ud=R(a,d,e)};O(m[F].a[x],"setSearchCompleteCallback",m[F].a[x].vb);
m[F].a.ia=function(a,d){var e=g,f;if(a[w])for(var i=0;i<a[w];i++)if(a[i]==c){a[i]=d;f=i;e=b;break}if(!e){f=a[w];a[ra](d)}return f};O(m[F].a,"AllocateCompletionMapContext",m[F].a.ia);m[F].a[x].xb=function(a){this.Za=a};O(m[F].a[x],"setUserDefinedLabel",m[F].a[x].xb);m[F].a[x].ag=function(a){this.yb=a};O(m[F].a[x],"setUserDefinedClassSuffix",m[F].a[x].ag);m[F].a[x].Tf=function(){this.ce=g};O(m[F].a[x],"setNoHtmlGeneration",m[F].a[x].Tf);
m[F].a.Xa=function(a,d,e,f,i){var l=q.min(e[C]/a,e[Sa]/d);l=q.min(l,1);var n={};ja(n,q[wa](a*l));u(n,q[wa](d*l));if(f){ja(f,n[C]);u(f,n[Sa]);if(i)f[E].left=(e[C]-n[C])/2+"px"}return n};O(m[F].a,"scaleImage",m[F].a.Xa);m[F].a.Nd=1;O(m[F].a,"VERTICAL_BRANDING",m[F].a.Nd);m[F].a.Be=2;O(m[F].a,"HORIZONTAL_BRANDING",m[F].a.Be);
m[F].a.lf=function(a,d,e){var f=d&&d==m[F].a.Nd,i=new Db("gsc-");d=W(i.bc);var l=fb(c,c,i.bc);T(d,l);f=!f;if(!f){Z(d,i.Qb);Z(l,i.Qb)}var n=gb(l,0),z,B;if(f)B=z=n;else{z=n;B=gb(l,0)}var U="/css/small-logo.png",S=51;n=15;if(e)if(typeof e=="string")if(e[Ja](/^http:\/\/www\.youtube\.com/)){U="/css/youtube-logo-55x24.png";S=55;n=24;Z(d,i.bc+"-youtube");if(!f){Z(d,i.Qb+"-youtube");Z(l,i.Qb+"-youtube")}}f=X(z,i.text);l=X(B,i.ge);z=V(P["powered-by"],i.text);U=m[J][Ra]+U;S=S;n=n;B=i.ge;if(wb&&!xb){B=W(B);
B[E].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+U+'")';ja(B[E],S+"px");u(B[E],n+"px")}else B=ib(U,c,c,B);n=B;T(f,z);if(e){f="http://www.google.com";if(typeof e=="string"&&(e[Ja](/^http:\/\/[a-z]*\.google\.com/)||e[Ja](/^http:\/\/www\.youtube\.com/)))f=e;e=jb(f,c,"_BLANK");s(e,i.Ze);T(e,n);T(l,e)}else T(l,n);if(a){a=typeof a=="string"?p.getElementById(a):a;db(a);T(a,d)}return a=d};O(m[F].a,"getBranding",m[F].a.lf);
m[F].a.setOnLoadCallback=function(a,d){m.setOnLoadCallback(a,d)};O(m[F].a,"setOnLoadCallback",m[F].a.setOnLoadCallback);var Gb;function Fb(a){Gb||(Gb=p[H]("DIV"));Gb[v](a);t(Gb,"")}m[F].a[x].jf=function(a){var d=this.gb;if(a)d=a;a={};var e=W(this.ha());Z(e,"gs-result");Z(e,"gs-error-result");d=V(d,"gs-snippet");T(e,d);a.html=e;return a};m[F].a[x].kf=function(a){var d=this.nb;if(a)d=a;a={};var e=W(this.ha());Z(e,"gs-result");Z(e,"gs-no-results-result");d=V(d,"gs-snippet");T(e,d);a.html=e;return a};
j("google.search.CurrentLocale",ea);j("google.search.ShortDatePattern",aa);m[F].r=function(){m[F].a[G](this);this.z="blog";this.Ba="/GblogSearch";this.ma="http://blogsearch.google.com/blogsearch";this.m=c;this.N=g;this.Ra=b;this.da=cb(this,m[F].r[x].na);this.Qa="gsc-blogConfig";this.k=c};N("google.search.BlogSearch",m[F].r);Va(m[F].r,m[F].a);m[F].r.C="GblogSearch";O(m[F].r,"RESULT_CLASS",m[F].r.C);m[F].r.o=[];m[F].r.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].r.o[l];m[F].r.o[l]=c;a.U(d,e,f,i)};O(m[F].r,"RawCompletion",m[F].r.H);
m[F].r[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].r.o,this):e;d=d==c?"google.search.BlogSearch.RawCompletion":d;f=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;if(this.m)a=a+" blogurl:"+this.m;a="&q="+h(a);if(this.N)a=a+"&scoring=d";f=f+a;this.v=a}return f};
m[F].r[x].D=function(a){a.html&&delete a.html;var d=W(this.ha());Z(d,"gs-result");var e;e=Y(a.postUrl,a[sa],this.t(),"gs-title");T(d,e);e=new Date(a.publishedDate);e=V(this.Ta(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=V(this.lc(e),"gs-relativePublishedDate");T(d,e);e=V(a[Ca],"gs-snippet");T(d,e);e=Y(a.blogUrl,a.blogUrl,this.t(),"gs-visibleUrl");T(d,e);a.html=d;this.ua(a.html)};O(m[F].r[x],"createResultHtml",m[F].r[x].D);m[F].r[x].qa=function(a){this.m=a==c||a==""?c:a};
O(m[F].r[x],"setSiteRestriction",m[F].r[x].qa);m[F].r[x].K=function(a){this.N=a==m[F].a.ka?b:a==m[F].a.la?g:g};O(m[F].r[x],"setResultOrder",m[F].r[x].K);
m[F].r[x].na=function(a,d){if(d)if(this.k==c){d=W("gsc-configSetting");this.k=ob(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.k);T(d,V(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,lb(P[Ia],"gsc-configSettingSubmit"));T(d,e);T(a,d);this.k[La]()}else{ka(this.k,this.N);this.k[La]()}else if(this.k)this.k[ya]?this.K(m[F].a.ka):this.K(m[F].a.la)};m[F].l=function(){m[F].a[G](this);this.z="book";this.Ba="/GbookSearch";this.ma="http://books.google.com/books";this.Hb=g;this.Ec=c};N("google.search.BookSearch",m[F].l);Va(m[F].l,m[F].a);m[F].l.C="GbookSearch";O(m[F].l,"RESULT_CLASS",m[F].l.C);m[F].l.Md="user-list";O(m[F].l,"USER_LIST",m[F].l.Md);m[F].l.Ed=1;O(m[F].l,"TYPE_ALL_BOOKS",m[F].l.Ed);m[F].l.Id=2;O(m[F].l,"TYPE_FULL_VIEW_BOOKS",m[F].l.Id);m[F].l.o=[];
m[F].l.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].l.o[l];m[F].l.o[l]=c;a.U(d,e,f,i)};O(m[F].l,"RawCompletion",m[F].l.H);m[F].l[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].l.o,this):e;d=d==c?"google.search.BookSearch.RawCompletion":d;f=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;a="&q="+h(a);if(this.Hb)a=a+"&as_brr=1";if(this.Ec)a=a+"&as_list="+this.Ec;f=f+a;this.v=a}return f};
m[F].l[x].D=function(a){a.html&&delete a.html;a.thumbnailHtml=this.gc(a);var d=W(this.ha());Z(d,"gs-result");var e=W("gs-text-box"),f=fb(),i=gb(f,0),l=X(i,"gs-image-box");i=X(i,"gs-text-box");T(l,a.thumbnailHtml[Na](b));T(i,e);T(d,f);f=Y(a.unescapedUrl,a[sa],this.t(),"gs-title");T(e,f);f=V(P.by+"&nbsp;"+a.authors,"gs-author");T(e,f);f=W("gs-spacer");T(e,f);if(a.publishedYear){f=V(a.publishedYear,"gs-publishedDate");T(e,f)}if(ca(a.pageCount,10)>0){f=V("-&nbsp;"+P["page-count"](a.pageCount),"gs-pageCount");
T(e,f)}f=Y("http://books.google.com","books.google.com",this.t(),"gs-visibleUrl");T(e,f);a.html=d;this.ua(a.html)};O(m[F].l[x],"createResultHtml",m[F].l[x].D);
m[F].l[x].gc=function(a){var d=W("gs-image-box gs-book-image-box"),e=W("gs-row-1"),f=ib("http://books.google.com/googlebooks/pages-trans.gif",c,c,"gs-pages");T(e,f);f=ib("http://books.google.com/googlebooks/p_edge-trans.gif",c,c,"gs-page-edge");T(e,f);T(d,e);e=W("gs-row-2");f=m[F].a.Xa(a.tbWidth,a.tbHeight,this.M);f=ib(a.tbUrl,f[C],f[Sa],"gs-image");a=jb(a.unescapedUrl,c,this.t(),"gs-image");s(a,"gs-image");T(a,f);T(e,a);T(d,e);return d};
m[F].l[x].V=function(a,d){if(a==m[F].a.zb)if(d)if(d==m[F].l.Ed)this.Hb=g;else if(d==m[F].l.Id)this.Hb=b;else this.V(a,c);else this.Hb=g;else if(a==m[F].l.Md)this.Ec=d&&d[Ja](/^[a-zA-Z0-9\-_]*$/)?d:c};O(m[F].l[x],"setRestriction",m[F].l[x].V);m[F].c=function(){m[F].a[G](this);this.ke=2;this.z="image";this.Ba="/GimageSearch";this.ma="http://images.google.com/images";this.m=this.xc=this.kc=this.qc=this.oc=this.nc=this.pc=this.Ha=c;this.M={width:112,height:84}};N("google.search.ImageSearch",m[F].c);Va(m[F].c,m[F].a);m[F].c.C="GimageSearch";O(m[F].c,"RESULT_CLASS",m[F].c.C);m[F].c.wd="restrict-imagesize";O(m[F].c,"RESTRICT_IMAGESIZE",m[F].c.wd);m[F].c.Fe=["icon"];O(m[F].c,"IMAGESIZE_SMALL",m[F].c.Fe);m[F].c.Ee=["small","medium","large","xlarge"];
O(m[F].c,"IMAGESIZE_MEDIUM",m[F].c.Ee);m[F].c.De=["xxlarge"];O(m[F].c,"IMAGESIZE_LARGE",m[F].c.De);m[F].c.Ce=["huge"];O(m[F].c,"IMAGESIZE_EXTRA_LARGE",m[F].c.Ce);m[F].c.td="restrict-coloration";O(m[F].c,"RESTRICT_COLORIZATION",m[F].c.td);m[F].c.Ic="mono";O(m[F].c,"COLORIZATION_BLACK_AND_WHITE",m[F].c.Ic);m[F].c.Kc="gray";O(m[F].c,"COLORIZATION_GRAYSCALE",m[F].c.Kc);m[F].c.Jc="color";O(m[F].c,"COLORIZATION_COLOR",m[F].c.Jc);m[F].c.sd="restrict-colorfilter";O(m[F].c,"RESTRICT_COLORFILTER",m[F].c.sd);
m[F].c.Tc="red";O(m[F].c,"COLOR_RED",m[F].c.Tc);m[F].c.Qc="orange";O(m[F].c,"COLOR_ORANGE",m[F].c.Qc);m[F].c.Wc="yellow";O(m[F].c,"COLOR_YELLOW",m[F].c.Wc);m[F].c.Pc="green";O(m[F].c,"COLOR_GREEN",m[F].c.Pc);m[F].c.Uc="teal";O(m[F].c,"COLOR_TEAL",m[F].c.Uc);m[F].c.Mc="blue";O(m[F].c,"COLOR_BLUE",m[F].c.Mc);m[F].c.Sc="purple";O(m[F].c,"COLOR_PURPLE",m[F].c.Sc);m[F].c.Rc="pink";O(m[F].c,"COLOR_PINK",m[F].c.Rc);m[F].c.Vc="white";O(m[F].c,"COLOR_WHITE",m[F].c.Vc);m[F].c.Oc="gray";
O(m[F].c,"COLOR_GRAY",m[F].c.Oc);m[F].c.Lc="black";O(m[F].c,"COLOR_BLACK",m[F].c.Lc);m[F].c.Nc="brown";O(m[F].c,"COLOR_BROWN",m[F].c.Nc);m[F].c.vd="restrict-filetype";O(m[F].c,"RESTRICT_FILETYPE",m[F].c.vd);m[F].c.$c="jpg";O(m[F].c,"FILETYPE_JPG",m[F].c.$c);m[F].c.ad="png";O(m[F].c,"FILETYPE_PNG",m[F].c.ad);m[F].c.Zc="gif";O(m[F].c,"FILETYPE_GIF",m[F].c.Zc);m[F].c.Yc="bmp";O(m[F].c,"FILETYPE_BMP",m[F].c.Yc);m[F].c.xd="restrict-imagetype";O(m[F].c,"RESTRICT_IMAGETYPE",m[F].c.xd);m[F].c.cd="face";
O(m[F].c,"IMAGETYPE_FACES",m[F].c.cd);m[F].c.bd="clipart";O(m[F].c,"IMAGETYPE_CLIPART",m[F].c.bd);m[F].c.dd="lineart";O(m[F].c,"IMAGETYPE_LINEART",m[F].c.dd);m[F].c.ed="news";O(m[F].c,"IMAGETYPE_NEWS",m[F].c.ed);m[F].c.fd="photo";O(m[F].c,"IMAGETYPE_PHOTO",m[F].c.fd);m[F].c.rd="restrict";O(m[F].c,"RESTRICT",m[F].c.rd);m[F].c.ud="cc_attribute";O(m[F].c,"RESTRICT_CREATIVE_COMMONS",m[F].c.ud);m[F].c.o=[];m[F].c.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].c.o[l];m[F].c.o[l]=c;a.U(d,e,f,i)};
O(m[F].c,"RawCompletion",m[F].c.H);
m[F].c[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].c.o,this):e;d=d==c?"google.search.ImageSearch.RawCompletion":d;d=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;a="&q="+h(a);if(this.Ha)a=a+"&safe="+this.Ha;if(this.pc)a=a+"&imgsz="+h(this.pc);if(this.nc)a=a+"&imgc="+h(this.nc);if(this.oc)a=a+"&imgcolor="+h(this.oc);if(this.qc)a=a+"&imgtype="+h(this.qc);if(this.kc)a=a+"&as_filetype="+h(this.kc);if(this.xc)a=a+"&restrict="+h(this.xc);if(this.m)a=a+"&as_sitesearch="+h(this.m);d=d+a;this.v=a;if(f&&
f!=0)this.v=this.v+"&start="+f}return d};
m[F].c[x].D=function(a){a.html&&delete a.html;var d=W(this.ha());Z(d,"gs-result");var e=W("gs-image-box"),f=m[F].a.Xa(a.tbWidth,a.tbHeight,this.M),i=ib(a.tbUrl,f[C],f[Sa],"gs-image");i[E].left=(this.M[C]-f[C])/2+"px";r(i,a.titleNoFormatting+" ("+a.visibleUrl+")");f=jb(a.unescapedUrl,c,this.t(),"gs-image");s(f,"gs-image");T(f,i);T(e,f);T(d,e);e=W("gs-text-box");i=V(a[Ca],"gs-snippet");r(i,a.contentNoFormatting);T(e,i);i=V(a[C]+" x "+a[Sa],"gs-size");T(e,i);i=Y(a.originalContextUrl,a.visibleUrl,this.t(),
"gs-visibleUrl");r(i,a.visibleUrl);T(e,i);T(d,e);a.html=d;this.ua(a.html)};O(m[F].c[x],"createResultHtml",m[F].c[x].D);m[F].c[x].qa=function(a){this.m=a};O(m[F].c[x],"setSiteRestriction",m[F].c[x].qa);
m[F].c[x].V=function(a,d){if(a==m[F].a.Tb)this.Ha=d?d==m[F].a.Wb||d==m[F].a.Vb?d:d==m[F].a.Ub?c:c:c;else if(a==m[F].c.wd)this.pc=d?d.join("|"):c;else if(a==m[F].c.td)this.nc=d?d==m[F].c.Ic||d==m[F].c.Kc||d==m[F].c.Jc?d:c:c;else if(a==m[F].c.sd)this.oc=d?d==m[F].c.Tc||d==m[F].c.Qc||d==m[F].c.Wc||d==m[F].c.Pc||d==m[F].c.Uc||d==m[F].c.Mc||d==m[F].c.Sc||d==m[F].c.Rc||d==m[F].c.Vc||d==m[F].c.Oc||d==m[F].c.Lc||d==m[F].c.Nc?d:c:c;else if(a==m[F].c.vd)this.kc=d?d==m[F].c.$c||d==m[F].c.ad||d==m[F].c.Zc||d==
m[F].c.Yc?d:c:c;else if(a==m[F].c.xd)this.qc=d?d==m[F].c.cd||d==m[F].c.bd||d==m[F].c.dd||d==m[F].c.ed||d==m[F].c.fd?d:c:c;else if(a==m[F].c.rd)this.xc=d?d==m[F].c.ud?d:c:c};O(m[F].c[x],"setRestriction",m[F].c[x].V);m[F].e=function(){m[F].a[G](this);this.Z=c;this.Y="San Francisco, CA";this.ca={y:37.77916,x:-122.42009};this.Pa=c;this.mb=b;this.bb=g;this.Va=c;this.Ra=b;this.da=cb(this,this.na);this.Qa="gsc-locationConfig";this.z="local";this.Ba="/GlocalSearch";this.ma="http://www.google.com/local";this.Na=this.F=c};N("google.search.LocalSearch",m[F].e);Va(m[F].e,m[F].a);m[F].e.C="GlocalSearch";O(m[F].e,"RESULT_CLASS",m[F].e.C);m[F].e.Hd="blended";O(m[F].e,"TYPE_BLENDED_RESULTS",m[F].e.Hd);m[F].e.Kd="kmlonly";
O(m[F].e,"TYPE_KMLONLY_RESULTS",m[F].e.Kd);m[F].e.Ld="localonly";O(m[F].e,"TYPE_LOCALONLY_RESULTS",m[F].e.Ld);m[F].e.Fc="disabled";O(m[F].e,"ADDRESS_LOOKUP_DISABLED",m[F].e.Fc);m[F].e.Gc="enabled";O(m[F].e,"ADDRESS_LOOKUP_ENABLED",m[F].e.Gc);m[F].e.Bd=17;O(m[F].e,"STATIC_MAP_ZOOM_FARTHEST",m[F].e.Bd);m[F].e.Qe=4;O(m[F].e,"STATIC_MAP_ZOOM_DEFAULT",m[F].e.Qe);m[F].e.Ad=0;O(m[F].e,"STATIC_MAP_ZOOM_CLOSEST",m[F].e.Ad);m[F].e.$b=8;O(m[F].e,"STATIC_MAP_MAX_POINTS",m[F].e.$b);m[F].e.Hf=3.141592653589;
m[F].e.gf=6367000;m[F].e.gg=16093;m[F].e.o=[];m[F].e.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].e.o[l];m[F].e.o[l]=c;a.resultViewport=d&&d.viewport?d.viewport:c;a.U(d,e,f,i)};O(m[F].e,"RawCompletion",m[F].e.H);
m[F].e[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].e.o,this):e;d=d==c?"google.search.LocalSearch.RawCompletion":d;f=this.za(d,e,f);d="";if(a){d="&q="+h(a);f=f+d}this.Ah=c;if(this.Z){var i;if(this.mb){e=this.Z.getCenterLatLng();i=this.Z.getSpanLatLng();a="&sll="+e.y+","+e.x;a+="&sspn="+i[Sa]+","+i[C];a+=m[F].e.Cb(e.y,e.x);f+=a;d+=a}else{e=this.Z.getCenter();i=this.Z.getBounds().toSpan().toUrlValue();a="&sll="+e.y+","+e.x;a+="&sspn="+i;a+=m[F].e.Cb(e.y,e.x);f+=a;d+=a}}else if(this.ca){a="&sll="+this.ca.y+
","+this.ca.x;if(this.Pa)a=a+"&sspn="+this.Pa.lat+","+this.Pa.lng;a+=m[F].e.Cb(this.ca.y,this.ca.x);f+=a;d+=a}else if(this.Y){a="&near="+h(this.Y);f+=a;d+=a}if(this.bb){f+="&nogeocode=t";d+="&nogeocode=t"}if(this.Va){f+="&mrt="+h(this.Va);d+="&mrt="+h(this.Va)}if(d)this.v=d;return f};m[F].e.Cb=function(a,d){var e=2*m[F].e.gg/m[F].e.gf*2*m[F].e.Hf,f=d-e,i=a+e;d=d+e;return"&gll="+q[Ba]((a-e)*1000000)+","+q[Ba](f*1000000)+","+q[Ba](i*1000000)+","+q[Ba](d*1000000)+"&llsep=500,500"};
O(m[F].e,"centerToGll",m[F].e.Cb);
m[F].e[x].D=function(a){a.html&&delete a.html;var d=W(this.ha());Z(d,"gs-result");var e;e=Y(a.url,a[sa],this.t(),"gs-title");T(d,e);if(a.listingType=="kml"&&a[Ca]&&a[Ca]!=""){e=V(a[Ca],"gs-snippet");T(d,e)}var f=W("gs-address");if(a.addressLines&&a.addressLines[w]>0)for(var i=0;i<a.addressLines[w];i++){e=a.addressLines[i];var l="gs-addressLine";if(i==0)l="gs-street gs-addressLine";else if(i==1)l="gs-city gs-addressLine";e=V(e,l);T(f,e)}else{e=V(a.streetAddress,"gs-street");T(f,e);i="";if(a.city!=
""){i=a.city;if(a.region!="")i+=", "}e=V(i,"gs-city");T(f,e);e=V(a.region,"gs-region");T(f,e)}e=V(a.country,"gs-country");T(f,e);T(d,f);if(a.phoneNumbers&&a.phoneNumbers[w]){i=f=c;e=a.phoneNumbers[0];for(var n=0;n<a.phoneNumbers[w];n++){l=a.phoneNumbers[n];if(l[Oa]=="main"){f=l;break}if(l[Oa]==""||l[Oa]=="mobile"&&i==c)i=l}l=f?f:i?i:e;e=V(l.number,"gs-phone");T(d,e)}if(a.ddUrl&&a.ddUrl!=""){e=Y(a.ddUrl,P.directions,this.t(),"gs-directions");T(d,e)}if(a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&
a.ddUrlFromHere!=""){e=W("gs-directions-to-from");f=V(P["get-directions"]+":","gs-label");e[v](f);f=Y(a.ddUrlToHere,P["to-here"],this.t(),"gs-secondary-link");e[v](f);f=V("-","gs-spacer");e[v](f);f=Y(a.ddUrlFromHere,P["from-here"],this.t(),"gs-secondary-link");e[v](f);T(d,e)}a.html=d;this.ua(a.html)};O(m[F].e[x],"createResultHtml",m[F].e[x].D);
m[F].e[x].qe=function(a){if(a.centerAndZoom){this.mb=b;this.Z=a;this.ca=c;this.Y="";if(this.F)this.F=c}else if(a.setCenter){this.mb=g;this.Z=a;this.Pa=this.ca=c;this.Y="";if(this.F)this.F=c}else if(a.x&&a.y){this.mb=b;this.ca=a;this.Z=this.Pa=c;this.Y="";if(this.F)this.F=c}else if(a!=c&&a!=""){this.mb=b;this.Z=c;this.Y=a;this.ca=c;if(this.F)this.F=c;var d=new m[F].e;d.vb(this,this.Te,[d,a]);d[L](a)}};O(m[F].e[x],"setCenterPoint",m[F].e[x].qe);
m[F].e[x].Te=function(a,d){if(a.results&&a.results[w]){var e={};e.y=da(a.results[0].lat);e.x=da(a.results[0].lng);this.ca=e;this.Y=d;this.Ra=b;this.Z=c;if(a.resultViewport){d={};d.Qg=da(a.resultViewport.span.lat)/2;d.Rg=da(a.resultViewport.span.lng)/2;this.Pa=d}}};
m[F].e[x].na=function(a,d){if(d){if(this.F==c){d=c;if(this.Z==c){var e=W("gsc-configSetting");this.F=mb(c,"gsc-configSettingInput",this.Y==""?c:this.Y);T(e,V(P["search-location"],"gsc-configSettingInputLabel"));T(e,this.F);T(a,e);d=this.F}e=W("gsc-configSetting");this.Na=ob(c,"0",this.bb,"gsc-configSettingCheckbox");T(e,this.Na);T(e,V(P["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==c)d=this.Na;var f=V(c,"gsc-configSettingSubmit");T(f,lb(P[Ia],"gsc-configSettingSubmit"));T(e,f);
T(a,e);d[La]()}}else{if(this.F){if(this.F[Ea]){this.Y=this.F[Ea];this.qe(this.Y)}this.F=c}if(this.Na){this.bb=this.Na[ya];this.Na=c}db(a)}};m[F].e[x].Qf=function(a){if(a==m[F].e.Fc)this.bb=b;else if(a==m[F].e.Gc)this.bb=g};O(m[F].e[x],"setAddressLookupMode",m[F].e[x].Qf);m[F].e.me=function(a,d,e,f){var i=a.staticMapUrl;i=i[D](/&h=\d*/,"&h="+d);i=i[D](/&w=\d*/,"&w="+e);if(f&&f>=m[F].e.Ad&&f<=m[F].e.Bd)i=i[D](/&zl=\d*/,"&zl="+f);return a.staticMapUrl=i};O(m[F].e,"resizeStaticMapUrl",m[F].e.me);
m[F].e.bf=function(a,d,e,f){var i="",l="http://mt.google.com/mapdata?cc=us&tstyp=5&zl=4&w=150&h=100",n={};n.staticMapUrl=l;l=m[F].e.me(n,d,e,f);if(f==c)l=l[D](/&zl=\d*/,"");d=a[w];if(d>m[F].e.$b)d=m[F].e.$b;for(e=0;e<d;e++){n=a[e];if(n.lat&&n.lng)if(typeof n.lat=="string"){f=da(n.lat);n=da(n.lng)}else{f=n.lat;n=n.lng}else if(n.x&&n.y){f=n.y;n=n.x}else return c;n=n*1000000;f="&Point=b&Point.latitude_e6=__LAT__&Point.longitude_e6=__LNG__&Point.iconid=__ICONID__&Point=e"[D](/__LAT__/,q[Ba](f*1000000));
f=f[D](/__LNG__/,q[Ba](n));n=51+e;if(d==1)n=15;f=f[D](/__ICONID__/,n);i=i+f}return l+i};O(m[F].e,"computeStaticMapUrl",m[F].e.bf);m[F].e[x].V=function(a,d){if(a==m[F].a.zb)if(d){this.Va=c;this.Va=d==m[F].e.Hd||d==m[F].e.Kd||d==m[F].e.Ld?d:c}else this.Va=c};O(m[F].e[x],"setRestriction",m[F].e[x].V);m[F].n=function(){m[F].a[G](this);this.z="news";this.Ba="/GnewsSearch";this.ma="http://news.google.com/nwshp";this.nh=c;this.Ya="site:";this.N=g;this.Ra=b;this.da=cb(this,this.na);this.Qa="gsc-newsConfig";this.h=this.k=c};N("google.search.NewsSearch",m[F].n);Va(m[F].n,m[F].a);m[F].n.C="GnewsSearch";O(m[F].n,"RESULT_CLASS",m[F].n.C);m[F].n.qd="GnewsSearch.quote";O(m[F].n,"QUOTE_RESULT_CLASS",m[F].n.qd);m[F].n.o=[];
m[F].n.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].n.o[l];m[F].n.o[l]=c;a.U(d,e,f,i)};O(m[F].n,"RawCompletion",m[F].n.H);
m[F].n[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].n.o,this):e;d=d==c?"google.search.NewsSearch.RawCompletion":d;d=this.za(d,e,f);if(a||!a&&this.h){e=c;if(a)e=a;if(this.G)e=e==c?this.G:e+" "+this.G;if(this.m)e=e==c?this.Ya+this.m:e+" "+this.Ya+this.m;a=e?"&q="+h(e):"";if(this.N)a=a+"&scoring=d";if(this.h){e="";for(var i in this.h)if(i.charAt(0)==":")e+="&"+this.h[i];a=a+e}if(this.m&&this.Ya=="source:")d=d[D](/&hl=.*&/,"&hl=en&");d=d+a;this.v=a;if(f&&f!=0)this.v=this.v+"&start="+f}return d};
m[F].n[x].D=function(a){a.html&&delete a.html;if(!(a.GsearchResultClass==m[F].n.qd)){var d=W(this.ha());Z(d,"gs-result");var e;e=Y(a.unescapedUrl,a[sa],this.t(),"gs-title");T(d,e);e=V(a.publisher,"gs-publisher");T(d,e);e=a[Fa][Aa](",");if(e[w]>1){e=V(", "+e[e[w]-1],"gs-location");T(d,e)}e=new Date(a.publishedDate);e=V(" - "+this.Ta(e),"gs-publishedDate");T(d,e);e=new Date(a.publishedDate);e=V(" - "+this.lc(e),"gs-relativePublishedDate");T(d,e);e=V(a[Ca],"gs-snippet");T(d,e);if(a.clusterUrl&&a.clusterUrl!=
""){e=Y(a.clusterUrl,P["related-articles"]+"&nbsp;&raquo;",this.t(),"gs-clusterUrl");T(d,e)}a.html=d;this.ua(a.html)}};O(m[F].n[x],"createResultHtml",m[F].n[x].D);m[F].n[x].qa=function(a){if(a==c||a==""){this.m=c;this.Ya="site:"}else if(a[Ja]("[./:]")){this.Ya="site:";this.m=a}else{this.Ya="source:";this.m=a[D](/\s/g,"_")}};O(m[F].n[x],"setSiteRestriction",m[F].n[x].qa);m[F].n[x].K=function(a){this.N=a==m[F].a.ka?b:a==m[F].a.la?g:g};O(m[F].n[x],"setResultOrder",m[F].n[x].K);
m[F].n[x].na=function(a,d){if(d)if(this.k==c){d=W("gsc-configSetting");this.k=ob(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.k);T(d,V(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,lb(P[Ia],"gsc-configSettingSubmit"));T(d,e);T(a,d);this.k[La]()}else{ka(this.k,this.N);this.k[La]()}else if(this.k)this.k[ya]?this.K(m[F].a.ka):this.K(m[F].a.la)};
m[F].n[x].V=function(a,d){if(a==m[F].a.Sb)if(d)for(var e in d){a=d[e];if(e=="geo"){if(this.h==c)this.h={};this.h[":geo"]=e+"="+h(a)}if(e=="qsid"){if(this.h==c)this.h={};this.h[":qsid"]=e+"="+h(a)}if(e=="quotesearch"){if(this.h==c)this.h={};this.h[":quotesearch"]=e+"="+h(a)}if(e=="topic"){if(this.h==c)this.h={};this.h[":topic"]=e+"="+h(a)}if(e=="ned"){if(this.h==c)this.h={};this.h[":ned"]=e+"="+h(a)}if(e=="as_mind"){if(this.h==c)this.h={};this.h[":as_mind"]=e+"="+h(a)}if(e=="as_minm"){if(this.h==c)this.h=
{};this.h[":as_minm"]=e+"="+h(a)}if(e=="as_miny"){if(this.h==c)this.h={};this.h[":as_miny"]=e+"="+h(a)}if(e=="as_maxd"){if(this.h==c)this.h={};this.h[":as_maxd"]=e+"="+h(a)}if(e=="as_maxm"){if(this.h==c)this.h={};this.h[":as_maxm"]=e+"="+h(a)}if(e=="as_maxy"){if(this.h==c)this.h={};this.h[":as_maxy"]=e+"="+h(a)}}else this.h=c};O(m[F].n[x],"setRestriction",m[F].n[x].V);m[F].i=function(){m[F].a[G](this);this.z="patent";this.Ba="/GpatentSearch";this.ma="http://www.google.com/patents";this.we="";this.pb=c;this.Ra=b;this.da=cb(this,this.na);this.Qa="gsc-patentConfig";this.k=c};N("google.search.PatentSearch",m[F].i);Va(m[F].i,m[F].a);m[F].i.C="GpatentSearch";O(m[F].i,"RESULT_CLASS",m[F].i.C);m[F].i.Fd=1;O(m[F].i,"TYPE_ANY_STATUS",m[F].i.Fd);m[F].i.Jd=2;O(m[F].i,"TYPE_ISSUED_PATENTS",m[F].i.Jd);m[F].i.Gd=3;O(m[F].i,"TYPE_APPLICATIONS",m[F].i.Gd);m[F].i.o=[];
m[F].i.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].i.o[l];m[F].i.o[l]=c;a.U(d,e,f,i)};O(m[F].i,"RawCompletion",m[F].i.H);m[F].i[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].i.o,this):e;d=d==c?"google.search.PatentSearch.RawCompletion":d;f=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;a="&q="+h(a)+this.we;if(this.pb)a=a+this.pb;f=f+a;this.v=a}return f};
m[F].i[x].D=function(a){a.html&&delete a.html;a.thumbnailHtml=this.gc(a);var d=W(this.ha());Z(d,"gs-result");var e=W("gs-text-box"),f=fb(),i=gb(f,0),l=X(i,"gs-image-box");i=X(i,"gs-text-box");T(l,a.thumbnailHtml[Na](b));T(i,e);T(d,f);l=Y(a.unescapedUrl,a[sa],this.t(),"gs-title");T(e,l);f=W("gs-patent-info gs-metadata");T(e,f);l=c;l=a.patentNumber?a.patentStatus=="issued"?P["us-pat"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp;"+a.patentNumber:P["us-pat-app"]+"&nbsp; N/A";l=V(l,"gs-patent-number");
T(f,l);if(a.applicationDate){l=V(" - "+this.Ta(new Date(a.applicationDate)),"gs-publishedDate");T(f,l)}if(a.assignee){l=V(" - "+a.assignee,"gs-author");T(f,l)}l=V(a[Ca],"gs-snippet");T(e,l);T(e,l);a.html=d;this.ua(a.html)};O(m[F].i[x],"createResultHtml",m[F].i[x].D);m[F].i[x].gc=function(a){var d=W("gs-patent-image"),e=ib(a.tbUrl,75,100,"gs-image");a=jb(a.unescapedUrl,c,this.t(),"gs-image");s(a,"gs-image");T(a,e);T(d,a);return d};
m[F].i[x].K=function(a){this.pb=a==m[F].a.ka?"&scoring=d":a==m[F].a.pd?"&scoring=ad":a==m[F].a.la?c:c};O(m[F].i[x],"setResultOrder",m[F].i[x].K);m[F].i[x].V=function(a,d){if(a==m[F].a.zb)this.we=d?d==m[F].i.Fd?"":d==m[F].i.Jd?"&as_psrg=1":d==m[F].i.Gd?"&as_psra=1":"":""};O(m[F].i[x],"setRestriction",m[F].i[x].V);
m[F].i[x].na=function(a,d){if(d){var e=g;if(this.pb&&this.pb=="&scoring=d")e=b;if(this.k==c){d=W("gsc-configSetting");this.k=ob(c,"0",e,"gsc-configSettingCheckbox");T(d,this.k);T(d,V(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));e=W("gsc-configSettingSubmit");T(e,lb(P[Ia],"gsc-configSettingSubmit"));T(d,e);T(a,d);this.k[La]()}else{ka(this.k,e);this.k[La]()}}else if(this.k)this.k[ya]?this.K(m[F].a.ka):this.K(m[F].a.la)};m[F].B=function(){this.le=this.X=m[F].b.Da;this.j=c;this.M={width:112,height:84};this.Rb={width:100,height:75};this.nb=c};N("google.search.SearcherOptions",m[F].B);m[F].B[x].se=function(a){switch(a){case m[F].b.Xc:case m[F].b.La:case m[F].b.Da:this.X=a;break;default:this.X=m[F].b.Da;break}this.le=this.X};O(m[F].B[x],"setExpandMode",m[F].B[x].se);m[F].B[x].Wf=function(a){db(a);this.j=a};O(m[F].B[x],"setRoot",m[F].B[x].Wf);m[F].B[x].ub=function(a){this.nb=a};O(m[F].B[x],"setNoResultsString",m[F].B[x].ub);
m[F].B[x].Rf=function(a){if(a>100)a=100;u(this.M,a);ja(this.M,q[wa](a*1.33))};O(m[F].B[x],"setImageResultsTbHeight",m[F].B[x].Rf);m[F].B[x].bg=function(a){if(a>100)a=100;u(this.Rb,a);ja(this.Rb,q[wa](a*1.33))};O(m[F].B[x],"setVideoResultsTbHeight",m[F].B[x].bg);m[F].R=function(){ia(this,c);this.ve=c;this.W=m[F].b.ra};N("google.search.DrawOptions",m[F].R);m[F].R[x].Sf=function(a){ia(this,a)};O(m[F].R[x],"setInput",m[F].R[x].Sf);
m[F].R[x].Xf=function(a){if(a&&typeof a=="string")a=p.getElementById(a);this.ve=a};O(m[F].R[x],"setSearchFormRoot",m[F].R[x].Xf);m[F].R[x].re=function(a){this.W=a==m[F].b.ra||a==m[F].b.Ka?a:m[F].b.ra};O(m[F].R[x],"setDrawMode",m[F].R[x].re);
m[F].A=function(a,d,e){this.u=e;this.ec=this.jc=g;this.f=a;this.w=c;this.Mf=R(d,m[F].b[x].Gf,[this]);this.Pf=R(d,m[F].b[x].vc,[this,m[F].A.Zb]);this.Of=R(d,m[F].b[x].vc,[this,m[F].A.Yb]);this.Nf=R(d,m[F].b[x].vc,[this,m[F].A.zd]);this.Lf=R(d,m[F].b[x].Ff,[this]);this.Kf=R(d,m[F].b[x].Bf,[this]);this.f.vb(d,m[F].b[x].U,[this]);this.f.pa(d.Kb);this.f.tb(d.Fa);this.Q=this.Sa=this.wa=this.yc=this.jb=this.Pb=this.j=c;this.lb=b};m[F].A.Xb=0;m[F].A.Zb=1;m[F].A.Yb=2;m[F].A.zd=3;
m[F].A[x].Bc=function(a){var d="gsc-results-selector ";d+=a==m[F].A.Xb?this.u.X==m[F].b.Da?"gsc-one-result-active":this.f.Wa==m[F].a.ba?"gsc-more-results-active":"gsc-all-results-active":a==m[F].A.Zb?"gsc-one-result-active":a==m[F].A.Yb?"gsc-more-results-active":"gsc-all-results-active";s(this.yc,d)};
m[F].b=function(a){if(!m[J].KeyVerified)if(m[F].b.je())m[J].KeyVerified=b;else return;this.Kb=m[F].a.ba;this.W=m[F].b.ra;this.Lb=this.j=c;ia(this,c);this.Ob=m[F].b.Ab;this.uf=R(this,m[F].b[x].Cf,[c]);this.vf=R(this,m[F].b[x].Df,[c]);this.Ua=this.qb=this.zc=this.Jb=c;this.cb=this.zf=g;this.Fa=m[F].a.ab;this.rc=P.copy;this.d=[];this.rg=[];var d;if(a)for(var e=0;e<a[w];e++){d=new m[F].A(a[e],this,g);this.d[ra](d)}};N("google.search.SearchControl",m[F].b);m[F].b.od=P["no-results"];
O(m[F].b,"NO_RESULTS_DEFAULT_STRING",m[F].b.od);m[F].b.Dd=350;O(m[F].b,"TIMEOUT_SHORT",m[F].b.Dd);m[F].b.Ab=500;O(m[F].b,"TIMEOUT_MEDIUM",m[F].b.Ab);m[F].b.Cd=700;O(m[F].b,"TIMEOUT_LONG",m[F].b.Cd);m[F].b.Xc=1;O(m[F].b,"EXPAND_MODE_CLOSED",m[F].b.Xc);m[F].b.La=2;O(m[F].b,"EXPAND_MODE_OPEN",m[F].b.La);m[F].b.Da=3;O(m[F].b,"EXPAND_MODE_PARTIAL",m[F].b.Da);m[F].b.ra=1;O(m[F].b,"DRAW_MODE_LINEAR",m[F].b.ra);m[F].b.Ka=2;O(m[F].b,"DRAW_MODE_TABBED",m[F].b.Ka);m[F].b.ld="save";
O(m[F].b,"KEEP_LABEL_SAVE",m[F].b.ld);m[F].b.kd="keep";O(m[F].b,"KEEP_LABEL_KEEP",m[F].b.kd);m[F].b.jd="include";O(m[F].b,"KEEP_LABEL_INCLUDE",m[F].b.jd);m[F].b.hd="copy";O(m[F].b,"KEEP_LABEL_COPY",m[F].b.hd);m[F].b.gd="blank";O(m[F].b,"KEEP_LABEL_BLANK",m[F].b.gd);try{m[F].b.appPath=k[Fa].href}catch(Hb){m[F].b.appPath=c}
m[F].b.je=function(){var a=b,d;d=k[Fa].host[Ua]()[Aa](".");if(d[w]<2)d=g;else{var e=d.pop(),f=d.pop();if((f=="igoogle"||f=="gmodules"||f=="googlesyndication")&&e=="com")d=b;else{if(e[w]==2&&d[w]>0)if(tb[f]&&tb[f][e]==1)f=d.pop();d=f=="google"}}if(d)return b;if(m[J].LoadFailure)if(m[J].OriginalAppPath&&m[F].b.appPath)if(m[F].b.appPath==m[J].OriginalAppPath){m[J].LoadFailure=g;a=b}else{m[J].LoadFailure=g;a=b}m[J].KeyVerified=b;m[J].LoadFailure=g;return a};O(m[F].b,"keyCheck",m[F].b.je);
m[F].b[x].eb=function(a,d){this.va=b;this.Oa=a;if(d){if(d.includeVerticalAds!=o)this.Ca=d.includeVerticalAds;if(d.includeSideAds!=o)this.Ca=d.includeSideAds;if(d.iframes!=o)this.hb=d.iframes;if(d.useNarrowTopAd!=o)if(this.hb)this.ye=d.useNarrowTopAd;if(d.channel)this.Pd=d.channel;if(d.clientIP)this.Qd=d.clientIP;if(d.safe)this.Rd=d.safe;if(d[Da])this.Sd=d[Da];if(a=d.adtest||d.debug)this.ac=a;if(d.numTopAds!=o){this.Ga=d.numTopAds;this.Ga=q.max(0,q.min(4,this.Ga))}if(d.numSideAds!=o){this.ya=d.numSideAds;
this.Ca=(this.ya=q.max(0,q.min(8,this.ya)))?b:g}this.pe=d.enableSearchCompleteCallback?b:g}m[J][Qa]("hl","afs_ads")};O(m[F].b[x],"enableAds",m[F].b[x].eb);m[F].b[x].Ma=function(a,d){d||(d=new m[F].B);a.oa=c;this.d[ra](new m[F].A(a,this,d));if(this.rb(a))this.rf=b;a.sb="gsc"};O(m[F].b[x],"addSearcher",m[F].b[x].Ma);
m[F].b[x].Wd=function(a){if(this.d[a].u.j){this.d[a].lb=g;this.d[a].j=this.d[a].u.j;Z(this.d[a].j,"gsc-resultsRoot");$(this.d[a].j,"gsc-resultsbox-visible");Z(this.d[a].j,"gsc-resultsbox-invisible")}else this.d[a].j=W("gsc-resultsRoot");this.d[a].f.yb&&nb(this.d[a].j,"gsc-resultsRoot-"+this.d[a].f.yb);if(this.W==m[F].b.Ka)this.q[a].fa=this.d[a].j;var d=fb(c,c,"gsc-resultsHeader"),e=gb(d,0);this.d[a].Ja=X(e,"gsc-twiddleRegionCell");e=X(e,"gsc-configLabelCell");this.d[a].Pb=V("","gsc-twiddle");T(this.d[a].Ja,
this.d[a].Pb);var f=V(this.d[a].f.of(),"gsc-title");T(this.d[a].Pb,f);this.d[a].jb=V("","gsc-stats");T(this.d[a].Ja,this.d[a].jb);f=V();var i=V(P.blank,"gsc-result-selector gsc-one-result"),l=V(P.blank,"gsc-result-selector gsc-more-results"),n=V(P.blank,"gsc-result-selector gsc-all-results");r(i,P["show-one-result"]);r(l,P["show-more-results"]);r(n,P["show-all-results"]);T(f,i);T(f,l);T(f,n);na(i,this.d[a].Pf);na(l,this.d[a].Of);na(n,this.d[a].Nf);this.d[a].yc=f;this.d[a].Bc(m[F].A.Xb);T(this.d[a].Ja,
this.d[a].yc);na(this.d[a].Pb,this.d[a].Mf);if(this.d[a].f.da){this.d[a].P=eb("","gsc-configLabel");t(this.d[a].P,P.blank);Z(this.d[a].P,"gsc-twiddle-closed");T(e,this.d[a].P);na(this.d[a].P,this.d[a].Lf);r(this.d[a].P,P.settings);this.d[a].wa=W("gsc-config");Z(this.d[a].wa,this.d[a].f.Qa);this.d[a].Sa=kb("gsc-config");Z(this.d[a].Sa,this.d[a].f.Qa);this.d[a].Sa.onsubmit=this.d[a].Kf;T(this.d[a].wa,this.d[a].Sa);oa(this.d[a].wa[E],"none")}this.d[a].Q=W("gsc-results");e=this.d[a].f.mc();Z(this.d[a].Q,
e);this.d[a].u.j==c&&T(this.Aa,this.d[a].j);T(this.d[a].j,d);this.d[a].wa&&T(this.d[a].j,this.d[a].wa);T(this.d[a].j,this.d[a].Q)};m[F].b[x].Xd=function(a){var d=this.d[a],e={},f=d.f.qf();f=f[D](/ /g,"&nbsp;");e.T=V(f);e.fa=c;e.Ac=d.f;e.z=d.f.z;na(e.T,R(this,this.fg,[a]));this.q[a]=e;T(this.$,e.T);a="gs-spacer";if(Xa("opera"))a=a+" gs-spacer-opera";a=eb(" ",a);T(this.$,a);d.u.se(m[F].b.La)};
m[F].b[x].Gb=function(a,d){var e=c,f=c;if(d)if(d.W){this.W=d.W;e=d[A];f=d.ve}else this.W=m[F].b.ra;else this.W=m[F].b.ra;this.j=W("gsc-control");if(e!=c){ia(this,e);this[A].onkeyup=this.uf;this[A].onpaste=this.vf}else{if(f==c)f=this.j;d=new m[F].L(b,f);d.ue(this,this.submit);d.te(this,this.cc);ia(this,d[A]);this.fb&&d.sf()}this.Aa=W("gsc-resultsbox-invisible");if(this.W==m[F].b.Ka){this.$=W("gsc-tabsAreaInvisible");T(this.j,this.$);this.q=[];for(d=this.I=0;d<this.d[w];d++)this.Xd(d)}this.aa=this.j;
if(this.va){this.aa=W("gsc-wrapper");this.O=W("gsc-adBlockInvisible");this.S=W("gsc-adBlockVerticalInvisible");T(this.aa,this.O);T(this.j,this.S);T(this.j,this.aa);this.ac&&nb(this.j,"gsc-ad-preview")}T(this.aa,this.Aa);for(d=0;d<this.d[w];d++){this.Wd(d);if(this.W==m[F].b.Ka){Z(this.q[d].T,"gsc-tabHeader");Z(this.q[d].fa,"gsc-tabData");if(d==this.I){Z(this.q[d].T,"gsc-tabhActive");Z(this.q[d].fa,"gsc-tabdActive")}else{Z(this.q[d].T,"gsc-tabhInactive");Z(this.q[d].fa,"gsc-tabdInactive")}}}if(a&&typeof a==
"string")a=p.getElementById(a);if(a){a=a;d=this.j;if(a)try{db(a);a[v](d)}catch(i){}if((a=this.mf())&&a<300){this.zf=b;Z(this.j,"gsc-narrow")}}};O(m[F].b[x],"draw",m[F].b[x].Gb);m[F].b[x].$f=function(a){switch(a){case m[F].b.Dd:case m[F].b.Ab:case m[F].b.Cd:this.Ob=a;break;default:this.Ob=m[F].b.Ab;break}};O(m[F].b[x],"setTimeoutInterval",m[F].b[x].$f);
m[F].b[x].Uf=function(a,d,e){if(e)switch(e){case m[F].b.ld:case m[F].b.kd:case m[F].b.jd:case m[F].b.hd:case m[F].b.gd:this.rc=P[e];break;default:this.rc=e;break}this.Jb=cb(a,d)};O(m[F].b[x],"setOnKeepCallback",m[F].b[x].Uf);M=m[F].b[x];M.rb=function(a){var d=a.z;if(this.fb){if(d=="web"&&a.J!=m[F].g.ea)return g;return b}else return d=="blog"||d=="image"?b:g};
M.fg=function(a){if(!(this.I==a)){$(this.q[this.I].T,"gsc-tabhActive");$(this.q[this.I].fa,"gsc-tabdActive");Z(this.q[this.I].T,"gsc-tabhInactive");Z(this.q[this.I].fa,"gsc-tabdInactive");this.I=a;Z(this.q[this.I].T,"gsc-tabhActive");Z(this.q[this.I].fa,"gsc-tabdActive");$(this.q[this.I].T,"gsc-tabhInactive");$(this.q[this.I].fa,"gsc-tabdInactive");if(this.va){a=this.q[this.I].Ac;this.rb(a)?this.kb():this.Yd()}}};
M.kb=function(){if(this.va){s(this.O,"gsc-adBlockInvisible");s(this.S,"gsc-adBlockVerticalInvisible");this.Ca&&qb(this.aa,"gsc-thinWrapper")}};M.Yd=function(){if(this.va){this.uc>0?pb(this.O,"gsc-adBlock"):pb(this.O,"gsc-adBlockInvisible");if(this.Ca)if(this.tc>0){s(this.S,"gsc-adBlockVertical");Z(this.aa,"gsc-thinWrapper")}else{s(this.S,"gsc-adBlockVerticalInvisible");$(this.aa,"gsc-thinWrapper")}}};M.submit=function(){this[A][Ea][w]?this[L]():this.cc();return g};O(m[F].b[x],"submit",m[F].b[x].submit);
m[F].b[x].Fb=function(){if(this.$&&!this.eg&&(!this.fb||this.Od))s(this.$,"gsc-tabsArea")};
pa(m[F].b[x],function(a){if(a){a=a;this[A].onfocus&&this[A].onfocus();la(this[A],a)}else a=this[A][Ea];this.Bb=c;if(a[w]){this.cb=g;s(this.Aa,"gsc-resultsbox-visible");this.Fb();this.ib=m[J].createGuidArg_();var d=this.va;if(d&&this.rf&&this.W==m[F].b.ra)d=g;var e=this.wf();if(e==o&&!this.Oa&&!this.hb)d=g;if(d){d=this.Kb==m[F].a.ta;if(this.Ga==o)this.Ga=d?2:1;var f="w"+this.Ga;if(this.Ca){if(this.ya==o)this.ya=d?4:2;f=f+"n"+this.ya}if(this.hb){d="w"+this.Ga;d=m[J].GoogleApisBase+"/services/ads/afs?q="+
h(a)+"&hl="+h(m[F][K])+"&ad="+h(d)+"&source="+this.d[0].f.sb+"&"+this.ib}else d="http://www.google.com/"+(e?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+h(a)+"&hl="+h(m[F][K])+"&ad="+h(f)+"&js=uds&"+this.ib;if(e)d+="&cx="+e;if(this.Oa)d+="&client="+h(this.Oa);if(this.Pd)d+="&channel="+h(this.Pd);if(this.ac)d+="&adtest=on";if(this.Qd)d+="&ip="+h(this.Qd);if(this.Rd)d+="&adsafe="+h(this.Rd);if(this.Sd)d+="&useragent="+h(this.Sd);if(this.hb){qa(this.Aa[E],"hidden");this.Bb=new m[F].$a;this.kb();
t(this.O,"");t(this.S,"");if(ab()||bb())d+="&nocache="+_json_cache_defeater_++;d+="&referer="+k[Fa].host;if(this.Ga>0){if(this.ye)d=d[D](/&ad=[^&]*/,"&ad=n1w0");f=this.be(g);e=d.substring(0,2000);e=e[D](/%\w?$/,"");f.src=e;this.O[v](f)}if(this.Ca&&this.ya>0){e=d[D](/&ad=[^&]*/,"&ad="+("n"+this.ya));d=this.be(b);e=e.substring(0,2000);e=e[D](/%\w?$/,"");d.src=e;this.S[v](d)}}else{var i=this;k.google_afs_request_done=function(l){i.Af(l)};$a(d)}}for(e=0;e<this.d[w];e++){if(!this.d[e].lb){$(this.d[e].j,
"gsc-resultsbox-invisible");Z(this.d[e].j,"gsc-resultsbox-visible")}this.zc&&this.zc(this,this.d[e].f,a);if(this.d[e].f.oa)this.d[e].f.oa=c;this.d[e].f.ib=this.ib;this.d[e].f[L](a)}this.Bb&&this.Bb.start(2000)}});O(m[F].b[x],"execute",m[F].b[x][L]);M=m[F].b[x];M.cf=function(a,d){var e=this;return function(f){m[J][Qa]("afsq","1");if(d)e.tc=f;else e.uc=f;e.yf(a,d,f);f=f>0;if(e.$){var i=e.q[e.I].Ac;if(e.rb(i))f=g}f&&e.Yd()}};
M.Ve=function(a,d){var e=function(){var f=0;try{var i=a.contentWindow;if(i.frames&&i.frames[w])f=i.frames[0].name}catch(l){}d(f)};if(ab())ha(a,function(){if(a[Ka]=="loaded"||a[Ka]=="complete"){ha(a,c);e()}});else ga(a,function(){ga(a,c);e()})};
M.We=function(a,d){var e=function(f){f=f?f:k.event;if(f.source==a.contentWindow){if(k.detachEvent)k.detachEvent("onmessage",e);else k.removeEventListener&&k.removeEventListener("message",e,g);d(f.data)}};if(k.attachEvent)k.attachEvent("onmessage",e);else k.addEventListener&&k.addEventListener("message",e,g)};
M.be=function(a){var d=p[H]("iframe");d.name="google_afs_ads_frame";ja(d,0);u(d,0);d.frameBorder=0;d.marginWidth=0;d.marginHeight=0;d.vspace=0;d.hspace=0;d.pg="true";d.scrolling="no";qa(d[E],"hidden");a=this.Bb.jg(this.cf(d,a));var e=k;(e.postMessage?e:e.document.postMessage?e.document:c)?this.We(d,a):this.Ve(d,a);return d};M.yf=function(a,d,e){ja(a,"100%");u(a,"100%");u(a[E],d?e*5.65+3+"em":this.ye?e*5+(ab()?3:2)+"em":e*3+1+"em");if(e>0)qa(a[E],"visible")};
M.wf=function(){for(var a=0;a<this.d[w];a++){var d=this.d[a].f;if(d.z=="web")if(d.J!=m[F].g.ea)if(d.J==m[F].g.db)return d.m}return c};
M.Af=function(a){k.google_afs_request_done=c;if(this.O){m[J][Qa]("afsq","1");t(this.O,"");t(this.S,"");this.uc=this.tc=0;if(!a||a[w]<1)this.kb();else{if(!this.$)for(var d=0;d<this.d[w];d++){var e=this.d[d].f;if(this.rb(e)){this.kb();return}}s(this.O,"gsc-adBlock");e=g;var f=p[H]("h2");d="";if(this.ac)d="*DEBUG* ";d+=P["ads-by-google"];t(f,d);T(this.O,f);var i=a[w];for(d=0;d<i;d++){var l=a[d];if(l[Oa]=="text/wide"){this.uc++;var n=W("gsc-ad"),z=Y(l.url,l.line1,m[F].a.ab);T(n,z);z=p[H]("cite");t(z,
l.visible_url);T(n,z);z=eb();t(z,l.line2);T(n,z);T(this.O,n)}else if(this.Ca){this.tc++;if(!e){e=b;Z(this.aa,"gsc-thinWrapper");T(this.S,f[Na](b));s(this.S,"gsc-adBlockVertical")}n=W("gsc-ad");z=Y(l.url,l.line1,m[F].a.ab);T(n,z);z=eb();t(z,l.line2+"<br/>"+l.line3);T(n,z);z=p[H]("cite");t(z,l.visible_url);T(n,z);T(this.S,n)}}this.Ca&&!e&&qb(this.aa,"gsc-thinWrapper");if(this.$){e=this.q[this.I].Ac;this.rb(e)&&this.kb()}this.qb&&this.pe&&this.qb(this,"ads")}}};
M.Cf=function(){var a=this[A][Ea];if(a&&a!=""){this.Ua&&k[ua](this.Ua);this.Ua=k[za](R(this,m[F].b[x][L],[c]),this.Ob)}};M.Df=function(){this.Ua&&k[ua](this.Ua);this.Ua=k[za](R(this,m[F].b[x][L],[c]),this.Ob)};M.pa=function(a){switch(a){case m[F].a.ta:this.Kb=a;break;default:case m[F].a.ba:this.Kb=m[F].a.ba;break}for(var d=0;d<this.d[w];d++)this.d[d].f.pa(a)};O(m[F].b[x],"setResultSetSize",m[F].b[x].pa);m[F].b[x].tb=function(a){this.Fa=a;for(var d=0;d<this.d[w];d++)this.d[d].f.tb(a)};
O(m[F].b[x],"setLinkTarget",m[F].b[x].tb);m[F].b[x].ub=function(a){for(var d=0;d<this.d[w];d++)this.d[d].u.ub(a)};O(m[F].b[x],"setNoResultsString",m[F].b[x].ub);M=m[F].b[x];M.Gf=function(a){a.jc?this.Ia(a,g):this.Ia(a,b)};M.Ia=function(a,d,e){if(d){$(a.Ja,"gsc-twiddle-closed");Z(a.Ja,"gsc-twiddle-opened");a.jc=b;oa(a.Q[E],"block")}else{$(a.Ja,"gsc-twiddle-opened");Z(a.Ja,"gsc-twiddle-closed");a.jc=g;oa(a.Q[E],"none");t(a.jb,e?"(0)":"("+a.f.results[w]+")")}};M.Bf=function(a){this.wb(a,g,b);return g};
M.Ff=function(a){if(a.f.Ra)a.ec?this.wb(a,g,b):this.wb(a,b,b)};M.wb=function(a,d,e){if(d){if(a.P&&a.f.da){Z(a.P,"gsc-twiddle-opened");$(a.P,"gsc-twiddle-closed");t(a.P,P[Ia]);a.ec=b;oa(a.wa[E],"block");a.f.da(a.Sa,b)}}else if(a.P&&a.f.da){$(a.P,"gsc-twiddle-opened");Z(a.P,"gsc-twiddle-closed");t(a.P,P.blank);a.ec=g;a.f.da(a.Sa,g);oa(a.wa[E],"none");e&&this[L]()}};M.Ef=function(a,d){if(this.Jb){d.f.tf();this.Jb(a)}};M.Xe=function(){this.cb=b};O(m[F].b[x],"cancelSearch",m[F].b[x].Xe);
m[F].b[x].cc=function(){la(this[A],"");this[A].onblur&&this[A].onblur();s(this.Aa,"gsc-resultsbox-invisible");this.$&&pb(this.$,"gsc-tabsAreaInvisible");this.O&&pb(this.O,"gsc-adBlockInvisible");if(this.S){s(this.S,"gsc-adBlockVerticalInvisible");$(this.aa,"gsc-thinWrapper")}for(var a=0;a<this.d[w];a++){if(!this.d[a].lb){$(this.d[a].j,"gsc-resultsbox-visible");Z(this.d[a].j,"gsc-resultsbox-invisible")}var d=this.d[a];db(d.Q);d.w=c;this.Ia(d,g,b);this.wb(d,g,g)}};O(m[F].b[x],"clearAllResults",m[F].b[x].cc);
m[F].b[x].U=function(a){if(this.hb&&a==this.d[this.I])qa(this.Aa[E],"visible");var d,e,f=g,i;if(!this.cb){db(a.Q);a.w=c;this.Ia(a,g,b);this.wb(a,g,g);a.Bc(m[F].A.Xb);var l=a.f.context,n=this.$&&l;if(this.fb&&!this.Od){if(n){i=l[sa];for(e=0;e<this.q[w];e++){d=this.q[e];if(d.z==a.f.z){var z=a.f;if(i&&!a.f.Za)t(d.T,i);break}}}this.Od=b;this.Fb()}if((d=a.f.promotions)&&d[w]>0)for(e=0;e<d[w];e++){var B=d[e];B.html||a.f.Vd(B);if(B.html){i=W(a.f.mc());Z(i,"gsc-result");var U=B.html[Na](b);T(i,U);T(a.Q,i)}}B=
a.f.results;if(a.f.gb&&a.f.completionStatus>=400){B=[];B[ra](a.f.jf())}else if(B[w]==0&&a.u.nb&&a.f.completionStatus==200){B=[];B[ra](a.f.kf(a.u.nb))}for(e=0;e<B[w];e++){d=B[e];d.html||a.f.D(d);if(d.html){f=b;i=W(a.f.mc());Z(i,"gsc-result");a.f.yb&&nb(i,"gsc-result-"+a.f.yb);U=d.html[Na](b);if(d.GsearchResultClass==m[F].c.C){if(a.u.M)if(a.u.M[C]!=a.f.M[C]||a.u.M[Sa]!=a.f.M[Sa])for(var S=U.getElementsByTagName("img"),xa=0;xa<S[w];xa++)m[F].a.Xa(d.tbWidth,d.tbHeight,a.u.M,S[xa],b)}else if(d.GsearchResultClass==
m[F].s.C)if(a.u.Rb){S=U.getElementsByTagName("img");for(xa=0;xa<S[w];xa++)m[F].a.Xa(d.tbWidth,d.tbHeight,a.u.Rb,S[xa])}T(i,U);if(this.Jb){U=this.rc;S=V("","gsc-keeper");t(S,U);T(i,S);na(S,R(this,m[F].b[x].Ef,[d,a]))}if(e>=a.f.ke){if(!a.w){a.w=W("gsc-expansionArea");T(a.Q,a.w);if(a.u.X==m[F].b.Da)oa(a.w[E],"none")}T(a.w,i)}else T(a.Q,i)}}if(!a.w&&a.f[y]){a.w=W("gsc-expansionArea");T(a.Q,a.w)}if(a.w&&a.f.v&&a.f.gwsUrl){i=Y(a.f.gwsUrl,P["more-results"]+"&nbsp;&raquo;",a.f.t(),"gsc-trailing-more-results");
if(a.f[y]){e=W("gsc-cursor-box");d=this.df(a);e[v](d);e[v](i);T(a.w,e)}else T(a.w,i)}if(f){t(a.jb,"("+a.f.results[w]+")");a.u.X==m[F].b.Da||a.u.X==m[F].b.La?this.Ia(a,b):this.Ia(a,g);(e=a.f.de())&&T(a.Q,e)}else{t(a.jb,"(0)");t(a.Q,"");this.Ia(a,g)}a.u.X=a.u.le;this.qb&&this.qb(this,a.f);if(this.fb&&n&&!this.Se&&l.facets){a=this[A][Ea];l=l.facets;for(e=0;e<l[w];e++){n=l[e];f=new m[F].g;f.qa(z.m,n.label);f.xb(n.anchor);this.Ma(f);f[L](a)}for(e=0;e<this.d[w];e++)if(!this.q[e]){this.Xd(e);this.Wd(e);
Z(this.q[e].T,"gsc-tabHeader");Z(this.q[e].fa,"gsc-tabData");Z(this.q[e].T,"gsc-tabhInactive");Z(this.q[e].fa,"gsc-tabdInactive")}this.Se=b}}};O(m[F].b[x],"onSearchComplete",m[F].b[x].U);m[F].b[x].df=function(a){for(var d=W("gsc-cursor"),e=a.f[y],f=0;f<e.pages[w];f++){var i="gsc-cursor-page";if(f==e.currentPageIndex)i=i+" gsc-cursor-current-page";i=V(e.pages[f].label,i);na(i,R(this,m[F].b[x].Jf,[a,f]));d[v](i)}return d};
m[F].b.yd={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
m[F].b.he=function(a,d){if(bb())alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var e=b;if(d)e=d;if(e)for(d=0;d<a.childNodes[w];d++)m[F].b.he(a.childNodes[d],b);if(a.nodeType==1){var f,i;d=e=g;if(k[Ha]){f=k[Ha](a,c);e=i=b}else if(a[Ma]){f=a[Ma];i=g;e=b}if(e){for(var l in f)if(m[F].b.yd[l]){e=m[F].b.yd[l];var n=f[l];if(l=="display"&&n=="none"){t(a,"");d=b}if(f[l]!="")i?a[E].setProperty(e,n):a[E][I](e,n)}if(d)if(!i)a.outerHTML='<div style="display:none"/>'}}}};
O(m[F].b,"inlineCurrentStyle",m[F].b.he);m[F].b[x].mf=function(a){a=a?a:this.j;var d=c;if(k[Ha])d=k[Ha](a,c);else if(a[Ma])d=a[Ma];else if(p.defaultView[Ha])d=p.defaultView[Ha](a,c);return d?ca(d[C],10):300};m[F].b[x].vb=function(a,d){this.qb=cb(a,d)};O(m[F].b[x],"setSearchCompleteCallback",m[F].b[x].vb);m[F].b[x].Yf=function(a,d){this.zc=cb(a,d)};O(m[F].b[x],"setSearchStartingCallback",m[F].b[x].Yf);
m[F].b[x].vc=function(a,d){a.Bc(d);var e=g;switch(d){default:case m[F].A.Zb:if(a.w)oa(a.w[E],"none");break;case m[F].A.Yb:if(a.w)oa(a.w[E],"block");if(a.f.Wa!=m[F].a.ba)e=b;a.f.pa(m[F].a.ba);break;case m[F].A.zd:if(a.w)oa(a.w[E],"block");if(a.f.Wa!=m[F].a.ta)e=b;a.f.pa(m[F].a.ta);break}if(e){d=this[A][Ea];if(d[w]){this.cb=g;s(this.Aa,"gsc-resultsbox-visible");this.Fb();if(!a.lb){$(a.j,"gsc-resultsbox-invisible");Z(a.j,"gsc-resultsbox-visible")}a.u.X=m[F].b.La;a.f[L](d)}}};
m[F].b[x].Jf=function(a,d){this.cb=g;s(this.Aa,"gsc-resultsbox-visible");this.Fb();if(!a.lb){$(a.j,"gsc-resultsbox-invisible");Z(a.j,"gsc-resultsbox-visible")}a.u.X=m[F].b.La;a.f.fe(d)};
m[F].L=function(a,d,e){var f=kb("gsc-search-box");f.acceptCharset="utf-8";var i=c,l=P["search-uc"],n=P[F];if(e){if(e.buttonText)n=l=e.buttonText;if(e.clickableBrandingUrl){i="http://www.google.com";if(typeof e.clickableBrandingUrl=="string"&&e.clickableBrandingUrl[Ja](/^http:\/\/[a-z]*\.google\.com/))i=e.clickableBrandingUrl;i=jb(i,c,"_BLANK");s(i,"gsc-branding-clickable")}}this.Lb=lb(l,"gsc-search-button");r(this.Lb,n);if(a){e="gsc-branding-img";this.dc=V(P.blank,"gsc-clear-button");r(this.dc,P["clear-results"])}else e=
"gsc-branding-img-noclear";ia(this,mb(c,"gsc-input",c));this[A].name="search";r(this[A],n);n=fb(c,c,"gsc-search-box");T(f,n);n=gb(n,0);this.ie=X(n,"gsc-input");l=X(n,"gsc-search-button");if(a){a=X(n,"gsc-clear-button");T(a,this.dc)}T(this.ie,this[A]);T(l,this.Lb);a=fb(c,c,"gsc-branding");T(f,a);n=gb(a,0);this.userDefinedCell=X(n,"gsc-branding-user-defined");a=X(n,"gsc-branding-text");n=X(n,e);l=V(P["powered-by"],"gsc-branding-text");var z=m[J][Ra]+"/css/small-logo.png";e=e;if(ab()){e=W(e);e[E].filter=
'progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+z+'")';ja(e[E],"51px");u(e[E],"15px")}else e=ib(z,c,c,e);e=e;T(a,l);if(i){T(i,e);T(n,i)}else T(n,e);this.oe=f;db(d);T(d,this.oe)};N("google.search.SearchForm",m[F].L);m[F].L[x].ue=function(a,d){this.xe=R(this,this.dg,[this]);this.Mb=R(a,d,[this]);this.oe.onsubmit=this.xe;na(this.Lb,this.xe)};O(m[F].L[x],"setOnSubmitCallback",m[F].L[x].ue);m[F].L[x].te=function(a,d){na(this.dc,R(a,d,[this]))};O(m[F].L[x],"setOnClearCallback",m[F].L[x].te);
m[F].L[x].dg=function(){var a=this.ie.offsetWidth,d=this[A][Ea];this.Mb&&this.Mb();if(ab()){var e=this,f;f=d[w]*8>=a?a-6:"99%";k[za](function(){ja(e[A][E],f)},1)}return g};pa(m[F].L[x],function(a){if(a)la(this[A],a);this.Mb&&this.Mb()});O(m[F].L[x],"execute",m[F].L[x][L]);
m[F].L[x].sf=function(){var a=this[A],d=function(){if(a[Ea]=="")a[E].background="#FFFFFF url(http://www.google.com/coop/intl/"+m[F][K]+"/images/google_custom_search_watermark.gif) left no-repeat"},e=function(){a[E].background="#FFFFFF"};a.onblur=d;a.onfocus=e;d()};m[F].$a=function(){this.wc=0;this.ae=g;this.ob=[]};m[F].$a[x].jg=function(a){this.wc++;var d=this;return function(){for(var e=[],f=0;f<arguments[w];++f)e[ra](arguments[f]);if(d.ae)this.Zd(a,e);else{d.ob[ra]([a,e]);d.wc--;d.wc==0&&d.$d()}}};
m[F].$a[x].$d=function(){for(var a=0;a<this.ob[w];a++)this.Zd(this.ob[a][0],this.ob[a][1]);this.ob=[];this.ae=b};m[F].$a[x].Zd=function(a,d){k[za](function(){a[Pa](c,d)},0)};m[F].$a[x].start=function(a){k[za](R(this,this.$d,[]),a)};m[F].p=function(a){m[F].b[G](this);this.fb=b;this.pa(m[F].a.ta);this.eb("",{iframes:b});this.Db=new m[F].g;if(a==o){a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+k[Fa]};this.kg=b}this.Db.qa(a);this.Db.Nb=P.cse;this.Ma(this.Db);this.ub(m[F].b.od);this.hg=(new Date)[Ta]()};N("google.search.CustomSearchControl",m[F].p);Va(m[F].p,m[F].b);m[F].p[x].Gb=function(a,d){(d=d)||(d=new m[F].R);d.re(m[F].b.Ka);if(this.kg&&this.d[w]==1)this.eg=b;m[F].b[x].Gb[G](this,a,d);s(this.j,"gsc-control-cse")};
O(m[F].p[x],"draw",m[F].p[x].Gb);pa(m[F].p[x],function(a){var d=this.j.offsetWidth;$(this.aa,"gsc-thinWrapper");if(d<m[F].p.Ke)this.va=g;else d<m[F].p.Me?this.eb(this.Oa,{useNarrowTopAd:b,includeVerticalAds:g}):this.eb(this.Oa,{useNarrowTopAd:g,includeVerticalAds:d>m[F].p.Le});if((new Date)[Ta]()-this.hg<m[F].p.ze&&this.va){d=fa(k[Fa].href)[D]("+"," ");var e=fa(a)[D]("+"," ");this.va=d[Ga](e)!=-1}m[F].b[x][L][G](this,a)});O(m[F].p[x],"execute",m[F].p[x][L]);m[F].p[x].xb=function(a){this.Db.xb(a)};
O(m[F].p[x],"setUserDefinedLabel",m[F].p[x].xb);m[F].p[x].Ma=function(a,d){m[F].b[x].Ma[G](this,a,d);a.sb="gcsc"};O(m[F].p[x],"addSearcher",m[F].p[x].Ma);m[F].p[x].ff=function(){m[F].b[x].eb("",{numTopAds:0,numSideAds:0});this.Oa=c;this.pe=g};O(m[F].p[x],"disableAds",m[F].p[x].ff);m[F].p.Ae="";O(m[F].p,"AUTO_PUBID",m[F].p.Ae);m[F].p.Ke=250;m[F].p.Me=500;m[F].p.Le=800;m[F].p.ze=500;m[F].s=function(){m[F].a[G](this);this.z="video";this.Ba="/GvideoSearch";this.ma="http://video.google.com/videosearch";this.N=g;this.Ra=b;this.da=cb(this,this.na);this.Qa="gsc-videoConfig";this.k=c};N("google.search.VideoSearch",m[F].s);Va(m[F].s,m[F].a);m[F].s.C="GvideoSearch";O(m[F].s,"RESULT_CLASS",m[F].s.C);m[F].s.o=[];m[F].s.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].s.o[l];m[F].s.o[l]=c;a.U(d,e,f,i)};O(m[F].s,"RawCompletion",m[F].s.H);
m[F].s[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].s.o,this):e;d=d==c?"google.search.VideoSearch.RawCompletion":d;d=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;a="&q="+h(a);if(this.N)a=a+"&scoring=d";d=d+a;this.v=a;if(f&&f!=0)this.v=this.v+"&start="+f}return d};
m[F].s[x].D=function(a){a.html&&delete a.html;var d=W(this.ha());Z(d,"gs-result");var e=W("gs-image-box"),f=W("gs-text-box"),i=fb(),l=gb(i,0),n=X(l,"gs-image-box");l=X(l,"gs-text-box");T(n,e);T(l,f);T(d,i);i=m[F].a.Xa(a.tbWidth,a.tbHeight,this.M);i=ib(a.tbUrl,i[C],i[Sa],"gs-image");n=jb(a.url,c,this.t(),"gs-image");s(n,"gs-image");T(n,i);T(e,n);e=Y(a.url,a[sa],this.t(),"gs-title");T(f,e);e=V(a[Ca],"gs-snippet");if(ab())u(e[E],"2.6em");T(f,e);e=V(this.Ta(new Date(a.published)),"gs-publishedDate");
T(f,e);e=Y("http://"+a.publisher,a.publisher,this.t(),"gs-publisher");T(f,e);a.html=d;this.ua(a.html)};O(m[F].s[x],"createResultHtml",m[F].s[x].D);
m[F].s.ef=function(a,d){var e=c;if(a.playUrl&&a.playUrl!=""){e=a.playUrl;var f="gsc-video-player";if(d)f=d;if(Xa("opera")){var i=p[H]("object");s(i,f);i[I]("type","application/x-shockwave-flash");i[I]("data",e);e=W(d);e[v](i)}else{i=p[H]("embed");s(i,f);i[I]("type","application/x-shockwave-flash");i[I]("src",e);if(a.videoType)a.videoType=="Google"?i[I]("bgcolor","#000000"):i[I]("wmode","transparent");else i[I]("bgcolor","#000000");e=W(d);e[v](i)}}return e};O(m[F].s,"createPlayer",m[F].s.ef);
m[F].s[x].K=function(a){this.N=a==m[F].a.ka?b:a==m[F].a.la?g:g};O(m[F].s[x],"setResultOrder",m[F].s[x].K);m[F].s[x].na=function(a,d){if(d)if(this.k==c){d=W("gsc-configSetting");this.k=ob(c,"0",this.N,"gsc-configSettingCheckbox");T(d,this.k);T(d,V(P["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,lb(P[Ia],"gsc-configSettingSubmit"));T(d,e);T(a,d);this.k[La]()}else{ka(this.k,this.N);this.k[La]()}else if(this.k)this.k[ya]?this.K(m[F].a.ka):this.K(m[F].a.la)};m[F].g=function(){m[F].a[G](this);this.z="web";this.Ba="/GwebSearch";this.ma="http://www.google.com/search";this.m=c;this.J=m[F].g.ea;this.h=this.Ha=this.xa=this.ic=this.Ea=c};N("google.search.WebSearch",m[F].g);Va(m[F].g,m[F].a);m[F].g.C="GwebSearch";O(m[F].g,"RESULT_CLASS",m[F].g.C);m[F].g.db="cx";O(m[F].g,"cxRestriction_CX",m[F].g.db);m[F].g.Eb="cref";O(m[F].g,"cxRestriction_CREF",m[F].g.Eb);m[F].g.ea="none";O(m[F].g,"cxRestriction_NONE",m[F].g.ea);m[F].g.o=[];
m[F].g.H=function(a,d,e,f,i){var l=0;if(a)l=ca(a,10);a=m[F].g.o[l];m[F].g.o[l]=c;a.U(d,e,f,i)};O(m[F].g,"RawCompletion",m[F].g.H);
m[F].g[x].ga=function(a,d,e,f){e=e==c?m[F].a.ia(m[F].g.o,this):e;d=d==c?"google.search.WebSearch.RawCompletion":d;d=this.za(d,e,f);if(a){a=a;if(this.G)a=a+" "+this.G;if(this.m&&this.J!=m[F].g.ea&&this.ic){e=this.ic;var i=a;if(this.Ea!=c)i=a+" more:"+this.Ea;e=e[D](/__HL__/,m[F][K]);this.xa=e=e[D](/__QUERY__/,h(i))}if(this.m&&this.J==m[F].g.ea)a=a+" site:"+this.m;e="";if(this.m&&this.J!=m[F].g.ea){if(this.J==m[F].g.db)e=e+"&cx="+this.m;else if(this.J==m[F].g.Eb)e=e+"&cref="+h(this.m);if(this.Ea!=c)a=
a+" more:"+this.Ea}e=e+"&q="+h(a);if(this.Ha)e=e+"&safe="+this.Ha;if(this.h)e=e+this.h;d=d+e;this.v=e;if(f&&f!=0)this.v=this.v+"&start="+f}return d};
m[F].g[x].Vd=function(a){a.html&&delete a.html;var d=W("gs-promotion");Z(d,"gs-result");var e=Y(a.url,a[sa],this.t(),"gs-title");T(d,e);e=fb(0,0);var f=gb(e,0),i;T(d,e);if(a.image){e=a.image;e=ib(e.url,e[C],e[Sa],"gs-promotion-image");i=hb("gs-promotion-image-td");T(i,e);T(f,i)}if(a.bodyLines){i=hb();var l=W();T(f,i);T(i,l);f=a.bodyLines;for(i=0;i<f[w];i++){e=f[i];var n=e[sa],z=e.url,B=e.visibleUrl;e=W();if(z&&B){z=jb(z,B,this.t(),"gs-title");T(e,z)}n&&T(e,p.createTextNode(n?n:""));T(l,e)}}e=V(a.visibleUrl,
"gs-visibleUrl");T(l,e);Z(e,"gs-visibleUrl-short");a.html=d};O(m[F].g[x],"createPromotionHtml",m[F].g[x].Vd);
m[F].g[x].D=function(a){a.html&&delete a.html;var d=W(this.ha());Z(d,"gs-result");var e;e=Y(a.unescapedUrl,a[sa],this.t(),"gs-title");T(d,e);e=V(a[Ca],"gs-snippet");T(d,e);e=V(a.visibleUrl,"gs-visibleUrl");T(d,e);Z(e,"gs-visibleUrl-short");e=a.unescapedUrl[Ga](a.visibleUrl);var f=a.visibleUrl;if(e!=-1&&e!=0)f=a.unescapedUrl.substring(e);e=V(f,"gs-visibleUrl");Z(e,"gs-visibleUrl-long");T(d,e);a.html=d;this.ua(a.html)};O(m[F].g[x],"createResultHtml",m[F].g[x].D);
m[F].g[x].qa=function(a,d,e){this.gb=this.xa=c;var f=g;if(a==c||typeof a=="string"&&a==""){f=g;this.m=c;this.J=m[F].g.ea;this.gb=this.Ea=c}else if(typeof a=="string")if(f=a[Ja](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/)){this.m=a;this.J=m[F].g.db}else{this.m=a;this.J=m[F].g.ea}else if(a.siteUrl){f=g;this.m=a.siteUrl}else if(a.cseId){f=b;this.m=a.cseId;this.J=m[F].g.db}else if(a.crefUrl){f=b;this.m=a.crefUrl;this.J=m[F].g.Eb;this.gb=P["linked-cse-error-results"]}else{f=g;this.m=c;this.J=m[F].g.ea;this.Ea=
c}if(f){if(d)this.Ea=d;if(e)if(e[Ja](/__HL__/)&&e[Ja](/__QUERY__/))this.ic=e;if(this.J==m[F].g.Eb)if(!this.m[Ja](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/))(new Image).src="http://www.google.com/cse/tools/ping?cref="+h(this.m)+"&nocache="+Number(new Date)}};O(m[F].g[x],"setSiteRestriction",m[F].g[x].qa);
m[F].g[x].V=function(a,d){if(a==m[F].a.Tb)this.Ha=d?d==m[F].a.Wb||d==m[F].a.Vb||d==m[F].a.Ub?d:c:c;if(a==m[F].a.Sb)if(d)for(var e in d){a=d[e];if(e=="lr"||e=="usg"||e=="filter"){if(this.h==c)this.h="&";else this.h+="&";this.h+=e+"="+h(a)}}else this.h=c};O(m[F].g[x],"setRestriction",m[F].g[x].V);if(!m[F].NoOldNames){j("GwebSearch",m[F].g);j("GbookSearch",m[F].l);j("GblogSearch",m[F].r);j("GvideoSearch",m[F].s);j("GnewsSearch",m[F].n);j("GlocalSearch",m[F].e);j("GimageSearch",m[F].c);j("GpatentSearch",m[F].i);j("GSearch",m[F].a);j("GSearchControl",m[F].b);j("GSearchForm",m[F].L);j("GsearcherOptions",m[F].B);j("GdrawOptions",m[F].R)};
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0])}})()