var photosjson=null;jQuery(function(){$("form[name='dummy-newsletter'] input.newsletter").blur(function(){if(this.value=='')this.value='Enter Email to receive updates';});$("form[name='dummy-newsletter'] input.newsletter").focus(function(){if(this.value=='Enter Email to receive updates')this.value='';});$("form[name='dummy-newsletter'] input[type='image']").click(function(){$(this).unbind();var url=window.location.href;var arr=url.split("/");post_to_url(arr[0]+"//"+arr[2]+"/user/register",{'email':$("form[name='dummy-newsletter'] input.newsletter").val()},'post');return false;});$("#content").mouseover(function(){$(".flydown:visible:not(.active)").hide();});$("a.see-all, .see-all a").click(function(){$(".node-type-article #comments").slideDown(300);hashstring=this.href.substring(this.href.lastIndexOf("#"));setTimeout(function(){window.location=(hashstring)?hashstring:'#comments';},350);return false;});if(window.location.hash.substring(1,8)=='comment'){$("#comments").show();window.location=window.location.hash;}
if($("area.active").length){setTimeout(function(){showFlydown($("area.active")[0],false);},1);}
$(".gallery-thumb a").click(function(){Gallery.setImage(this.className);return false;});$(".gallery-prev").click(function(){Gallery.prev();return false;});$(".gallery-next").click(function(){Gallery.next();return false;});$("#article-slidebox").css("height",$("#article-slidebox").height()+"px");$("#article-slidebox .items").css("position","absolute");$("#article-slidebox.scrollable").scrollable({size:4});$(".prevPage,.nextPage").mouseover(function(){$(this).addClass("hover");});$(".prevPage,.nextPage").mouseout(function(){$(this).removeClass("hover");});numDots=$("#article-slidebox-holder .navi a").length;if(numDots){$("#article-slidebox-holder .navi").css("left",'-'+(numDots*3)+'px');}
if(photosjson!=null){Gallery.photos=photosjson;Gallery.init();}
$("#hidenews").click(function(){$(".block-breaking-news").hide();$.cookie("hidenews",1);return false;})
if($.cookie("hidenews")){}
$("#content-area .view-blogs .share a").each(function(i,el){var object=SHARETHIS.addEntry({title:"share",url:el.href,summary:"Sharing is good for the soul."},{button:false,offsetLeft:-190});object.attachButton(el);});$("#edit-lang").msDropDown();})
function translateRedirect(el){path=Drupal.settings.basePath+el.value;window.location=path;return false;}
jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options.expires=-1;}
var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toUTCString();}
var path=options.path?'; path='+(options.path):'';var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break;}}}
return cookieValue;}};var Gallery={}
Gallery.pos=0;Gallery.next=function(){nextPos=(typeof gallery[Gallery.pos+1]!='undefined')?Gallery.pos+1:0;Gallery.setImage(nextPos);}
Gallery.prev=function(){prevPos=(Gallery.pos!=0)?Gallery.pos-1:Gallery.photos.length-1;Gallery.setImage(prevPos);}
Gallery.setImage=function(pos){gallery=Gallery.photos;if(typeof gallery[pos]!='undefined'){$("#gallery-image").attr("src",gallery[pos].src);$("#gallery-image").parent("a").attr("href",gallery[pos].href);$("#gallery-image-credit").html(gallery[pos].credit);$("#gallery-image-caption").html(gallery[pos].caption);$("#gallery-image-title").html(gallery[pos].title);$(".gallery-thumb").removeClass("active");$(".gallery-thumb.thumb-"+pos).addClass("active");Gallery.pos=parseInt(pos);if(gallery[pos].video){$("#gallery-image").hide();$("#gallery-video").html(gallery[pos].video);}else{$("#gallery-image").show();$("#gallery-video").html("");}
nextPos=parseInt(pos)+1;if(typeof gallery[nextPos]!='undefined'){preload=new Image();preload.src=gallery[nextPos].src;}
if(pos){}}}
Gallery.init=function(){$("#gallery-count").html(Gallery.photos.length);if(!Gallery.photos.length){$("#gallery-image-info").hide();$("#gallery-image-holder").html("This gallery is empty.").css("height","auto");}else{startPos=0;if(imgNid=parseInt(document.location.hash.substring(1))){for(i in Gallery.photos){if(Gallery.photos[i].nid==imgNid){startPos=i;}}}
Gallery.setImage(startPos);}}
var flydownTimer=false;function showFlydown(obj,id){if(!flydownTimer){flydownTimer=setTimeout(function(){showFlydown(obj,id);},100);return;}
else{flydownTimer=false;}
var X_OFFSET=-30;var Y_OFFSET=6;var imgPos=$('#navitems').position();var coords=obj.coords.split(",");if(!id){$items=$('#menu-active');}else{$items=$('#'+id);}
$items.css("top",imgPos.top-Y_OFFSET+"px");$items.css("margin-left",(5+parseInt(coords[0]))+"px");if(!id){$items.show().fadeIn(0,1);}else{$(".flydown:not(.active)").fadeOut("fast");$items.mouseout(function(){$(this).fadeOut("fast");});$items.mouseover(function(){$(this).stop().fadeIn(0,1);});$items.show().stop().fadeTo(0,1);}}
function post_to_url(path,params,method){method=method||"post";var form=document.createElement("form");form.setAttribute("method",method);form.setAttribute("action",path);for(var key in params){if(params.hasOwnProperty(key)){var hiddenField=document.createElement("input");hiddenField.setAttribute("type","hidden");hiddenField.setAttribute("name",key);hiddenField.setAttribute("value",params[key]);form.appendChild(hiddenField);}}
document.body.appendChild(form);form.submit();}