// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var k=this,aa=function(a,b,c){return a.call.apply(a.bind,arguments)},ba=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return q.apply(null,arguments)},ca=null;
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return q.apply(null,c)}return q(this,a)};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var da=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,ea=function(a){if(null==a)return String(a);var b=da.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},fa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ga=function(a){if(!a||"object"!=ea(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!fa(a,"constructor")&&!fa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||fa(a,c)};var ha=function(){},z=function(a){return"function"==typeof a},A=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ia=function(a){return"number"==ea(a)&&!isNaN(a)},ja=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ka=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},B=function(a){return Math.round(Number(a))||0},la=function(a){var b=[];if(A(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));
return b},C=function(){this.prefix="gtm.";this.oa={}};C.prototype.set=function(a,b){this.oa[this.prefix+a]=b};C.prototype.get=function(a){return this.oa[this.prefix+a]};C.prototype.contains=function(a){return void 0!==this.get(a)};
var ma=function(a,b,c){try{return a["1"](a,b||ha,c||ha)}catch(d){}return!1},na=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ka(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},oa=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},pa=function(a){for(var b=0;b<a.length;b++)a[b]()},qa=(new Date).getTime(),ra=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c};var D=window,E=document,sa=navigator,G=function(a,b){var c=D[a],d="var "+a+";";if(k.execScript)k.execScript(d,"JavaScript");else if(k.eval)if(null==ca&&(k.eval("var _et_ = 1;"),"undefined"!=typeof k._et_?(delete k._et_,ca=!0):ca=!1),ca)k.eval(d);else{var e=k.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(d));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");D[a]=void 0===c?b:c;return D[a]},K=function(a,
b,c,d){return(d||"http:"!=D.location.protocol?a:b)+c},ta=function(a){var b=E.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},ua=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},L=function(a,b,c){var d=E.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ua(d,b);c&&(d.onerror=c);ta(d)},va=function(a,b){var c=E.createElement("iframe");c.height="0";c.width="0";c.style.display=
"none";c.style.visibility="hidden";ta(c);ua(c,b);void 0!==a&&(c.src=a);return c},O=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},Q=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},R=function(a){D.setTimeout(a,0)},wa=!1,xa=[],ya=function(a){if(!(a&&"readystatechange"==a.type&&"interactive"!=E.readyState&&"complete"!=E.readyState||wa)){wa=!0;for(var b=0;b<xa.length;b++)xa[b]()}},
za=0,Aa=function(){if(!wa&&140>za){za++;try{E.documentElement.doScroll("left"),ya()}catch(a){D.setTimeout(Aa,50)}}},Ca=function(a){var b=E.getElementById(a);if(b&&Ba(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Ba(document.all[a][c],"id")==a)return document.all[a][c];return b},Ba=function(a,b){return a&&b&&a.attributes[b]?a.attributes[b].value:null},Da=function(a){return a.target||a.srcElement||{}},Ea=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&
100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Fa=!1,Ga=[],Ha=function(){if(!Fa){Fa=!0;for(var a=0;a<Ga.length;a++)Ga[a]()}},Ia=function(a){a=a||D;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)};var Ja=new C,Ka={},La=ha,Na=[],Oa=!1,Ra={set:function(a,b){Pa(Qa(a,b),Ka)},get:function(a){return S(a,2)}},Sa=function(a){var b=!1;return function(){!b&&z(a)&&R(a);b=!0}},Ta=function(){for(var a=!1;!Oa&&0<Na.length;){Oa=!0;var b=Na.shift();if(z(b))try{b.call(Ra)}catch(c){}else if(A(b))e:{var d=b;if("string"==ea(d[0])){for(var e=d[0].split("."),f=e.pop(),g=d.slice(1),h=Ka,p=0;p<e.length;p++){if(void 0===h[e[p]])break e;h=h[e[p]]}try{h[f].apply(h,g)}catch(n){}}}else{var l;var r=b,m=void 0;for(m in r)if(r.hasOwnProperty(m)){var s=
m,y=r[m];Ja.set(s,y);Pa(Qa(s,y),Ka)}var F=r.event;if(F){var u=Sa(r.eventCallback),M=r.eventTimeout;M&&D.setTimeout(u,Number(M));l=La(F,u)}else l=!1;a=l||a}Oa=!1}return!a},S=function(a,b){if(2==b){for(var c=Ka,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Ja.get(a)},Qa=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},Pa=function(a,b){for(var c in a)if(fa(a,c)){var d=a[c];A(d)?(A(b[c])||(b[c]=[]),Pa(d,
b[c])):ga(d)?(ga(b[c])||(b[c]={}),Pa(d,b[c])):b[c]=d}};var Ua={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Va={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],
nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Wa=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Xa=function(){var a=S("gtm.whitelist"),b=a&&Wa(la(a),Ua),c=S("gtm.blacklist")||S("tagTypeBlacklist"),d=c&&Wa(la(c),Va),e={};return function(f){var g=f&&f["1"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)e:{if(0>ja(b,g.a))if(g.b&&0<g.b.length)for(var p=0;p<g.b.length;p++){if(0>
ja(b,g.b[p])){h=!1;break e}}else{h=!1;break e}h=!0}var n=!1;if(c){var l;if(!(l=0<=ja(d,g.a)))e:{for(var r=g.b||[],m=new C,s=0;s<d.length;s++)m.set(d[s],!0);for(s=0;s<r.length;s++)if(m.get(r[s])){l=!0;break e}l=!1}n=l}return e[g.a]=!h||n}};var Ya=null;var _e=function(){return Ya};_e.a="e";_e.b=["google"];var _v=function(a){var b=S(a["3"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(){return String(S("gtm.referrer")||E.referrer)};_f.a="f";_f.b=["google"];
var Za=E.createElement("a"),$a=function(a){var b=D.location,c=b.hash?b.href.replace(b.hash,""):b.href,d=S("gtm.url");d&&(Za.href=c=String(d),b=Za);var e=(b.protocol.replace(":","")||D.location.protocol.replace(":","")).toLowerCase();switch(a["0"]){case "protocol":c=e;break;case "host":c=(b.hostname||D.location.hostname).split(":")[0].toLowerCase();break;case "port":c=String(1*(b.hostname?b.port:D.location.port)||("http"==e?80:"https"==e?443:""));break;case "path":c="/"==b.pathname.substr(0,1)?b.pathname:"/"+b.pathname;
break;case "query":c=b.search.replace("?","");break;case "fragment":c=b.hash.replace("#","")}
return c},_u=$a;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[""])==String(a[""])};_eq.a="eq";_eq.b=["google"];var eb=function(a,b){return a<b?-1:a>b?1:0};var fb,gb,hb,ib,jb=function(){return k.navigator?k.navigator.userAgent:null};ib=hb=gb=fb=!1;var kb;if(kb=jb()){var lb=k.navigator;fb=0==kb.lastIndexOf("Opera",0);gb=!fb&&(-1!=kb.indexOf("MSIE")||-1!=kb.indexOf("Trident"));hb=!fb&&-1!=kb.indexOf("WebKit");ib=!fb&&!hb&&!gb&&"Gecko"==lb.product}var T=gb,mb=ib,nb=hb,ob=function(){var a=k.document;return a?a.documentMode:void 0},rb;
e:{var sb="",tb;if(fb&&k.opera)var ub=k.opera.version,sb="function"==typeof ub?ub():ub;else if(mb?tb=/rv\:([^\);]+)(\)|;)/:T?tb=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:nb&&(tb=/WebKit\/(\S+)/),tb)var vb=tb.exec(jb()),sb=vb?vb[1]:"";if(T){var wb=ob();if(wb>parseFloat(sb)){rb=String(wb);break e}}rb=sb}
var xb=rb,yb={},U=function(a){var b;if(!(b=yb[a])){for(var c=0,d=String(xb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",p=e[g]||"",n=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(h)||["","",""],m=l.exec(p)||["","",""];if(0==r[0].length&&0==m[0].length)break;c=eb(0==r[1].length?0:parseInt(r[1],10),0==m[1].length?0:parseInt(m[1],10))||eb(0==r[2].length,
0==m[2].length)||eb(r[2],m[2])}while(0==c)}b=yb[a]=0<=c}return b},zb=k.document,Ab=zb&&T?ob()||("CSS1Compat"==zb.compatMode?parseInt(xb,10):5):void 0;if(mb||T){var Bb;if(Bb=T)Bb=T&&9<=Ab;Bb||mb&&U("1.9.1")}T&&U("9");var Gb=function(a,b){var c="";T&&!Cb(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Db)a.srcdoc=d;else if(Eb){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Fb(a,d)},Db=nb&&"srcdoc"in document.createElement("iframe"),Eb=mb||nb||T&&U(11),Fb=function(a,b){T&&U(7)&&!U(10)&&6>Hb()&&Ib(b)&&(b=Jb(b));var c=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};T&&!Cb(a)?Kb(a,c):c()},Hb=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Cb=function(a){try{var b;var c=a.contentWindow;try{b=!!c&&null!=c.location.href}catch(d){b=!1}return b}catch(e){return!1}},Lb=0,Kb=function(a,b){var c="goog_rendering_callback"+Lb++;window[c]=b;T&&U(6)&&!U(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+document.domain+
'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Ib=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Jb=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=
String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Tb=function(a,b,c,d){return function(e){e=e||D.event;var f=Da(e),g=!1;if(3!==e.which||"CLICK"!=a&&"LINK_CLICK"!=a)if(2!==e.which&&(null!=e.which||4!=e.button)||"LINK_CLICK"!=a)if("LINK_CLICK"==a&&(f=Ea(f,["a"]),g=!f||!f.href||e.ctrlKey||e.shiftKey||e.altKey||!0===e.metaKey),e.defaultPrevented||!1===e.returnValue||e.$a&&e.$a()){if(!c&&f){var h={simulateDefault:!1};V(a,f,h,d)}}else{var p=/(iPad|iPhone|iPod)/g.test(sa.userAgent);if(f){var h={},n=V(a,f,h,d);h.simulateDefault=!n&&b&&!g;if(h.simulateDefault){var l=
Sb(f).toLowerCase();switch(l){case "_blank":p?(h.simulateDefault=!1,g=!0):(h.targetWindowName="gtm_autoEvent_"+(new Date).getTime(),h.targetWindow=D.open("",h.targetWindowName));break;case "":h.targetWindow=D.frames.self;break;case "_self":case "_parent":case "_top":h.targetWindow=D.frames[l.substring(1)];break;default:p&&!D.frames[l]?(h.simulateDefault=!1,g=!0):(D.frames[l]||(h.targetWindowName=l),h.targetWindow=D.frames[l]||D.open("",l))}!g&&e.preventDefault&&e.preventDefault()}e.returnValue=n||
!b||g;return e.returnValue}return!0}}},V=function(a,b,c,d){var e=d||2E3,f={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Ba(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":f.event="gtm.linkClick";f["gtm.elementUrl"]=b.href;f.eventTimeout=e;f["gtm.elementText"]=b.innerText||b.textContent||"";f.eventCallback=Ub(b,c);break;case "FORM_SUBMIT":f.event="gtm.formSubmit";f["gtm.elementUrl"]=b.action;c.jsFormSubmit?c.waitForTags&&(f.eventTimeout=
e,f.eventCallback=function(){E.gtmSubmitFormNow=!0;Wb(b).call(b)}):(f.eventTimeout=e,f.eventCallback=Vb(b,c));break;case "CLICK":f.event="gtm.click";f["gtm.elementText"]=b.innerText||b.textContent||"";f["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return D["dataLayer"].push(f)},Sb=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "form":b="_self"}return b},Ub=function(a,b,c){return function(){b.simulateDefault&&
(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||(new Date).getTime(),500>(new Date).getTime()-c&&D.setTimeout(Ub(a,b,c),25)))}},Vb=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);E.gtmSubmitFormNow=!0;Wb(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||(new Date).getTime(),500>(new Date).getTime()-c&&D.setTimeout(Vb(a,b,c),25)}},Xb=function(a,b,c,d){var e,f;switch(a){case "CLICK":if(E.gtmHasClickListenerTag)return;
E.gtmHasClickListenerTag=!0;e="click";f=function(a){var b=Da(a);b&&V("CLICK",b,{},d);return!0};break;case "LINK_CLICK":if(E.gtmHasLinkClickListenerTag)return;E.gtmHasLinkClickListenerTag=!0;e="click";f=Tb(a,b||!1,c||!1,d);break;case "FORM_SUBMIT":if(E.gtmHasFormSubmitListenerTag)return;E.gtmHasFormSubmitListenerTag=!0;e="submit";f=Tb(a,b||!1,c||!1,d);break;default:return}Q(E,e,f,!1)},Wb=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
E.gtmFormElementSubmitter||(E.gtmFormElementSubmitter=document.createElement("form"));return E.gtmFormElementSubmitter.submit};var $b,ac;
var kc=function(a){return function(){}},lc=function(a){return function(){}};var wc=function(){var a=vc.Ua,b=window||k,c=b.onerror,d=!1;nb&&!U("535.3")&&(d=!d);b.onerror=function(b,f,g,h,p){c&&c(b,f,g,h,p);a({message:b,fileName:f,Ta:g,pb:h,error:p});return d}};var Uc=function(){this.f=[]};Uc.prototype.set=function(a,b){this.f.push([a,b]);return this};Uc.prototype.B=function(a,b){for(var c={},d=0;d<this.f.length;d++){var e=Z(this.f[d][0],a,b),f=Z(this.f[d][1],a,b);c[e]=f}return c};var Vc=function(a){this.index=a};Vc.prototype.B=function(a,b){var c=Wc[this.index];if(c&&!b(c)){var d=c["2"];if(a){if(a.get(d))return;a.set(d,!0)}c=Z(c,a,b);a&&a.set(d,!1);return ma(c)}};
for(var _M=function(a){return new Vc(a)},Yc=function(a){this.B=function(b,c){for(var d=[],e=0;e<a.length;e++)d.push(Z(Xc[a[e]],b,c));return d.join("")}},_T=function(a){return new Yc(arguments)},Zc=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.B=function(c,d){if(a[0]instanceof Vc&&b(8)&&b(16))return'google_tag_manager["GTM-NVS4ZD"].macro('+
a[0].index+")";for(var e=String(Z(a[0],c,d)),f=1;f<a.length;f++)e=Y[a[f]](e);return e}},_E=function(a,b){return new Zc(arguments)},Z=function(a,b,c){var d=a;if(a instanceof Vc||a instanceof Uc||a instanceof Yc||a instanceof Zc)return a.B(b,c);if(A(a))for(var d=[],e=0;e<a.length;e++)d[e]=Z(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Z(a[f],b,c))}return d},$c=function(a,b){var c=b[a],d=c;if(c instanceof Vc||c instanceof Zc||c instanceof Yc)d=c;else if(A(c))for(var d=
[],e=0;e<c.length;e++)d[e]=$c(c[e],b);else if("object"==typeof c){var d=new Uc,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],$c(c[f],b))}return d},cd=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Xc[e[1]]);if(1==a)for(var f=ad(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=bd[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=ad(e[g])}return c},ad=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<dd;c+=6,d++){var e=a&&a.charCodeAt(d)||
65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},dd=21,ed=[_u,'url hostname','host','url',_f,'referrer','url path','path',_v,'element','gtm.element',_e,'event','element id','gtm.elementId','element classes','gtm.elementClasses','element url','gtm.elementUrl','element target','gtm.elementTarget'],fd=[],gd=0;gd<ed.length;gd++)fd[gd]=$c(gd,ed);var Xc=fd,bd=cd(0,"1:0,2:1,0:2,2:3,1:4,2:5,2:6,0:7,1:8,2:9,3:10,1:11,2:12,2:13,3:14,2:15,3:16,2:17,3:18,2:19,3:20"),Wc=cd(1,"H,J,w,BD,Ac,AgB,AEG,AEY,AEgB,AEAG"),hd=cd(1,""),$=cd(1,""),id=cd(2,"");var qd=function(){var a=this;this.r=!1;this.u=[];this.L=[];this.La=function(){a.r||pa(a.u);a.r=!0};this.Ka=function(){a.r||pa(a.L);a.r=!0};this.M=ha},rd=function(){this.h=[];this.aa={};this.N=[];this.o=0};rd.prototype.addListener=function(a){this.N.push(a)};var sd=function(a,b,c,d){if(!c.r){a.h[b]=c;void 0!==d&&(a.aa[b]=d);a.o++;var e=function(){0<a.o&&a.o--;0<a.o||pa(a.N)};c.u.push(e);c.L.push(e)}};var td=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=hd[b]&&Z(hd[b],new C,c);a[b]=[d&&ma(d),d]}return a[b]}},ud=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.i(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.i(e[d],a.c)[0])return!1;return!0},vd=function(a,b){return function(){ma(a,b.La,b.Ka)}},La=function(a,b){Ya=a;S("tagTypeBlacklist");for(var c={name:a,Ia:b||ha,w:ad(),A:ad(),i:td(),c:Xa()},d=0;d<id.length;d++)if(ud(c,id[d])){for(var e=c,f=id[d],g=f[1],h=0;h<
g.length;h++)e.w[g[h]]=!0;for(var p=f[3],h=0;h<p.length;h++)e.A[p[h]]=!0}var n=[];for(var l=0;l<dd;l++)if(c.w[l]&&!c.A[l])if(c.c($[l])){}else{n[l]=Z($[l],new C,c.c);}c.P=n;for(var r=new rd,m=0;m<dd;m++)if(c.w[m]&&!c.A[m]&&
!c.c($[m])){var s=c.P[m],y=new qd;y.u.push(kc(s));y.L.push(lc(s));y.M=vd(s,y);sd(r,m,y,s[""])}r.addListener(c.Ia);for(var F=[],u=0;u<r.h.length;u++){var M=r.h[u];if(M){var H=r.aa[u];void 0!==H?H!=u&&r.h[H]&&r.h[H].u.push(M.M):F.push(u)}}for(u=0;u<F.length;u++)r.h[F[u]].M();0<r.o||pa(r.N);Ya=null;return 0<c.P.length};var wd={macro:function(a){var b;if(b=Wc[a]){var c=_M(a),d=Xa();b=Z(c,new C,d)}return b},Za:function(){var a=D.google_tag_manager;a||(a=D.google_tag_manager={});a["GTM-NVS4ZD"]||(a["GTM-NVS4ZD"]=wd)}};wd.Za();
(function(){var a=G("dataLayer",[]),b=D.google_tag_manager;xa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Ga.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Na.push.apply(Na,b);300<this.length;)this.shift();return Ta()};Na.push.apply(Na,a.slice(0));R(Ta)})();
if("interactive"==E.readyState||"complete"==E.readyState)ya();else{Q(E,"DOMContentLoaded",ya);Q(E,"readystatechange",ya);if(E.createEventObject&&E.documentElement.doScroll){var xd=!0;try{xd=!D.frameElement}catch(yd){}xd&&Aa()}Q(D,"load",ya)}"complete"===E.readyState?Ha():Q(D,"load",Ha);var _vs="res_ts:1389112139148000,srv_cl:61597519,ds:live,cv:1";
})()
