// Created by iWeb 3.0.1 local-build-20091129

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_2:new IWShadow({blurRadius:8,offset:new IWPoint(0.0000,-5.0000),color:'#000000',opacity:0.200000}),stroke_0:new IWEmptyStroke(),shadow_0:new IWShadow({blurRadius:8,offset:new IWPoint(-0.0000,5.0000),color:'#000000',opacity:0.200000}),shadow_1:new IWShadow({blurRadius:8,offset:new IWPoint(-0.0000,5.0000),color:'#000000',opacity:0.200000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Tickets_files/TicketsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');fixAllIEPNGs('Media/transparent.gif');fixupAllIEPNGBGs();IMpreload('Tickets_files','shapeimage_19','0');IMpreload('Tickets_files','shapeimage_19','1');IMpreload('Tickets_files','shapeimage_19','2');IMpreload('Tickets_files','shapeimage_19','3');applyEffects()}
