document.write("<tr>");
document.write("<td align='center' valign='middle' colspan='3'>");
document.write("<p class='footer'>");
document.write("<a href='../index.html'> Home </a>&nbsp;|&nbsp;");
document.write("<a href='../contact/index.html'> Contact Us </a>&nbsp;|&nbsp;");
document.write("<a href='../support/index.html'> Donate Now </a>&nbsp;|&nbsp;");
document.write("<a href='../contact/bookings.html'> Bookings </a>&nbsp;|&nbsp;");
document.write("<a href='../about/join.html'> Auditions </a>&nbsp;|&nbsp;");
document.write("<a href='../support/store.html'> Store </a>&nbsp;|&nbsp;");
document.write("<a href='../downloads/news/BCC_Brochure.pdf'> BCC Brochure </a>&nbsp;&nbsp;|&nbsp;&nbsp;");
document.write("<a href='../news_events/blog.html'> BCC Blog </a>&nbsp;&nbsp;|&nbsp;&nbsp;");
document.write("<a href='../news_events/newsletters.html'> E-Newsletter</a></p>");
document.write("</td>");
document.write("</tr>");