document.write('<table width="708" height="135px" border="0" cellspacing="0" cellpadding="0" style="padding-bottom:15px;" align="center">');
document.write('<tr>');
document.write('<td rowspan="3" width="272" height="111px" align="right" valign="top"><a href="../index.html"><img src="../images/all/BCC_logo.gif" alt="BCC_logo" name="bcc_logo" width="272" height="111" border="0" /></a></td>');
document.write('<td width="192" align="right">');
document.write('<a href="../contact/bookings.html">');
document.write('<img src="../images/all/btn_BookChoirOff.gif" alt="Booking The Choir" name="btn_bookingChoirOff" width="148" height="29" border="0" id="btn_bookingChoirOff" onmouseover="MM_swapImage(\'btn_bookingChoirOff\',\'\',\'../images/all/btn_BookChoirOn.gif\',1)" onmouseout="MM_swapImgRestore()" /></a></td>');
 document.write('<td width="126" align="right"><a href="../support/index.html"><img src="../images/all/btn_donateNowOff.gif" alt="Donate Now" name="btn_donateNowOff" width="109" height="29" border="0" id="btn_donateNowOff" onmouseover="MM_swapImage(\'btn_donateNowOff\',\'\',\'../images/all/btn_donateNowOn.gif\',1)" onmouseout="MM_swapImgRestore()" /></a></td>');
document.write('<td width="118" align="right" valign="top" class="logo_good_search"><a href="http://www.goodsearch.com/" target="_blank"><img src="http://www.goodsearch.com/_gfx/goodsearch-95x45.gif" width="95" height="45" alt="GoodSearch: You Search...We Give!" border="0" /></a>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td rowspan="1" colspan="3" height="50px" valign="bottom" align="right" class="audio_player">');
document.write('<script language="javascript">');
document.write('if (AC_FL_RunContent == 0) {');
document.write('alert("This page requires AC_RunActiveContent.js.");');
document.write('} else {');
document.write('AC_FL_RunContent( "codebase","http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0","width","390","height","40","id","audioplayer","align","bottom","src","../flash/audioplayer","wmode","transparent","quality","high","bgcolor","#ffffff","name","audioplayer","salign","b","allowscriptaccess","sameDomain","allowfullscreen","false","pluginspage","http://www.macromedia.com/go/getflashplayer","movie","../flash/audioplayer" );} //end AC code');
document.write('</script>');
document.write('<noscript>');
document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="390" height="40" id="audioplayer" align="bottom">');
document.write('<param name="allowScriptAccess" value="sameDomain" />');
document.write('<param name="allowFullScreen" value="false" />');
document.write('<param name="wmode" value="transparent" />');
document.write('<param name="movie" value="../flash/audioplayer.swf" /><param name="salign" value="b" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />');
document.write('<embed src="../flash/audioplayer.swf" wmode="transparent" quality="high" bgcolor="#ffffff" width="390" height="40" name="audioplayer" align="bottom" salign="b" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />');
document.write('</object>');
document.write('</noscript>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td rowspan="1" colspan="3" height="20px" valign="top">');
document.write('<script language="javascript">');
document.write('if (AC_FL_RunContent == 0) {');
document.write('alert("This page requires AC_RunActiveContent.js.");');
document.write('} else {');
document.write('AC_FL_RunContent( "codebase","http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0","width","436","height","20","id","newsTicker","align","top","src","../flash/newsTicker_sub","quality","high","scale","noscale","wmode","transparent","bgcolor","#ffffff","name","newsTicker_sub","allowscriptaccess","sameDomain","allowfullscreen","false","pluginspage","http://www.macromedia.com/go/getflashplayer","movie","../flash/newsTicker_sub" );} //end AC code');
document.write('</script>');
document.write('<noscript>');
document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="436" height="20" id="newsTicker" align="top">');
document.write('<param name="allowScriptAccess" value="sameDomain" />');
document.write('<param name="allowFullScreen" value="false" />');
document.write('<param name="movie" value="../flash/newsTicker_sub.swf" /><param name="quality" value="high" /><param name="scale" value="noscale" /><param name="wmode" value="transparent" /><param name="bgcolor" value="#ffffff" />');
document.write('<embed src="../flash/newsTicker_sub.swf" quality="high" scale="noscale" wmode="transparent" bgcolor="#ffffff" width="436" height="20" name="newsTicker_sub" align="top" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />');
document.write('</object>');
document.write('</noscript>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');